/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PersonaVONombresDIANRUT
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class PersonaVONombresDIANRUT {
  @SerializedName("primerNombre")
  private String primerNombre = null;

  @SerializedName("segundoNombre")
  private String segundoNombre = null;

  @SerializedName("primerApellido")
  private String primerApellido = null;

  @SerializedName("segundoApellido")
  private String segundoApellido = null;

  @SerializedName("tipoNombre")
  private Integer tipoNombre = null;

  public PersonaVONombresDIANRUT primerNombre(String primerNombre) {
    this.primerNombre = primerNombre;
    return this;
  }

   /**
   * Primer nombre registrado en el RUT.
   * @return primerNombre
  **/
  @Schema(example = "JUAN", required = true, description = "Primer nombre registrado en el RUT.")
  public String getPrimerNombre() {
    return primerNombre;
  }

  public void setPrimerNombre(String primerNombre) {
    this.primerNombre = primerNombre;
  }

  public PersonaVONombresDIANRUT segundoNombre(String segundoNombre) {
    this.segundoNombre = segundoNombre;
    return this;
  }

   /**
   * Segundo nombre registrado en el RUT.
   * @return segundoNombre
  **/
  @Schema(example = "CARLOS", description = "Segundo nombre registrado en el RUT.")
  public String getSegundoNombre() {
    return segundoNombre;
  }

  public void setSegundoNombre(String segundoNombre) {
    this.segundoNombre = segundoNombre;
  }

  public PersonaVONombresDIANRUT primerApellido(String primerApellido) {
    this.primerApellido = primerApellido;
    return this;
  }

   /**
   * Primer apellido registrado en el RUT.
   * @return primerApellido
  **/
  @Schema(example = "TORRES", required = true, description = "Primer apellido registrado en el RUT.")
  public String getPrimerApellido() {
    return primerApellido;
  }

  public void setPrimerApellido(String primerApellido) {
    this.primerApellido = primerApellido;
  }

  public PersonaVONombresDIANRUT segundoApellido(String segundoApellido) {
    this.segundoApellido = segundoApellido;
    return this;
  }

   /**
   * Segundo apellido registrado en el RUT.
   * @return segundoApellido
  **/
  @Schema(example = "ROJAS", description = "Segundo apellido registrado en el RUT.")
  public String getSegundoApellido() {
    return segundoApellido;
  }

  public void setSegundoApellido(String segundoApellido) {
    this.segundoApellido = segundoApellido;
  }

  public PersonaVONombresDIANRUT tipoNombre(Integer tipoNombre) {
    this.tipoNombre = tipoNombre;
    return this;
  }

   /**
   * Tipo de nombre registrado en el RUT.
   * @return tipoNombre
  **/
  @Schema(example = "1", required = true, description = "Tipo de nombre registrado en el RUT.")
  public Integer getTipoNombre() {
    return tipoNombre;
  }

  public void setTipoNombre(Integer tipoNombre) {
    this.tipoNombre = tipoNombre;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonaVONombresDIANRUT personaVONombresDIANRUT = (PersonaVONombresDIANRUT) o;
    return Objects.equals(this.primerNombre, personaVONombresDIANRUT.primerNombre) &&
        Objects.equals(this.segundoNombre, personaVONombresDIANRUT.segundoNombre) &&
        Objects.equals(this.primerApellido, personaVONombresDIANRUT.primerApellido) &&
        Objects.equals(this.segundoApellido, personaVONombresDIANRUT.segundoApellido) &&
        Objects.equals(this.tipoNombre, personaVONombresDIANRUT.tipoNombre);
  }

  @Override
  public int hashCode() {
    return Objects.hash(primerNombre, segundoNombre, primerApellido, segundoApellido, tipoNombre);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonaVONombresDIANRUT {\n");
    
    sb.append("    primerNombre: ").append(toIndentedString(primerNombre)).append("\n");
    sb.append("    segundoNombre: ").append(toIndentedString(segundoNombre)).append("\n");
    sb.append("    primerApellido: ").append(toIndentedString(primerApellido)).append("\n");
    sb.append("    segundoApellido: ").append(toIndentedString(segundoApellido)).append("\n");
    sb.append("    tipoNombre: ").append(toIndentedString(tipoNombre)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
