/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PersonaVONombresRNMC
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class PersonaVONombresRNMC {
  @SerializedName("primerNombre")
  private String primerNombre = null;

  @SerializedName("tipoNombre")
  private Integer tipoNombre = null;

  public PersonaVONombresRNMC primerNombre(String primerNombre) {
    this.primerNombre = primerNombre;
    return this;
  }

   /**
   * Nombre completo registrado en el RNMC.
   * @return primerNombre
  **/
  @Schema(example = "MENDOZA BAUTISTA PEDRO ANTONIO", required = true, description = "Nombre completo registrado en el RNMC.")
  public String getPrimerNombre() {
    return primerNombre;
  }

  public void setPrimerNombre(String primerNombre) {
    this.primerNombre = primerNombre;
  }

  public PersonaVONombresRNMC tipoNombre(Integer tipoNombre) {
    this.tipoNombre = tipoNombre;
    return this;
  }

   /**
   * Tipo de nombre
   * @return tipoNombre
  **/
  @Schema(example = "3", required = true, description = "Tipo de nombre")
  public Integer getTipoNombre() {
    return tipoNombre;
  }

  public void setTipoNombre(Integer tipoNombre) {
    this.tipoNombre = tipoNombre;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonaVONombresRNMC personaVONombresRNMC = (PersonaVONombresRNMC) o;
    return Objects.equals(this.primerNombre, personaVONombresRNMC.primerNombre) &&
        Objects.equals(this.tipoNombre, personaVONombresRNMC.tipoNombre);
  }

  @Override
  public int hashCode() {
    return Objects.hash(primerNombre, tipoNombre);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonaVONombresRNMC {\n");
    
    sb.append("    primerNombre: ").append(toIndentedString(primerNombre)).append("\n");
    sb.append("    tipoNombre: ").append(toIndentedString(tipoNombre)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
