/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PersonaVONombresSISBENPUNTAJE
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class PersonaVONombresSISBENPUNTAJE {
  @SerializedName("primerNombre")
  private String primerNombre = null;

  @SerializedName("primerApellido")
  private String primerApellido = null;

  @SerializedName("tipoNombre")
  private Integer tipoNombre = null;

  public PersonaVONombresSISBENPUNTAJE primerNombre(String primerNombre) {
    this.primerNombre = primerNombre;
    return this;
  }

   /**
   * Primer nombre registrado en Sisbén.
   * @return primerNombre
  **/
  @Schema(example = "ALIX", required = true, description = "Primer nombre registrado en Sisbén.")
  public String getPrimerNombre() {
    return primerNombre;
  }

  public void setPrimerNombre(String primerNombre) {
    this.primerNombre = primerNombre;
  }

  public PersonaVONombresSISBENPUNTAJE primerApellido(String primerApellido) {
    this.primerApellido = primerApellido;
    return this;
  }

   /**
   * Primer apellido registrado en Sisbén.
   * @return primerApellido
  **/
  @Schema(example = "GARCIA GELVEZ", required = true, description = "Primer apellido registrado en Sisbén.")
  public String getPrimerApellido() {
    return primerApellido;
  }

  public void setPrimerApellido(String primerApellido) {
    this.primerApellido = primerApellido;
  }

  public PersonaVONombresSISBENPUNTAJE tipoNombre(Integer tipoNombre) {
    this.tipoNombre = tipoNombre;
    return this;
  }

   /**
   * Tipo de nombre
   * @return tipoNombre
  **/
  @Schema(example = "2", required = true, description = "Tipo de nombre")
  public Integer getTipoNombre() {
    return tipoNombre;
  }

  public void setTipoNombre(Integer tipoNombre) {
    this.tipoNombre = tipoNombre;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonaVONombresSISBENPUNTAJE personaVONombresSISBENPUNTAJE = (PersonaVONombresSISBENPUNTAJE) o;
    return Objects.equals(this.primerNombre, personaVONombresSISBENPUNTAJE.primerNombre) &&
        Objects.equals(this.primerApellido, personaVONombresSISBENPUNTAJE.primerApellido) &&
        Objects.equals(this.tipoNombre, personaVONombresSISBENPUNTAJE.tipoNombre);
  }

  @Override
  public int hashCode() {
    return Objects.hash(primerNombre, primerApellido, tipoNombre);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonaVONombresSISBENPUNTAJE {\n");
    
    sb.append("    primerNombre: ").append(toIndentedString(primerNombre)).append("\n");
    sb.append("    primerApellido: ").append(toIndentedString(primerApellido)).append("\n");
    sb.append("    tipoNombre: ").append(toIndentedString(tipoNombre)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
