/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones {
  @SerializedName("regimen")
  private String regimen = null;

  @SerializedName("administradora")
  private String administradora = null;

  @SerializedName("estadoAfiliacion")
  private String estadoAfiliacion = null;

  @SerializedName("fechaAfiliacion")
  private String fechaAfiliacion = null;

  @SerializedName("afiliacionSubsidiada")
  private String afiliacionSubsidiada = null;

  public ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones regimen(String regimen) {
    this.regimen = regimen;
    return this;
  }

   /**
   * Régimen de pensiones.
   * @return regimen
  **/
  @Schema(example = "Activo cotizante", required = true, description = "Régimen de pensiones.")
  public String getRegimen() {
    return regimen;
  }

  public void setRegimen(String regimen) {
    this.regimen = regimen;
  }

  public ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones administradora(String administradora) {
    this.administradora = administradora;
    return this;
  }

   /**
   * Administradora de pensiones.
   * @return administradora
  **/
  @Schema(example = "COMPAÑIA COLOMBIANA ADMINISTRADORA DE FONDOS DE PENSIONES Y CESANTIAS SA COLFONDOS", required = true, description = "Administradora de pensiones.")
  public String getAdministradora() {
    return administradora;
  }

  public void setAdministradora(String administradora) {
    this.administradora = administradora;
  }

  public ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones estadoAfiliacion(String estadoAfiliacion) {
    this.estadoAfiliacion = estadoAfiliacion;
    return this;
  }

   /**
   * Estado de la afiliación a pensiones.
   * @return estadoAfiliacion
  **/
  @Schema(example = "PENSIONES: AHORRO INDIVIDUAL", required = true, description = "Estado de la afiliación a pensiones.")
  public String getEstadoAfiliacion() {
    return estadoAfiliacion;
  }

  public void setEstadoAfiliacion(String estadoAfiliacion) {
    this.estadoAfiliacion = estadoAfiliacion;
  }

  public ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones fechaAfiliacion(String fechaAfiliacion) {
    this.fechaAfiliacion = fechaAfiliacion;
    return this;
  }

   /**
   * Get fechaAfiliacion
   * @return fechaAfiliacion
  **/
  @Schema(required = true, description = "")
  public String getFechaAfiliacion() {
    return fechaAfiliacion;
  }

  public void setFechaAfiliacion(String fechaAfiliacion) {
    this.fechaAfiliacion = fechaAfiliacion;
  }

  public ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones afiliacionSubsidiada(String afiliacionSubsidiada) {
    this.afiliacionSubsidiada = afiliacionSubsidiada;
    return this;
  }

   /**
   * Indica si la afiliación es subsidiada.
   * @return afiliacionSubsidiada
  **/
  @Schema(example = "- --", required = true, description = "Indica si la afiliación es subsidiada.")
  public String getAfiliacionSubsidiada() {
    return afiliacionSubsidiada;
  }

  public void setAfiliacionSubsidiada(String afiliacionSubsidiada) {
    this.afiliacionSubsidiada = afiliacionSubsidiada;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones responseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones = (ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones) o;
    return Objects.equals(this.regimen, responseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones.regimen) &&
        Objects.equals(this.administradora, responseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones.administradora) &&
        Objects.equals(this.estadoAfiliacion, responseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones.estadoAfiliacion) &&
        Objects.equals(this.fechaAfiliacion, responseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones.fechaAfiliacion) &&
        Objects.equals(this.afiliacionSubsidiada, responseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones.afiliacionSubsidiada);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regimen, administradora, estadoAfiliacion, fechaAfiliacion, afiliacionSubsidiada);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones {\n");
    
    sb.append("    regimen: ").append(toIndentedString(regimen)).append("\n");
    sb.append("    administradora: ").append(toIndentedString(administradora)).append("\n");
    sb.append("    estadoAfiliacion: ").append(toIndentedString(estadoAfiliacion)).append("\n");
    sb.append("    fechaAfiliacion: ").append(toIndentedString(fechaAfiliacion)).append("\n");
    sb.append("    afiliacionSubsidiada: ").append(toIndentedString(afiliacionSubsidiada)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
