/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollectionTblCesantiasGrpCesantias;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollection
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollection {
  @SerializedName("tblCesantiasGrpCesantias")
  private List<ResponseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollectionTblCesantiasGrpCesantias> tblCesantiasGrpCesantias = null;

  public ResponseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollection tblCesantiasGrpCesantias(List<ResponseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollectionTblCesantiasGrpCesantias> tblCesantiasGrpCesantias) {
    this.tblCesantiasGrpCesantias = tblCesantiasGrpCesantias;
    return this;
  }

  public ResponseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollection addTblCesantiasGrpCesantiasItem(ResponseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollectionTblCesantiasGrpCesantias tblCesantiasGrpCesantiasItem) {
    if (this.tblCesantiasGrpCesantias == null) {
      this.tblCesantiasGrpCesantias = new ArrayList<ResponseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollectionTblCesantiasGrpCesantias>();
    }
    this.tblCesantiasGrpCesantias.add(tblCesantiasGrpCesantiasItem);
    return this;
  }

   /**
   * Detalles de afiliación a Cesantías.
   * @return tblCesantiasGrpCesantias
  **/
  @Schema(description = "Detalles de afiliación a Cesantías.")
  public List<ResponseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollectionTblCesantiasGrpCesantias> getTblCesantiasGrpCesantias() {
    return tblCesantiasGrpCesantias;
  }

  public void setTblCesantiasGrpCesantias(List<ResponseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollectionTblCesantiasGrpCesantias> tblCesantiasGrpCesantias) {
    this.tblCesantiasGrpCesantias = tblCesantiasGrpCesantias;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollection responseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollection = (ResponseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollection) o;
    return Objects.equals(this.tblCesantiasGrpCesantias, responseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollection.tblCesantiasGrpCesantias);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tblCesantiasGrpCesantias);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuafVOReportVOLstPensionadosTblCesantiasTblCesantiasGrpCesantiasCollection {\n");
    
    sb.append("    tblCesantiasGrpCesantias: ").append(toIndentedString(tblCesantiasGrpCesantias)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
