/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PersonaVO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.LocalDate;
/**
 * Colombia -  23948865 - Consulta de afiliación a empresas Promotoras de Salud - EPS. (Base de Datos Unificada BDUA).
 */
@Schema(description = "Colombia -  23948865 - Consulta de afiliación a empresas Promotoras de Salud - EPS. (Base de Datos Unificada BDUA).")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseAntecedentesBDUAVO {
  @SerializedName("personaVO")
  private PersonaVO personaVO = null;

  @SerializedName("estado")
  private String estado = null;

  @SerializedName("entidad")
  private String entidad = null;

  @SerializedName("regimen")
  private String regimen = null;

  @SerializedName("fechaAfiliacion")
  private LocalDate fechaAfiliacion = null;

  @SerializedName("fechaFinalAfiliacion")
  private LocalDate fechaFinalAfiliacion = null;

  @SerializedName("departamento")
  private String departamento = null;

  @SerializedName("ciudad")
  private String ciudad = null;

  @SerializedName("tipoAfiliado")
  private String tipoAfiliado = null;

  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  /**
   * Indica si la fuente falló en la consulta.
   */
  @JsonAdapter(FuenteFalloEnum.Adapter.class)
  public enum FuenteFalloEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    FuenteFalloEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FuenteFalloEnum fromValue(String input) {
      for (FuenteFalloEnum b : FuenteFalloEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FuenteFalloEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FuenteFalloEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public FuenteFalloEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return FuenteFalloEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("fuenteFallo")
  private FuenteFalloEnum fuenteFallo = null;

  public ResponseAntecedentesBDUAVO personaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
    return this;
  }

   /**
   * Get personaVO
   * @return personaVO
  **/
  @Schema(required = true, description = "")
  public PersonaVO getPersonaVO() {
    return personaVO;
  }

  public void setPersonaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
  }

  public ResponseAntecedentesBDUAVO estado(String estado) {
    this.estado = estado;
    return this;
  }

   /**
   * Estado de la afiliación.
   * @return estado
  **/
  @Schema(required = true, description = "Estado de la afiliación.")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public ResponseAntecedentesBDUAVO entidad(String entidad) {
    this.entidad = entidad;
    return this;
  }

   /**
   * Entidad a la que está afiliado.
   * @return entidad
  **/
  @Schema(required = true, description = "Entidad a la que está afiliado.")
  public String getEntidad() {
    return entidad;
  }

  public void setEntidad(String entidad) {
    this.entidad = entidad;
  }

  public ResponseAntecedentesBDUAVO regimen(String regimen) {
    this.regimen = regimen;
    return this;
  }

   /**
   * Régimen de afiliación.
   * @return regimen
  **/
  @Schema(required = true, description = "Régimen de afiliación.")
  public String getRegimen() {
    return regimen;
  }

  public void setRegimen(String regimen) {
    this.regimen = regimen;
  }

  public ResponseAntecedentesBDUAVO fechaAfiliacion(LocalDate fechaAfiliacion) {
    this.fechaAfiliacion = fechaAfiliacion;
    return this;
  }

   /**
   * Fecha de inicio de la afiliación.
   * @return fechaAfiliacion
  **/
  @Schema(required = true, description = "Fecha de inicio de la afiliación.")
  public LocalDate getFechaAfiliacion() {
    return fechaAfiliacion;
  }

  public void setFechaAfiliacion(LocalDate fechaAfiliacion) {
    this.fechaAfiliacion = fechaAfiliacion;
  }

  public ResponseAntecedentesBDUAVO fechaFinalAfiliacion(LocalDate fechaFinalAfiliacion) {
    this.fechaFinalAfiliacion = fechaFinalAfiliacion;
    return this;
  }

   /**
   * Fecha de finalización de la afiliación.
   * @return fechaFinalAfiliacion
  **/
  @Schema(required = true, description = "Fecha de finalización de la afiliación.")
  public LocalDate getFechaFinalAfiliacion() {
    return fechaFinalAfiliacion;
  }

  public void setFechaFinalAfiliacion(LocalDate fechaFinalAfiliacion) {
    this.fechaFinalAfiliacion = fechaFinalAfiliacion;
  }

  public ResponseAntecedentesBDUAVO departamento(String departamento) {
    this.departamento = departamento;
    return this;
  }

   /**
   * Departamento de residencia.
   * @return departamento
  **/
  @Schema(required = true, description = "Departamento de residencia.")
  public String getDepartamento() {
    return departamento;
  }

  public void setDepartamento(String departamento) {
    this.departamento = departamento;
  }

  public ResponseAntecedentesBDUAVO ciudad(String ciudad) {
    this.ciudad = ciudad;
    return this;
  }

   /**
   * Ciudad de residencia.
   * @return ciudad
  **/
  @Schema(required = true, description = "Ciudad de residencia.")
  public String getCiudad() {
    return ciudad;
  }

  public void setCiudad(String ciudad) {
    this.ciudad = ciudad;
  }

  public ResponseAntecedentesBDUAVO tipoAfiliado(String tipoAfiliado) {
    this.tipoAfiliado = tipoAfiliado;
    return this;
  }

   /**
   * Tipo de afiliado.
   * @return tipoAfiliado
  **/
  @Schema(required = true, description = "Tipo de afiliado.")
  public String getTipoAfiliado() {
    return tipoAfiliado;
  }

  public void setTipoAfiliado(String tipoAfiliado) {
    this.tipoAfiliado = tipoAfiliado;
  }

  public ResponseAntecedentesBDUAVO fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Get fechaConsulta
   * @return fechaConsulta
  **/
  @Schema(required = true, description = "")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public ResponseAntecedentesBDUAVO fuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
    return this;
  }

   /**
   * Indica si la fuente falló en la consulta.
   * @return fuenteFallo
  **/
  @Schema(required = true, description = "Indica si la fuente falló en la consulta.")
  public FuenteFalloEnum getFuenteFallo() {
    return fuenteFallo;
  }

  public void setFuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseAntecedentesBDUAVO responseAntecedentesBDUAVO = (ResponseAntecedentesBDUAVO) o;
    return Objects.equals(this.personaVO, responseAntecedentesBDUAVO.personaVO) &&
        Objects.equals(this.estado, responseAntecedentesBDUAVO.estado) &&
        Objects.equals(this.entidad, responseAntecedentesBDUAVO.entidad) &&
        Objects.equals(this.regimen, responseAntecedentesBDUAVO.regimen) &&
        Objects.equals(this.fechaAfiliacion, responseAntecedentesBDUAVO.fechaAfiliacion) &&
        Objects.equals(this.fechaFinalAfiliacion, responseAntecedentesBDUAVO.fechaFinalAfiliacion) &&
        Objects.equals(this.departamento, responseAntecedentesBDUAVO.departamento) &&
        Objects.equals(this.ciudad, responseAntecedentesBDUAVO.ciudad) &&
        Objects.equals(this.tipoAfiliado, responseAntecedentesBDUAVO.tipoAfiliado) &&
        Objects.equals(this.fechaConsulta, responseAntecedentesBDUAVO.fechaConsulta) &&
        Objects.equals(this.fuenteFallo, responseAntecedentesBDUAVO.fuenteFallo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personaVO, estado, entidad, regimen, fechaAfiliacion, fechaFinalAfiliacion, departamento, ciudad, tipoAfiliado, fechaConsulta, fuenteFallo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseAntecedentesBDUAVO {\n");
    
    sb.append("    personaVO: ").append(toIndentedString(personaVO)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    entidad: ").append(toIndentedString(entidad)).append("\n");
    sb.append("    regimen: ").append(toIndentedString(regimen)).append("\n");
    sb.append("    fechaAfiliacion: ").append(toIndentedString(fechaAfiliacion)).append("\n");
    sb.append("    fechaFinalAfiliacion: ").append(toIndentedString(fechaFinalAfiliacion)).append("\n");
    sb.append("    departamento: ").append(toIndentedString(departamento)).append("\n");
    sb.append("    ciudad: ").append(toIndentedString(ciudad)).append("\n");
    sb.append("    tipoAfiliado: ").append(toIndentedString(tipoAfiliado)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    fuenteFallo: ").append(toIndentedString(fuenteFallo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
