/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollectionTblPersonaGrpPersona;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollection
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollection {
  @SerializedName("tblPersonaGrpPersona")
  private List<ResponseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollectionTblPersonaGrpPersona> tblPersonaGrpPersona = null;

  public ResponseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollection tblPersonaGrpPersona(List<ResponseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollectionTblPersonaGrpPersona> tblPersonaGrpPersona) {
    this.tblPersonaGrpPersona = tblPersonaGrpPersona;
    return this;
  }

  public ResponseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollection addTblPersonaGrpPersonaItem(ResponseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollectionTblPersonaGrpPersona tblPersonaGrpPersonaItem) {
    if (this.tblPersonaGrpPersona == null) {
      this.tblPersonaGrpPersona = new ArrayList<ResponseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollectionTblPersonaGrpPersona>();
    }
    this.tblPersonaGrpPersona.add(tblPersonaGrpPersonaItem);
    return this;
  }

   /**
   * Colección de personas (detalles básicos).
   * @return tblPersonaGrpPersona
  **/
  @Schema(description = "Colección de personas (detalles básicos).")
  public List<ResponseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollectionTblPersonaGrpPersona> getTblPersonaGrpPersona() {
    return tblPersonaGrpPersona;
  }

  public void setTblPersonaGrpPersona(List<ResponseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollectionTblPersonaGrpPersona> tblPersonaGrpPersona) {
    this.tblPersonaGrpPersona = tblPersonaGrpPersona;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollection responseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollection = (ResponseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollection) o;
    return Objects.equals(this.tblPersonaGrpPersona, responseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollection.tblPersonaGrpPersona);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tblPersonaGrpPersona);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuafVOReportVOLstPensionadosTblPersonaTblPersonaGrpPersonaCollection {\n");
    
    sb.append("    tblPersonaGrpPersona: ").append(toIndentedString(tblPersonaGrpPersona)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
