/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PersonaVO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.LocalDate;
/**
 * Colombia -  65238701 - Consulta de matrícula ante el Consejo Profesional Nacional de Tecnólogos en Electricidad, Electromecánica, Electrónica y afines.
 */
@Schema(description = "Colombia -  65238701 - Consulta de matrícula ante el Consejo Profesional Nacional de Tecnólogos en Electricidad, Electromecánica, Electrónica y afines.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseConaltelVO {
  @SerializedName("personaVO")
  private PersonaVO personaVO = null;

  @SerializedName("matricula")
  private String matricula = null;

  @SerializedName("estado")
  private String estado = null;

  @SerializedName("documentoSolicitado")
  private String documentoSolicitado = null;

  @SerializedName("fechaSolicitud")
  private String fechaSolicitud = null;

  @SerializedName("profesion")
  private String profesion = null;

  @SerializedName("institucion")
  private String institucion = null;

  @SerializedName("ciudad")
  private String ciudad = null;

  @SerializedName("radicado")
  private String radicado = null;

  @SerializedName("fechaRadicacion")
  private LocalDate fechaRadicacion = null;

  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  /**
   * Indica si la fuente falló en la consulta.
   */
  @JsonAdapter(FuenteFalloEnum.Adapter.class)
  public enum FuenteFalloEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    FuenteFalloEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FuenteFalloEnum fromValue(String input) {
      for (FuenteFalloEnum b : FuenteFalloEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FuenteFalloEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FuenteFalloEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public FuenteFalloEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return FuenteFalloEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("fuenteFallo")
  private FuenteFalloEnum fuenteFallo = null;

  public ResponseConaltelVO personaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
    return this;
  }

   /**
   * Get personaVO
   * @return personaVO
  **/
  @Schema(required = true, description = "")
  public PersonaVO getPersonaVO() {
    return personaVO;
  }

  public void setPersonaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
  }

  public ResponseConaltelVO matricula(String matricula) {
    this.matricula = matricula;
    return this;
  }

   /**
   * Número de matrícula en CONALTEL.
   * @return matricula
  **/
  @Schema(required = true, description = "Número de matrícula en CONALTEL.")
  public String getMatricula() {
    return matricula;
  }

  public void setMatricula(String matricula) {
    this.matricula = matricula;
  }

  public ResponseConaltelVO estado(String estado) {
    this.estado = estado;
    return this;
  }

   /**
   * Estado de la matrícula
   * @return estado
  **/
  @Schema(example = "entregada, en trámite", required = true, description = "Estado de la matrícula")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public ResponseConaltelVO documentoSolicitado(String documentoSolicitado) {
    this.documentoSolicitado = documentoSolicitado;
    return this;
  }

   /**
   * Tipo de documento solicitado
   * @return documentoSolicitado
  **/
  @Schema(example = "matrícula", required = true, description = "Tipo de documento solicitado")
  public String getDocumentoSolicitado() {
    return documentoSolicitado;
  }

  public void setDocumentoSolicitado(String documentoSolicitado) {
    this.documentoSolicitado = documentoSolicitado;
  }

  public ResponseConaltelVO fechaSolicitud(String fechaSolicitud) {
    this.fechaSolicitud = fechaSolicitud;
    return this;
  }

   /**
   * Get fechaSolicitud
   * @return fechaSolicitud
  **/
  @Schema(required = true, description = "")
  public String getFechaSolicitud() {
    return fechaSolicitud;
  }

  public void setFechaSolicitud(String fechaSolicitud) {
    this.fechaSolicitud = fechaSolicitud;
  }

  public ResponseConaltelVO profesion(String profesion) {
    this.profesion = profesion;
    return this;
  }

   /**
   * Profesión registrada.
   * @return profesion
  **/
  @Schema(required = true, description = "Profesión registrada.")
  public String getProfesion() {
    return profesion;
  }

  public void setProfesion(String profesion) {
    this.profesion = profesion;
  }

  public ResponseConaltelVO institucion(String institucion) {
    this.institucion = institucion;
    return this;
  }

   /**
   * Institución donde se obtuvo la profesión.
   * @return institucion
  **/
  @Schema(required = true, description = "Institución donde se obtuvo la profesión.")
  public String getInstitucion() {
    return institucion;
  }

  public void setInstitucion(String institucion) {
    this.institucion = institucion;
  }

  public ResponseConaltelVO ciudad(String ciudad) {
    this.ciudad = ciudad;
    return this;
  }

   /**
   * Ciudad de la institución o donde se registró la matrícula.
   * @return ciudad
  **/
  @Schema(required = true, description = "Ciudad de la institución o donde se registró la matrícula.")
  public String getCiudad() {
    return ciudad;
  }

  public void setCiudad(String ciudad) {
    this.ciudad = ciudad;
  }

  public ResponseConaltelVO radicado(String radicado) {
    this.radicado = radicado;
    return this;
  }

   /**
   * Número de radicado.
   * @return radicado
  **/
  @Schema(required = true, description = "Número de radicado.")
  public String getRadicado() {
    return radicado;
  }

  public void setRadicado(String radicado) {
    this.radicado = radicado;
  }

  public ResponseConaltelVO fechaRadicacion(LocalDate fechaRadicacion) {
    this.fechaRadicacion = fechaRadicacion;
    return this;
  }

   /**
   * Fecha del radicado.
   * @return fechaRadicacion
  **/
  @Schema(required = true, description = "Fecha del radicado.")
  public LocalDate getFechaRadicacion() {
    return fechaRadicacion;
  }

  public void setFechaRadicacion(LocalDate fechaRadicacion) {
    this.fechaRadicacion = fechaRadicacion;
  }

  public ResponseConaltelVO fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Get fechaConsulta
   * @return fechaConsulta
  **/
  @Schema(required = true, description = "")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public ResponseConaltelVO fuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
    return this;
  }

   /**
   * Indica si la fuente falló en la consulta.
   * @return fuenteFallo
  **/
  @Schema(required = true, description = "Indica si la fuente falló en la consulta.")
  public FuenteFalloEnum getFuenteFallo() {
    return fuenteFallo;
  }

  public void setFuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseConaltelVO responseConaltelVO = (ResponseConaltelVO) o;
    return Objects.equals(this.personaVO, responseConaltelVO.personaVO) &&
        Objects.equals(this.matricula, responseConaltelVO.matricula) &&
        Objects.equals(this.estado, responseConaltelVO.estado) &&
        Objects.equals(this.documentoSolicitado, responseConaltelVO.documentoSolicitado) &&
        Objects.equals(this.fechaSolicitud, responseConaltelVO.fechaSolicitud) &&
        Objects.equals(this.profesion, responseConaltelVO.profesion) &&
        Objects.equals(this.institucion, responseConaltelVO.institucion) &&
        Objects.equals(this.ciudad, responseConaltelVO.ciudad) &&
        Objects.equals(this.radicado, responseConaltelVO.radicado) &&
        Objects.equals(this.fechaRadicacion, responseConaltelVO.fechaRadicacion) &&
        Objects.equals(this.fechaConsulta, responseConaltelVO.fechaConsulta) &&
        Objects.equals(this.fuenteFallo, responseConaltelVO.fuenteFallo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personaVO, matricula, estado, documentoSolicitado, fechaSolicitud, profesion, institucion, ciudad, radicado, fechaRadicacion, fechaConsulta, fuenteFallo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseConaltelVO {\n");
    
    sb.append("    personaVO: ").append(toIndentedString(personaVO)).append("\n");
    sb.append("    matricula: ").append(toIndentedString(matricula)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    documentoSolicitado: ").append(toIndentedString(documentoSolicitado)).append("\n");
    sb.append("    fechaSolicitud: ").append(toIndentedString(fechaSolicitud)).append("\n");
    sb.append("    profesion: ").append(toIndentedString(profesion)).append("\n");
    sb.append("    institucion: ").append(toIndentedString(institucion)).append("\n");
    sb.append("    ciudad: ").append(toIndentedString(ciudad)).append("\n");
    sb.append("    radicado: ").append(toIndentedString(radicado)).append("\n");
    sb.append("    fechaRadicacion: ").append(toIndentedString(fechaRadicacion)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    fuenteFallo: ").append(toIndentedString(fuenteFallo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
