/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseProcuraduriaVOListInstancias1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseProcuraduriaVOListInstancias1 {
  @SerializedName("nombre")
  private String nombre = null;

  @SerializedName("autoridad")
  private String autoridad = null;

  @SerializedName("fechaProvidencia")
  private String fechaProvidencia = null;

  @SerializedName("fechaEfectoJuridico")
  private String fechaEfectoJuridico = null;

  public ResponseProcuraduriaVOListInstancias1 nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

   /**
   * Nombre de la instancia
   * @return nombre
  **/
  @Schema(example = "PRIMERA, SEGUNDA", required = true, description = "Nombre de la instancia")
  public String getNombre() {
    return nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public ResponseProcuraduriaVOListInstancias1 autoridad(String autoridad) {
    this.autoridad = autoridad;
    return this;
  }

   /**
   * Autoridad disciplinaria responsable de la instancia.
   * @return autoridad
  **/
  @Schema(example = "CONSEJO PROFESIONAL DE INGENIEROS COPNIA SECCIONAL CUNDINAMARCA", required = true, description = "Autoridad disciplinaria responsable de la instancia.")
  public String getAutoridad() {
    return autoridad;
  }

  public void setAutoridad(String autoridad) {
    this.autoridad = autoridad;
  }

  public ResponseProcuraduriaVOListInstancias1 fechaProvidencia(String fechaProvidencia) {
    this.fechaProvidencia = fechaProvidencia;
    return this;
  }

   /**
   * Get fechaProvidencia
   * @return fechaProvidencia
  **/
  @Schema(required = true, description = "")
  public String getFechaProvidencia() {
    return fechaProvidencia;
  }

  public void setFechaProvidencia(String fechaProvidencia) {
    this.fechaProvidencia = fechaProvidencia;
  }

  public ResponseProcuraduriaVOListInstancias1 fechaEfectoJuridico(String fechaEfectoJuridico) {
    this.fechaEfectoJuridico = fechaEfectoJuridico;
    return this;
  }

   /**
   * Get fechaEfectoJuridico
   * @return fechaEfectoJuridico
  **/
  @Schema(required = true, description = "")
  public String getFechaEfectoJuridico() {
    return fechaEfectoJuridico;
  }

  public void setFechaEfectoJuridico(String fechaEfectoJuridico) {
    this.fechaEfectoJuridico = fechaEfectoJuridico;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseProcuraduriaVOListInstancias1 responseProcuraduriaVOListInstancias1 = (ResponseProcuraduriaVOListInstancias1) o;
    return Objects.equals(this.nombre, responseProcuraduriaVOListInstancias1.nombre) &&
        Objects.equals(this.autoridad, responseProcuraduriaVOListInstancias1.autoridad) &&
        Objects.equals(this.fechaProvidencia, responseProcuraduriaVOListInstancias1.fechaProvidencia) &&
        Objects.equals(this.fechaEfectoJuridico, responseProcuraduriaVOListInstancias1.fechaEfectoJuridico);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nombre, autoridad, fechaProvidencia, fechaEfectoJuridico);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseProcuraduriaVOListInstancias1 {\n");
    
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    autoridad: ").append(toIndentedString(autoridad)).append("\n");
    sb.append("    fechaProvidencia: ").append(toIndentedString(fechaProvidencia)).append("\n");
    sb.append("    fechaEfectoJuridico: ").append(toIndentedString(fechaEfectoJuridico)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
