/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PersonaVO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Colombia -  30068746 - Consulta del Permiso por Protección Temporal (PPT).
 */
@Schema(description = "Colombia -  30068746 - Consulta del Permiso por Protección Temporal (PPT).")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseMigracionPptVO {
  @SerializedName("PersonaVO")
  private PersonaVO personaVO = null;

  @SerializedName("numeroTelefonico")
  private String numeroTelefonico = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("tipoDocumento")
  private String tipoDocumento = null;

  @SerializedName("numeroIdentidadExtranjera")
  private String numeroIdentidadExtranjera = null;

  @SerializedName("estadoPpt")
  private String estadoPpt = null;

  @SerializedName("mensajeEstado")
  private String mensajeEstado = null;

  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  /**
   * Indica si la fuente falló en la consulta.
   */
  @JsonAdapter(FuenteFalloEnum.Adapter.class)
  public enum FuenteFalloEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    FuenteFalloEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FuenteFalloEnum fromValue(String input) {
      for (FuenteFalloEnum b : FuenteFalloEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FuenteFalloEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FuenteFalloEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public FuenteFalloEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return FuenteFalloEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("fuenteFallo")
  private FuenteFalloEnum fuenteFallo = null;

  public ResponseMigracionPptVO personaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
    return this;
  }

   /**
   * Get personaVO
   * @return personaVO
  **/
  @Schema(required = true, description = "")
  public PersonaVO getPersonaVO() {
    return personaVO;
  }

  public void setPersonaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
  }

  public ResponseMigracionPptVO numeroTelefonico(String numeroTelefonico) {
    this.numeroTelefonico = numeroTelefonico;
    return this;
  }

   /**
   * Número(s) telefónico(s) de contacto.
   * @return numeroTelefonico
  **/
  @Schema(example = "6346976 - 3106355564", required = true, description = "Número(s) telefónico(s) de contacto.")
  public String getNumeroTelefonico() {
    return numeroTelefonico;
  }

  public void setNumeroTelefonico(String numeroTelefonico) {
    this.numeroTelefonico = numeroTelefonico;
  }

  public ResponseMigracionPptVO email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Correo electrónico de contacto.
   * @return email
  **/
  @Schema(example = "MARIACAMILA90@GMAIL.COM", required = true, description = "Correo electrónico de contacto.")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public ResponseMigracionPptVO tipoDocumento(String tipoDocumento) {
    this.tipoDocumento = tipoDocumento;
    return this;
  }

   /**
   * Tipo de documento de identidad del extranjero.
   * @return tipoDocumento
  **/
  @Schema(example = "PASAPORTE", required = true, description = "Tipo de documento de identidad del extranjero.")
  public String getTipoDocumento() {
    return tipoDocumento;
  }

  public void setTipoDocumento(String tipoDocumento) {
    this.tipoDocumento = tipoDocumento;
  }

  public ResponseMigracionPptVO numeroIdentidadExtranjera(String numeroIdentidadExtranjera) {
    this.numeroIdentidadExtranjera = numeroIdentidadExtranjera;
    return this;
  }

   /**
   * Número de identidad extranjera asociado al PPT.
   * @return numeroIdentidadExtranjera
  **/
  @Schema(example = "ND1098XX", required = true, description = "Número de identidad extranjera asociado al PPT.")
  public String getNumeroIdentidadExtranjera() {
    return numeroIdentidadExtranjera;
  }

  public void setNumeroIdentidadExtranjera(String numeroIdentidadExtranjera) {
    this.numeroIdentidadExtranjera = numeroIdentidadExtranjera;
  }

  public ResponseMigracionPptVO estadoPpt(String estadoPpt) {
    this.estadoPpt = estadoPpt;
    return this;
  }

   /**
   * Estado actual del Permiso por Protección Temporal (PPT).
   * @return estadoPpt
  **/
  @Schema(example = "IMPRESO", required = true, description = "Estado actual del Permiso por Protección Temporal (PPT).")
  public String getEstadoPpt() {
    return estadoPpt;
  }

  public void setEstadoPpt(String estadoPpt) {
    this.estadoPpt = estadoPpt;
  }

  public ResponseMigracionPptVO mensajeEstado(String mensajeEstado) {
    this.mensajeEstado = mensajeEstado;
    return this;
  }

   /**
   * Mensaje descriptivo del estado del PPT (puede estar vacío).
   * @return mensajeEstado
  **/
  @Schema(required = true, description = "Mensaje descriptivo del estado del PPT (puede estar vacío).")
  public String getMensajeEstado() {
    return mensajeEstado;
  }

  public void setMensajeEstado(String mensajeEstado) {
    this.mensajeEstado = mensajeEstado;
  }

  public ResponseMigracionPptVO fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Get fechaConsulta
   * @return fechaConsulta
  **/
  @Schema(required = true, description = "")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public ResponseMigracionPptVO fuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
    return this;
  }

   /**
   * Indica si la fuente falló en la consulta.
   * @return fuenteFallo
  **/
  @Schema(example = "NO", required = true, description = "Indica si la fuente falló en la consulta.")
  public FuenteFalloEnum getFuenteFallo() {
    return fuenteFallo;
  }

  public void setFuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseMigracionPptVO responseMigracionPptVO = (ResponseMigracionPptVO) o;
    return Objects.equals(this.personaVO, responseMigracionPptVO.personaVO) &&
        Objects.equals(this.numeroTelefonico, responseMigracionPptVO.numeroTelefonico) &&
        Objects.equals(this.email, responseMigracionPptVO.email) &&
        Objects.equals(this.tipoDocumento, responseMigracionPptVO.tipoDocumento) &&
        Objects.equals(this.numeroIdentidadExtranjera, responseMigracionPptVO.numeroIdentidadExtranjera) &&
        Objects.equals(this.estadoPpt, responseMigracionPptVO.estadoPpt) &&
        Objects.equals(this.mensajeEstado, responseMigracionPptVO.mensajeEstado) &&
        Objects.equals(this.fechaConsulta, responseMigracionPptVO.fechaConsulta) &&
        Objects.equals(this.fuenteFallo, responseMigracionPptVO.fuenteFallo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personaVO, numeroTelefonico, email, tipoDocumento, numeroIdentidadExtranjera, estadoPpt, mensajeEstado, fechaConsulta, fuenteFallo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseMigracionPptVO {\n");
    
    sb.append("    personaVO: ").append(toIndentedString(personaVO)).append("\n");
    sb.append("    numeroTelefonico: ").append(toIndentedString(numeroTelefonico)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    tipoDocumento: ").append(toIndentedString(tipoDocumento)).append("\n");
    sb.append("    numeroIdentidadExtranjera: ").append(toIndentedString(numeroIdentidadExtranjera)).append("\n");
    sb.append("    estadoPpt: ").append(toIndentedString(estadoPpt)).append("\n");
    sb.append("    mensajeEstado: ").append(toIndentedString(mensajeEstado)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    fuenteFallo: ").append(toIndentedString(fuenteFallo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
