/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseRuntPlacaVOListSolicitudes
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuntPlacaVOListSolicitudes {
  @SerializedName("nroSolicitud")
  private String nroSolicitud = null;

  @SerializedName("fechaSolicitud")
  private String fechaSolicitud = null;

  @SerializedName("estado")
  private String estado = null;

  @SerializedName("tramites")
  private String tramites = null;

  @SerializedName("entidad")
  private String entidad = null;

  public ResponseRuntPlacaVOListSolicitudes nroSolicitud(String nroSolicitud) {
    this.nroSolicitud = nroSolicitud;
    return this;
  }

   /**
   * Número de solicitud.
   * @return nroSolicitud
  **/
  @Schema(example = "139880168", required = true, description = "Número de solicitud.")
  public String getNroSolicitud() {
    return nroSolicitud;
  }

  public void setNroSolicitud(String nroSolicitud) {
    this.nroSolicitud = nroSolicitud;
  }

  public ResponseRuntPlacaVOListSolicitudes fechaSolicitud(String fechaSolicitud) {
    this.fechaSolicitud = fechaSolicitud;
    return this;
  }

   /**
   * Get fechaSolicitud
   * @return fechaSolicitud
  **/
  @Schema(required = true, description = "")
  public String getFechaSolicitud() {
    return fechaSolicitud;
  }

  public void setFechaSolicitud(String fechaSolicitud) {
    this.fechaSolicitud = fechaSolicitud;
  }

  public ResponseRuntPlacaVOListSolicitudes estado(String estado) {
    this.estado = estado;
    return this;
  }

   /**
   * Estado de la solicitud
   * @return estado
  **/
  @Schema(example = "AUTORIZADA, APROBADA", required = true, description = "Estado de la solicitud")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public ResponseRuntPlacaVOListSolicitudes tramites(String tramites) {
    this.tramites = tramites;
    return this;
  }

   /**
   * Trámites asociados a la solicitud.
   * @return tramites
  **/
  @Schema(example = "Tramite revision tecnico mecanica,", required = true, description = "Trámites asociados a la solicitud.")
  public String getTramites() {
    return tramites;
  }

  public void setTramites(String tramites) {
    this.tramites = tramites;
  }

  public ResponseRuntPlacaVOListSolicitudes entidad(String entidad) {
    this.entidad = entidad;
    return this;
  }

   /**
   * Entidad asociada a la solicitud.
   * @return entidad
  **/
  @Schema(example = "DIAGNOSTICENTROS DE COLOMBIA S.A.S.", required = true, description = "Entidad asociada a la solicitud.")
  public String getEntidad() {
    return entidad;
  }

  public void setEntidad(String entidad) {
    this.entidad = entidad;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuntPlacaVOListSolicitudes responseRuntPlacaVOListSolicitudes = (ResponseRuntPlacaVOListSolicitudes) o;
    return Objects.equals(this.nroSolicitud, responseRuntPlacaVOListSolicitudes.nroSolicitud) &&
        Objects.equals(this.fechaSolicitud, responseRuntPlacaVOListSolicitudes.fechaSolicitud) &&
        Objects.equals(this.estado, responseRuntPlacaVOListSolicitudes.estado) &&
        Objects.equals(this.tramites, responseRuntPlacaVOListSolicitudes.tramites) &&
        Objects.equals(this.entidad, responseRuntPlacaVOListSolicitudes.entidad);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nroSolicitud, fechaSolicitud, estado, tramites, entidad);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuntPlacaVOListSolicitudes {\n");
    
    sb.append("    nroSolicitud: ").append(toIndentedString(nroSolicitud)).append("\n");
    sb.append("    fechaSolicitud: ").append(toIndentedString(fechaSolicitud)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    tramites: ").append(toIndentedString(tramites)).append("\n");
    sb.append("    entidad: ").append(toIndentedString(entidad)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
