/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollectionTblCompensacionFamiliarGrpCompensacionFamiliar;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollection
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollection {
  @SerializedName("tblCompensacionFamiliarGrpCompensacionFamiliar")
  private List<ResponseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollectionTblCompensacionFamiliarGrpCompensacionFamiliar> tblCompensacionFamiliarGrpCompensacionFamiliar = null;

  public ResponseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollection tblCompensacionFamiliarGrpCompensacionFamiliar(List<ResponseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollectionTblCompensacionFamiliarGrpCompensacionFamiliar> tblCompensacionFamiliarGrpCompensacionFamiliar) {
    this.tblCompensacionFamiliarGrpCompensacionFamiliar = tblCompensacionFamiliarGrpCompensacionFamiliar;
    return this;
  }

  public ResponseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollection addTblCompensacionFamiliarGrpCompensacionFamiliarItem(ResponseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollectionTblCompensacionFamiliarGrpCompensacionFamiliar tblCompensacionFamiliarGrpCompensacionFamiliarItem) {
    if (this.tblCompensacionFamiliarGrpCompensacionFamiliar == null) {
      this.tblCompensacionFamiliarGrpCompensacionFamiliar = new ArrayList<ResponseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollectionTblCompensacionFamiliarGrpCompensacionFamiliar>();
    }
    this.tblCompensacionFamiliarGrpCompensacionFamiliar.add(tblCompensacionFamiliarGrpCompensacionFamiliarItem);
    return this;
  }

   /**
   * Detalles de afiliación a Caja de Compensación Familiar.
   * @return tblCompensacionFamiliarGrpCompensacionFamiliar
  **/
  @Schema(description = "Detalles de afiliación a Caja de Compensación Familiar.")
  public List<ResponseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollectionTblCompensacionFamiliarGrpCompensacionFamiliar> getTblCompensacionFamiliarGrpCompensacionFamiliar() {
    return tblCompensacionFamiliarGrpCompensacionFamiliar;
  }

  public void setTblCompensacionFamiliarGrpCompensacionFamiliar(List<ResponseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollectionTblCompensacionFamiliarGrpCompensacionFamiliar> tblCompensacionFamiliarGrpCompensacionFamiliar) {
    this.tblCompensacionFamiliarGrpCompensacionFamiliar = tblCompensacionFamiliarGrpCompensacionFamiliar;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollection responseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollection = (ResponseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollection) o;
    return Objects.equals(this.tblCompensacionFamiliarGrpCompensacionFamiliar, responseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollection.tblCompensacionFamiliarGrpCompensacionFamiliar);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tblCompensacionFamiliarGrpCompensacionFamiliar);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuafVOReportVOLstPensionadosTblCompensacionFamiliarTblCompensacionFamiliarGrpCompensacionFamiliarCollection {\n");
    
    sb.append("    tblCompensacionFamiliarGrpCompensacionFamiliar: ").append(toIndentedString(tblCompensacionFamiliarGrpCompensacionFamiliar)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
