/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseRuesCamaraUnificadoVORmList;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Colombia -  48617941 - Rues unificado
 */
@Schema(description = "Colombia -  48617941 - Rues unificado")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuesCamaraUnificadoVO {
  @SerializedName("mensaje")
  private String mensaje = null;

  @SerializedName("rmList")
  private List<ResponseRuesCamaraUnificadoVORmList> rmList = new ArrayList<ResponseRuesCamaraUnificadoVORmList>();

  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  /**
   * Indica si la fuente falló en la consulta.
   */
  @JsonAdapter(FuenteFalloEnum.Adapter.class)
  public enum FuenteFalloEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    FuenteFalloEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FuenteFalloEnum fromValue(String input) {
      for (FuenteFalloEnum b : FuenteFalloEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FuenteFalloEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FuenteFalloEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public FuenteFalloEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return FuenteFalloEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("fuenteFallo")
  private FuenteFalloEnum fuenteFallo = null;

  public ResponseRuesCamaraUnificadoVO mensaje(String mensaje) {
    this.mensaje = mensaje;
    return this;
  }

   /**
   * Mensaje general de la consulta (puede estar vacío).
   * @return mensaje
  **/
  @Schema(required = true, description = "Mensaje general de la consulta (puede estar vacío).")
  public String getMensaje() {
    return mensaje;
  }

  public void setMensaje(String mensaje) {
    this.mensaje = mensaje;
  }

  public ResponseRuesCamaraUnificadoVO rmList(List<ResponseRuesCamaraUnificadoVORmList> rmList) {
    this.rmList = rmList;
    return this;
  }

  public ResponseRuesCamaraUnificadoVO addRmListItem(ResponseRuesCamaraUnificadoVORmList rmListItem) {
    this.rmList.add(rmListItem);
    return this;
  }

   /**
   * Listado de registros mercantiles encontrados (puede haber uno o varios).
   * @return rmList
  **/
  @Schema(required = true, description = "Listado de registros mercantiles encontrados (puede haber uno o varios).")
  public List<ResponseRuesCamaraUnificadoVORmList> getRmList() {
    return rmList;
  }

  public void setRmList(List<ResponseRuesCamaraUnificadoVORmList> rmList) {
    this.rmList = rmList;
  }

  public ResponseRuesCamaraUnificadoVO fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Get fechaConsulta
   * @return fechaConsulta
  **/
  @Schema(required = true, description = "")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public ResponseRuesCamaraUnificadoVO fuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
    return this;
  }

   /**
   * Indica si la fuente falló en la consulta.
   * @return fuenteFallo
  **/
  @Schema(example = "NO", required = true, description = "Indica si la fuente falló en la consulta.")
  public FuenteFalloEnum getFuenteFallo() {
    return fuenteFallo;
  }

  public void setFuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuesCamaraUnificadoVO responseRuesCamaraUnificadoVO = (ResponseRuesCamaraUnificadoVO) o;
    return Objects.equals(this.mensaje, responseRuesCamaraUnificadoVO.mensaje) &&
        Objects.equals(this.rmList, responseRuesCamaraUnificadoVO.rmList) &&
        Objects.equals(this.fechaConsulta, responseRuesCamaraUnificadoVO.fechaConsulta) &&
        Objects.equals(this.fuenteFallo, responseRuesCamaraUnificadoVO.fuenteFallo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mensaje, rmList, fechaConsulta, fuenteFallo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuesCamaraUnificadoVO {\n");
    
    sb.append("    mensaje: ").append(toIndentedString(mensaje)).append("\n");
    sb.append("    rmList: ").append(toIndentedString(rmList)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    fuenteFallo: ").append(toIndentedString(fuenteFallo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
