/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseRuesCamaraUnificadoVODetalleCamaraListActividadEconomica;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;
/**
 * Detalles específicos del registro en la Cámara de Comercio.
 */
@Schema(description = "Detalles específicos del registro en la Cámara de Comercio.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuesCamaraUnificadoVODetalleCamara {
  @SerializedName("razonSocial")
  private String razonSocial = null;

  @SerializedName("sigla")
  private String sigla = null;

  @SerializedName("camaraComercio")
  private String camaraComercio = null;

  @SerializedName("numeroMatricula")
  private String numeroMatricula = null;

  @SerializedName("identificacion")
  private String identificacion = null;

  @SerializedName("ultimoRenovado")
  private String ultimoRenovado = null;

  @SerializedName("fechaMatricula")
  private LocalDate fechaMatricula = null;

  @SerializedName("fechaCancelacion")
  private String fechaCancelacion = null;

  @SerializedName("fechaVigencia")
  private String fechaVigencia = null;

  @SerializedName("fechaRenovacion")
  private String fechaRenovacion = null;

  @SerializedName("motivoCancelacion")
  private String motivoCancelacion = null;

  @SerializedName("estadoMatricula")
  private String estadoMatricula = null;

  @SerializedName("tipoSociedad")
  private String tipoSociedad = null;

  @SerializedName("tipoOrganizacion")
  private String tipoOrganizacion = null;

  @SerializedName("categoriaMatricula")
  private String categoriaMatricula = null;

  @SerializedName("fechaUltimaAct")
  private String fechaUltimaAct = null;

  @SerializedName("empleados")
  private String empleados = null;

  /**
   * Indica si la empresa está afiliada a la Cámara de Comercio.
   */
  @JsonAdapter(AfiliadoEnum.Adapter.class)
  public enum AfiliadoEnum {
    @SerializedName("S")
    S("S"),
    @SerializedName("N")
    N("N");

    private String value;

    AfiliadoEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static AfiliadoEnum fromValue(String input) {
      for (AfiliadoEnum b : AfiliadoEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<AfiliadoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AfiliadoEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public AfiliadoEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return AfiliadoEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("afiliado")
  private AfiliadoEnum afiliado = null;

  @SerializedName("beneficiarioLey1780")
  private String beneficiarioLey1780 = null;

  @SerializedName("listActividadEconomica")
  private List<ResponseRuesCamaraUnificadoVODetalleCamaraListActividadEconomica> listActividadEconomica = new ArrayList<ResponseRuesCamaraUnificadoVODetalleCamaraListActividadEconomica>();

  public ResponseRuesCamaraUnificadoVODetalleCamara razonSocial(String razonSocial) {
    this.razonSocial = razonSocial;
    return this;
  }

   /**
   * Razón social o denominación de la empresa.
   * @return razonSocial
  **/
  @Schema(example = "FUNERARIA PREVICESAR S.A.S.", required = true, description = "Razón social o denominación de la empresa.")
  public String getRazonSocial() {
    return razonSocial;
  }

  public void setRazonSocial(String razonSocial) {
    this.razonSocial = razonSocial;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara sigla(String sigla) {
    this.sigla = sigla;
    return this;
  }

   /**
   * Sigla de la empresa, si aplica.
   * @return sigla
  **/
  @Schema(required = true, description = "Sigla de la empresa, si aplica.")
  public String getSigla() {
    return sigla;
  }

  public void setSigla(String sigla) {
    this.sigla = sigla;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara camaraComercio(String camaraComercio) {
    this.camaraComercio = camaraComercio;
    return this;
  }

   /**
   * Nombre de la Cámara de Comercio.
   * @return camaraComercio
  **/
  @Schema(example = "AGUACHICA", required = true, description = "Nombre de la Cámara de Comercio.")
  public String getCamaraComercio() {
    return camaraComercio;
  }

  public void setCamaraComercio(String camaraComercio) {
    this.camaraComercio = camaraComercio;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara numeroMatricula(String numeroMatricula) {
    this.numeroMatricula = numeroMatricula;
    return this;
  }

   /**
   * Número de matrícula mercantil.
   * @return numeroMatricula
  **/
  @Schema(example = "35587", required = true, description = "Número de matrícula mercantil.")
  public String getNumeroMatricula() {
    return numeroMatricula;
  }

  public void setNumeroMatricula(String numeroMatricula) {
    this.numeroMatricula = numeroMatricula;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara identificacion(String identificacion) {
    this.identificacion = identificacion;
    return this;
  }

   /**
   * Número de identificación (NIT con dígito de verificación).
   * @return identificacion
  **/
  @Schema(example = "NIT 900671537 - 6", required = true, description = "Número de identificación (NIT con dígito de verificación).")
  public String getIdentificacion() {
    return identificacion;
  }

  public void setIdentificacion(String identificacion) {
    this.identificacion = identificacion;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara ultimoRenovado(String ultimoRenovado) {
    this.ultimoRenovado = ultimoRenovado;
    return this;
  }

   /**
   * Año de la última renovación.
   * @return ultimoRenovado
  **/
  @Schema(example = "2022", required = true, description = "Año de la última renovación.")
  public String getUltimoRenovado() {
    return ultimoRenovado;
  }

  public void setUltimoRenovado(String ultimoRenovado) {
    this.ultimoRenovado = ultimoRenovado;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara fechaMatricula(LocalDate fechaMatricula) {
    this.fechaMatricula = fechaMatricula;
    return this;
  }

   /**
   * Fecha de matrícula inicial de la empresa.
   * @return fechaMatricula
  **/
  @Schema(example = "Fri Nov 01 00:00:00 GMT 2013", required = true, description = "Fecha de matrícula inicial de la empresa.")
  public LocalDate getFechaMatricula() {
    return fechaMatricula;
  }

  public void setFechaMatricula(LocalDate fechaMatricula) {
    this.fechaMatricula = fechaMatricula;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara fechaCancelacion(String fechaCancelacion) {
    this.fechaCancelacion = fechaCancelacion;
    return this;
  }

   /**
   * Get fechaCancelacion
   * @return fechaCancelacion
  **/
  @Schema(required = true, description = "")
  public String getFechaCancelacion() {
    return fechaCancelacion;
  }

  public void setFechaCancelacion(String fechaCancelacion) {
    this.fechaCancelacion = fechaCancelacion;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara fechaVigencia(String fechaVigencia) {
    this.fechaVigencia = fechaVigencia;
    return this;
  }

   /**
   * Fecha de vigencia del registro (puede ser \&quot;Indefinida\&quot;).
   * @return fechaVigencia
  **/
  @Schema(example = "Indefinida", required = true, description = "Fecha de vigencia del registro (puede ser \"Indefinida\").")
  public String getFechaVigencia() {
    return fechaVigencia;
  }

  public void setFechaVigencia(String fechaVigencia) {
    this.fechaVigencia = fechaVigencia;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara fechaRenovacion(String fechaRenovacion) {
    this.fechaRenovacion = fechaRenovacion;
    return this;
  }

   /**
   * Get fechaRenovacion
   * @return fechaRenovacion
  **/
  @Schema(required = true, description = "")
  public String getFechaRenovacion() {
    return fechaRenovacion;
  }

  public void setFechaRenovacion(String fechaRenovacion) {
    this.fechaRenovacion = fechaRenovacion;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara motivoCancelacion(String motivoCancelacion) {
    this.motivoCancelacion = motivoCancelacion;
    return this;
  }

   /**
   * Motivo de la cancelación del registro, si aplica.
   * @return motivoCancelacion
  **/
  @Schema(example = "NORMAL", required = true, description = "Motivo de la cancelación del registro, si aplica.")
  public String getMotivoCancelacion() {
    return motivoCancelacion;
  }

  public void setMotivoCancelacion(String motivoCancelacion) {
    this.motivoCancelacion = motivoCancelacion;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara estadoMatricula(String estadoMatricula) {
    this.estadoMatricula = estadoMatricula;
    return this;
  }

   /**
   * Estado actual de la matrícula.
   * @return estadoMatricula
  **/
  @Schema(example = "ACTIVA", required = true, description = "Estado actual de la matrícula.")
  public String getEstadoMatricula() {
    return estadoMatricula;
  }

  public void setEstadoMatricula(String estadoMatricula) {
    this.estadoMatricula = estadoMatricula;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara tipoSociedad(String tipoSociedad) {
    this.tipoSociedad = tipoSociedad;
    return this;
  }

   /**
   * Tipo de sociedad.
   * @return tipoSociedad
  **/
  @Schema(example = "SOCIEDAD COMERCIAL", required = true, description = "Tipo de sociedad.")
  public String getTipoSociedad() {
    return tipoSociedad;
  }

  public void setTipoSociedad(String tipoSociedad) {
    this.tipoSociedad = tipoSociedad;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara tipoOrganizacion(String tipoOrganizacion) {
    this.tipoOrganizacion = tipoOrganizacion;
    return this;
  }

   /**
   * Tipo de organización.
   * @return tipoOrganizacion
  **/
  @Schema(example = "SOCIEDADES POR ACCIONES SIMPLIFICADAS SAS", required = true, description = "Tipo de organización.")
  public String getTipoOrganizacion() {
    return tipoOrganizacion;
  }

  public void setTipoOrganizacion(String tipoOrganizacion) {
    this.tipoOrganizacion = tipoOrganizacion;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara categoriaMatricula(String categoriaMatricula) {
    this.categoriaMatricula = categoriaMatricula;
    return this;
  }

   /**
   * Categoría de la matrícula.
   * @return categoriaMatricula
  **/
  @Schema(example = "SOCIEDAD ó PERSONA JURIDICA PRINCIPAL ó ESAL", required = true, description = "Categoría de la matrícula.")
  public String getCategoriaMatricula() {
    return categoriaMatricula;
  }

  public void setCategoriaMatricula(String categoriaMatricula) {
    this.categoriaMatricula = categoriaMatricula;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara fechaUltimaAct(String fechaUltimaAct) {
    this.fechaUltimaAct = fechaUltimaAct;
    return this;
  }

   /**
   * Get fechaUltimaAct
   * @return fechaUltimaAct
  **/
  @Schema(required = true, description = "")
  public String getFechaUltimaAct() {
    return fechaUltimaAct;
  }

  public void setFechaUltimaAct(String fechaUltimaAct) {
    this.fechaUltimaAct = fechaUltimaAct;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara empleados(String empleados) {
    this.empleados = empleados;
    return this;
  }

   /**
   * Número de empleados.
   * @return empleados
  **/
  @Schema(required = true, description = "Número de empleados.")
  public String getEmpleados() {
    return empleados;
  }

  public void setEmpleados(String empleados) {
    this.empleados = empleados;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara afiliado(AfiliadoEnum afiliado) {
    this.afiliado = afiliado;
    return this;
  }

   /**
   * Indica si la empresa está afiliada a la Cámara de Comercio.
   * @return afiliado
  **/
  @Schema(required = true, description = "Indica si la empresa está afiliada a la Cámara de Comercio.")
  public AfiliadoEnum getAfiliado() {
    return afiliado;
  }

  public void setAfiliado(AfiliadoEnum afiliado) {
    this.afiliado = afiliado;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara beneficiarioLey1780(String beneficiarioLey1780) {
    this.beneficiarioLey1780 = beneficiarioLey1780;
    return this;
  }

   /**
   * Indica si es beneficiario de la Ley 1780.
   * @return beneficiarioLey1780
  **/
  @Schema(required = true, description = "Indica si es beneficiario de la Ley 1780.")
  public String getBeneficiarioLey1780() {
    return beneficiarioLey1780;
  }

  public void setBeneficiarioLey1780(String beneficiarioLey1780) {
    this.beneficiarioLey1780 = beneficiarioLey1780;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara listActividadEconomica(List<ResponseRuesCamaraUnificadoVODetalleCamaraListActividadEconomica> listActividadEconomica) {
    this.listActividadEconomica = listActividadEconomica;
    return this;
  }

  public ResponseRuesCamaraUnificadoVODetalleCamara addListActividadEconomicaItem(ResponseRuesCamaraUnificadoVODetalleCamaraListActividadEconomica listActividadEconomicaItem) {
    this.listActividadEconomica.add(listActividadEconomicaItem);
    return this;
  }

   /**
   * Listado de actividades económicas de la empresa.
   * @return listActividadEconomica
  **/
  @Schema(required = true, description = "Listado de actividades económicas de la empresa.")
  public List<ResponseRuesCamaraUnificadoVODetalleCamaraListActividadEconomica> getListActividadEconomica() {
    return listActividadEconomica;
  }

  public void setListActividadEconomica(List<ResponseRuesCamaraUnificadoVODetalleCamaraListActividadEconomica> listActividadEconomica) {
    this.listActividadEconomica = listActividadEconomica;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuesCamaraUnificadoVODetalleCamara responseRuesCamaraUnificadoVODetalleCamara = (ResponseRuesCamaraUnificadoVODetalleCamara) o;
    return Objects.equals(this.razonSocial, responseRuesCamaraUnificadoVODetalleCamara.razonSocial) &&
        Objects.equals(this.sigla, responseRuesCamaraUnificadoVODetalleCamara.sigla) &&
        Objects.equals(this.camaraComercio, responseRuesCamaraUnificadoVODetalleCamara.camaraComercio) &&
        Objects.equals(this.numeroMatricula, responseRuesCamaraUnificadoVODetalleCamara.numeroMatricula) &&
        Objects.equals(this.identificacion, responseRuesCamaraUnificadoVODetalleCamara.identificacion) &&
        Objects.equals(this.ultimoRenovado, responseRuesCamaraUnificadoVODetalleCamara.ultimoRenovado) &&
        Objects.equals(this.fechaMatricula, responseRuesCamaraUnificadoVODetalleCamara.fechaMatricula) &&
        Objects.equals(this.fechaCancelacion, responseRuesCamaraUnificadoVODetalleCamara.fechaCancelacion) &&
        Objects.equals(this.fechaVigencia, responseRuesCamaraUnificadoVODetalleCamara.fechaVigencia) &&
        Objects.equals(this.fechaRenovacion, responseRuesCamaraUnificadoVODetalleCamara.fechaRenovacion) &&
        Objects.equals(this.motivoCancelacion, responseRuesCamaraUnificadoVODetalleCamara.motivoCancelacion) &&
        Objects.equals(this.estadoMatricula, responseRuesCamaraUnificadoVODetalleCamara.estadoMatricula) &&
        Objects.equals(this.tipoSociedad, responseRuesCamaraUnificadoVODetalleCamara.tipoSociedad) &&
        Objects.equals(this.tipoOrganizacion, responseRuesCamaraUnificadoVODetalleCamara.tipoOrganizacion) &&
        Objects.equals(this.categoriaMatricula, responseRuesCamaraUnificadoVODetalleCamara.categoriaMatricula) &&
        Objects.equals(this.fechaUltimaAct, responseRuesCamaraUnificadoVODetalleCamara.fechaUltimaAct) &&
        Objects.equals(this.empleados, responseRuesCamaraUnificadoVODetalleCamara.empleados) &&
        Objects.equals(this.afiliado, responseRuesCamaraUnificadoVODetalleCamara.afiliado) &&
        Objects.equals(this.beneficiarioLey1780, responseRuesCamaraUnificadoVODetalleCamara.beneficiarioLey1780) &&
        Objects.equals(this.listActividadEconomica, responseRuesCamaraUnificadoVODetalleCamara.listActividadEconomica);
  }

  @Override
  public int hashCode() {
    return Objects.hash(razonSocial, sigla, camaraComercio, numeroMatricula, identificacion, ultimoRenovado, fechaMatricula, fechaCancelacion, fechaVigencia, fechaRenovacion, motivoCancelacion, estadoMatricula, tipoSociedad, tipoOrganizacion, categoriaMatricula, fechaUltimaAct, empleados, afiliado, beneficiarioLey1780, listActividadEconomica);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuesCamaraUnificadoVODetalleCamara {\n");
    
    sb.append("    razonSocial: ").append(toIndentedString(razonSocial)).append("\n");
    sb.append("    sigla: ").append(toIndentedString(sigla)).append("\n");
    sb.append("    camaraComercio: ").append(toIndentedString(camaraComercio)).append("\n");
    sb.append("    numeroMatricula: ").append(toIndentedString(numeroMatricula)).append("\n");
    sb.append("    identificacion: ").append(toIndentedString(identificacion)).append("\n");
    sb.append("    ultimoRenovado: ").append(toIndentedString(ultimoRenovado)).append("\n");
    sb.append("    fechaMatricula: ").append(toIndentedString(fechaMatricula)).append("\n");
    sb.append("    fechaCancelacion: ").append(toIndentedString(fechaCancelacion)).append("\n");
    sb.append("    fechaVigencia: ").append(toIndentedString(fechaVigencia)).append("\n");
    sb.append("    fechaRenovacion: ").append(toIndentedString(fechaRenovacion)).append("\n");
    sb.append("    motivoCancelacion: ").append(toIndentedString(motivoCancelacion)).append("\n");
    sb.append("    estadoMatricula: ").append(toIndentedString(estadoMatricula)).append("\n");
    sb.append("    tipoSociedad: ").append(toIndentedString(tipoSociedad)).append("\n");
    sb.append("    tipoOrganizacion: ").append(toIndentedString(tipoOrganizacion)).append("\n");
    sb.append("    categoriaMatricula: ").append(toIndentedString(categoriaMatricula)).append("\n");
    sb.append("    fechaUltimaAct: ").append(toIndentedString(fechaUltimaAct)).append("\n");
    sb.append("    empleados: ").append(toIndentedString(empleados)).append("\n");
    sb.append("    afiliado: ").append(toIndentedString(afiliado)).append("\n");
    sb.append("    beneficiarioLey1780: ").append(toIndentedString(beneficiarioLey1780)).append("\n");
    sb.append("    listActividadEconomica: ").append(toIndentedString(listActividadEconomica)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
