/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseRuntVODetalleLicencias
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuntVODetalleLicencias {
  @SerializedName("categoria")
  private String categoria = null;

  @SerializedName("fechaExpedicion")
  private String fechaExpedicion = null;

  @SerializedName("fechaVencimiento")
  private String fechaVencimiento = null;

  @SerializedName("fechaVencimientoExamen")
  private String fechaVencimientoExamen = null;

  @SerializedName("categoriaAntigua")
  private String categoriaAntigua = null;

  public ResponseRuntVODetalleLicencias categoria(String categoria) {
    this.categoria = categoria;
    return this;
  }

   /**
   * Categoría de la licencia de conducción.
   * @return categoria
  **/
  @Schema(example = "C1", required = true, description = "Categoría de la licencia de conducción.")
  public String getCategoria() {
    return categoria;
  }

  public void setCategoria(String categoria) {
    this.categoria = categoria;
  }

  public ResponseRuntVODetalleLicencias fechaExpedicion(String fechaExpedicion) {
    this.fechaExpedicion = fechaExpedicion;
    return this;
  }

   /**
   * Get fechaExpedicion
   * @return fechaExpedicion
  **/
  @Schema(required = true, description = "")
  public String getFechaExpedicion() {
    return fechaExpedicion;
  }

  public void setFechaExpedicion(String fechaExpedicion) {
    this.fechaExpedicion = fechaExpedicion;
  }

  public ResponseRuntVODetalleLicencias fechaVencimiento(String fechaVencimiento) {
    this.fechaVencimiento = fechaVencimiento;
    return this;
  }

   /**
   * Get fechaVencimiento
   * @return fechaVencimiento
  **/
  @Schema(required = true, description = "")
  public String getFechaVencimiento() {
    return fechaVencimiento;
  }

  public void setFechaVencimiento(String fechaVencimiento) {
    this.fechaVencimiento = fechaVencimiento;
  }

  public ResponseRuntVODetalleLicencias fechaVencimientoExamen(String fechaVencimientoExamen) {
    this.fechaVencimientoExamen = fechaVencimientoExamen;
    return this;
  }

   /**
   * Get fechaVencimientoExamen
   * @return fechaVencimientoExamen
  **/
  @Schema(required = true, description = "")
  public String getFechaVencimientoExamen() {
    return fechaVencimientoExamen;
  }

  public void setFechaVencimientoExamen(String fechaVencimientoExamen) {
    this.fechaVencimientoExamen = fechaVencimientoExamen;
  }

  public ResponseRuntVODetalleLicencias categoriaAntigua(String categoriaAntigua) {
    this.categoriaAntigua = categoriaAntigua;
    return this;
  }

   /**
   * Categoría antigua si aplica.
   * @return categoriaAntigua
  **/
  @Schema(required = true, description = "Categoría antigua si aplica.")
  public String getCategoriaAntigua() {
    return categoriaAntigua;
  }

  public void setCategoriaAntigua(String categoriaAntigua) {
    this.categoriaAntigua = categoriaAntigua;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuntVODetalleLicencias responseRuntVODetalleLicencias = (ResponseRuntVODetalleLicencias) o;
    return Objects.equals(this.categoria, responseRuntVODetalleLicencias.categoria) &&
        Objects.equals(this.fechaExpedicion, responseRuntVODetalleLicencias.fechaExpedicion) &&
        Objects.equals(this.fechaVencimiento, responseRuntVODetalleLicencias.fechaVencimiento) &&
        Objects.equals(this.fechaVencimientoExamen, responseRuntVODetalleLicencias.fechaVencimientoExamen) &&
        Objects.equals(this.categoriaAntigua, responseRuntVODetalleLicencias.categoriaAntigua);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoria, fechaExpedicion, fechaVencimiento, fechaVencimientoExamen, categoriaAntigua);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuntVODetalleLicencias {\n");
    
    sb.append("    categoria: ").append(toIndentedString(categoria)).append("\n");
    sb.append("    fechaExpedicion: ").append(toIndentedString(fechaExpedicion)).append("\n");
    sb.append("    fechaVencimiento: ").append(toIndentedString(fechaVencimiento)).append("\n");
    sb.append("    fechaVencimientoExamen: ").append(toIndentedString(fechaVencimientoExamen)).append("\n");
    sb.append("    categoriaAntigua: ").append(toIndentedString(categoriaAntigua)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
