/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1 {
  @SerializedName("numeroResolucionPensionPG")
  private String numeroResolucionPensionPG = null;

  @SerializedName("pensionCompartidaPG")
  private String pensionCompartidaPG = null;

  @SerializedName("estadoPension")
  private String estadoPension = null;

  @SerializedName("tipoPension")
  private String tipoPension = null;

  @SerializedName("tipoPensionado")
  private String tipoPensionado = null;

  @SerializedName("pagador")
  private String pagador = null;

  @SerializedName("fechaResolucion")
  private String fechaResolucion = null;

  @SerializedName("modalidadPensionPG")
  private String modalidadPensionPG = null;

  public ResponseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1 numeroResolucionPensionPG(String numeroResolucionPensionPG) {
    this.numeroResolucionPensionPG = numeroResolucionPensionPG;
    return this;
  }

   /**
   * Número de resolución de pensión.
   * @return numeroResolucionPensionPG
  **/
  @Schema(example = "101907", required = true, description = "Número de resolución de pensión.")
  public String getNumeroResolucionPensionPG() {
    return numeroResolucionPensionPG;
  }

  public void setNumeroResolucionPensionPG(String numeroResolucionPensionPG) {
    this.numeroResolucionPensionPG = numeroResolucionPensionPG;
  }

  public ResponseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1 pensionCompartidaPG(String pensionCompartidaPG) {
    this.pensionCompartidaPG = pensionCompartidaPG;
    return this;
  }

   /**
   * Indica si la pensión es compartida.
   * @return pensionCompartidaPG
  **/
  @Schema(example = "- --", required = true, description = "Indica si la pensión es compartida.")
  public String getPensionCompartidaPG() {
    return pensionCompartidaPG;
  }

  public void setPensionCompartidaPG(String pensionCompartidaPG) {
    this.pensionCompartidaPG = pensionCompartidaPG;
  }

  public ResponseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1 estadoPension(String estadoPension) {
    this.estadoPension = estadoPension;
    return this;
  }

   /**
   * Estado de la pensión.
   * @return estadoPension
  **/
  @Schema(example = "Activo", required = true, description = "Estado de la pensión.")
  public String getEstadoPension() {
    return estadoPension;
  }

  public void setEstadoPension(String estadoPension) {
    this.estadoPension = estadoPension;
  }

  public ResponseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1 tipoPension(String tipoPension) {
    this.tipoPension = tipoPension;
    return this;
  }

   /**
   * Tipo de pensión
   * @return tipoPension
  **/
  @Schema(example = "Vejez", required = true, description = "Tipo de pensión")
  public String getTipoPension() {
    return tipoPension;
  }

  public void setTipoPension(String tipoPension) {
    this.tipoPension = tipoPension;
  }

  public ResponseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1 tipoPensionado(String tipoPensionado) {
    this.tipoPensionado = tipoPensionado;
    return this;
  }

   /**
   * Tipo de pensionado.
   * @return tipoPensionado
  **/
  @Schema(example = "Régimen de prima media con tope máximo de pensión", required = true, description = "Tipo de pensionado.")
  public String getTipoPensionado() {
    return tipoPensionado;
  }

  public void setTipoPensionado(String tipoPensionado) {
    this.tipoPensionado = tipoPensionado;
  }

  public ResponseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1 pagador(String pagador) {
    this.pagador = pagador;
    return this;
  }

   /**
   * Entidad pagadora de la pensión.
   * @return pagador
  **/
  @Schema(example = "ADMINISTRADORA COLOMBIANA DE PENSIONES COLPENSIONES", required = true, description = "Entidad pagadora de la pensión.")
  public String getPagador() {
    return pagador;
  }

  public void setPagador(String pagador) {
    this.pagador = pagador;
  }

  public ResponseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1 fechaResolucion(String fechaResolucion) {
    this.fechaResolucion = fechaResolucion;
    return this;
  }

   /**
   * Get fechaResolucion
   * @return fechaResolucion
  **/
  @Schema(required = true, description = "")
  public String getFechaResolucion() {
    return fechaResolucion;
  }

  public void setFechaResolucion(String fechaResolucion) {
    this.fechaResolucion = fechaResolucion;
  }

  public ResponseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1 modalidadPensionPG(String modalidadPensionPG) {
    this.modalidadPensionPG = modalidadPensionPG;
    return this;
  }

   /**
   * Modalidad de la pensión.
   * @return modalidadPensionPG
  **/
  @Schema(example = "Régimen general", required = true, description = "Modalidad de la pensión.")
  public String getModalidadPensionPG() {
    return modalidadPensionPG;
  }

  public void setModalidadPensionPG(String modalidadPensionPG) {
    this.modalidadPensionPG = modalidadPensionPG;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1 responseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1 = (ResponseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1) o;
    return Objects.equals(this.numeroResolucionPensionPG, responseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1.numeroResolucionPensionPG) &&
        Objects.equals(this.pensionCompartidaPG, responseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1.pensionCompartidaPG) &&
        Objects.equals(this.estadoPension, responseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1.estadoPension) &&
        Objects.equals(this.tipoPension, responseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1.tipoPension) &&
        Objects.equals(this.tipoPensionado, responseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1.tipoPensionado) &&
        Objects.equals(this.pagador, responseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1.pagador) &&
        Objects.equals(this.fechaResolucion, responseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1.fechaResolucion) &&
        Objects.equals(this.modalidadPensionPG, responseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1.modalidadPensionPG);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroResolucionPensionPG, pensionCompartidaPG, estadoPension, tipoPension, tipoPensionado, pagador, fechaResolucion, modalidadPensionPG);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuafVOReportVOLstPensionadosTblPensionadosTblPensionadosGroup1CollectionTblPensionadosGroup1 {\n");
    
    sb.append("    numeroResolucionPensionPG: ").append(toIndentedString(numeroResolucionPensionPG)).append("\n");
    sb.append("    pensionCompartidaPG: ").append(toIndentedString(pensionCompartidaPG)).append("\n");
    sb.append("    estadoPension: ").append(toIndentedString(estadoPension)).append("\n");
    sb.append("    tipoPension: ").append(toIndentedString(tipoPension)).append("\n");
    sb.append("    tipoPensionado: ").append(toIndentedString(tipoPensionado)).append("\n");
    sb.append("    pagador: ").append(toIndentedString(pagador)).append("\n");
    sb.append("    fechaResolucion: ").append(toIndentedString(fechaResolucion)).append("\n");
    sb.append("    modalidadPensionPG: ").append(toIndentedString(modalidadPensionPG)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
