/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Colombia -  20036579 - Fuente que retorna el nombre completo de las personas
 */
@Schema(description = "Colombia -  20036579 - Fuente que retorna el nombre completo de las personas")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseNombreCompletoIntegralVO {
  @SerializedName("nombrePersona")
  private String nombrePersona = null;

  @SerializedName("primerNombre")
  private String primerNombre = null;

  @SerializedName("segundoNombre")
  private String segundoNombre = null;

  @SerializedName("primerApellido")
  private String primerApellido = null;

  @SerializedName("segundoApellido")
  private String segundoApellido = null;

  @SerializedName("mensaje")
  private String mensaje = null;

  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  /**
   * Define si la consulta falló o no cuando se fue a la fuente.
   */
  @JsonAdapter(FuenteFalloEnum.Adapter.class)
  public enum FuenteFalloEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    FuenteFalloEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FuenteFalloEnum fromValue(String input) {
      for (FuenteFalloEnum b : FuenteFalloEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FuenteFalloEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FuenteFalloEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public FuenteFalloEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return FuenteFalloEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("fuenteFallo")
  private FuenteFalloEnum fuenteFallo = null;

  public ResponseNombreCompletoIntegralVO nombrePersona(String nombrePersona) {
    this.nombrePersona = nombrePersona;
    return this;
  }

   /**
   * Nombre completo de la persona consultada. Este valor retorna vacío si no se encuentra la persona.
   * @return nombrePersona
  **/
  @Schema(example = "JUAN CARLOS PEREZ LOPEZ", required = true, description = "Nombre completo de la persona consultada. Este valor retorna vacío si no se encuentra la persona.")
  public String getNombrePersona() {
    return nombrePersona;
  }

  public void setNombrePersona(String nombrePersona) {
    this.nombrePersona = nombrePersona;
  }

  public ResponseNombreCompletoIntegralVO primerNombre(String primerNombre) {
    this.primerNombre = primerNombre;
    return this;
  }

   /**
   * Primer nombre o nombre completo o nombres y apellidos completos.
   * @return primerNombre
  **/
  @Schema(example = "JUAN", required = true, description = "Primer nombre o nombre completo o nombres y apellidos completos.")
  public String getPrimerNombre() {
    return primerNombre;
  }

  public void setPrimerNombre(String primerNombre) {
    this.primerNombre = primerNombre;
  }

  public ResponseNombreCompletoIntegralVO segundoNombre(String segundoNombre) {
    this.segundoNombre = segundoNombre;
    return this;
  }

   /**
   * Segundo nombre.
   * @return segundoNombre
  **/
  @Schema(example = "CARLOS", required = true, description = "Segundo nombre.")
  public String getSegundoNombre() {
    return segundoNombre;
  }

  public void setSegundoNombre(String segundoNombre) {
    this.segundoNombre = segundoNombre;
  }

  public ResponseNombreCompletoIntegralVO primerApellido(String primerApellido) {
    this.primerApellido = primerApellido;
    return this;
  }

   /**
   * Primer apellido o apellidos completos.
   * @return primerApellido
  **/
  @Schema(example = "PEREZ", required = true, description = "Primer apellido o apellidos completos.")
  public String getPrimerApellido() {
    return primerApellido;
  }

  public void setPrimerApellido(String primerApellido) {
    this.primerApellido = primerApellido;
  }

  public ResponseNombreCompletoIntegralVO segundoApellido(String segundoApellido) {
    this.segundoApellido = segundoApellido;
    return this;
  }

   /**
   * Segundo apellido.
   * @return segundoApellido
  **/
  @Schema(example = "LOPEZ", required = true, description = "Segundo apellido.")
  public String getSegundoApellido() {
    return segundoApellido;
  }

  public void setSegundoApellido(String segundoApellido) {
    this.segundoApellido = segundoApellido;
  }

  public ResponseNombreCompletoIntegralVO mensaje(String mensaje) {
    this.mensaje = mensaje;
    return this;
  }

   /**
   * Respuesta de obtención de nombre.
   * @return mensaje
  **/
  @Schema(example = "Nombre obtenido satisfactoriamente", required = true, description = "Respuesta de obtención de nombre.")
  public String getMensaje() {
    return mensaje;
  }

  public void setMensaje(String mensaje) {
    this.mensaje = mensaje;
  }

  public ResponseNombreCompletoIntegralVO fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Get fechaConsulta
   * @return fechaConsulta
  **/
  @Schema(required = true, description = "")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public ResponseNombreCompletoIntegralVO fuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
    return this;
  }

   /**
   * Define si la consulta falló o no cuando se fue a la fuente.
   * @return fuenteFallo
  **/
  @Schema(example = "NO", required = true, description = "Define si la consulta falló o no cuando se fue a la fuente.")
  public FuenteFalloEnum getFuenteFallo() {
    return fuenteFallo;
  }

  public void setFuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseNombreCompletoIntegralVO responseNombreCompletoIntegralVO = (ResponseNombreCompletoIntegralVO) o;
    return Objects.equals(this.nombrePersona, responseNombreCompletoIntegralVO.nombrePersona) &&
        Objects.equals(this.primerNombre, responseNombreCompletoIntegralVO.primerNombre) &&
        Objects.equals(this.segundoNombre, responseNombreCompletoIntegralVO.segundoNombre) &&
        Objects.equals(this.primerApellido, responseNombreCompletoIntegralVO.primerApellido) &&
        Objects.equals(this.segundoApellido, responseNombreCompletoIntegralVO.segundoApellido) &&
        Objects.equals(this.mensaje, responseNombreCompletoIntegralVO.mensaje) &&
        Objects.equals(this.fechaConsulta, responseNombreCompletoIntegralVO.fechaConsulta) &&
        Objects.equals(this.fuenteFallo, responseNombreCompletoIntegralVO.fuenteFallo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nombrePersona, primerNombre, segundoNombre, primerApellido, segundoApellido, mensaje, fechaConsulta, fuenteFallo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseNombreCompletoIntegralVO {\n");
    
    sb.append("    nombrePersona: ").append(toIndentedString(nombrePersona)).append("\n");
    sb.append("    primerNombre: ").append(toIndentedString(primerNombre)).append("\n");
    sb.append("    segundoNombre: ").append(toIndentedString(segundoNombre)).append("\n");
    sb.append("    primerApellido: ").append(toIndentedString(primerApellido)).append("\n");
    sb.append("    segundoApellido: ").append(toIndentedString(segundoApellido)).append("\n");
    sb.append("    mensaje: ").append(toIndentedString(mensaje)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    fuenteFallo: ").append(toIndentedString(fuenteFallo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
