/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseAfiliadosCompensadoVO;
import io.swagger.client.model.ResponseAntecedentesBDUAVO;
import io.swagger.client.model.ResponseAntecedentesPoliciaVO;
import io.swagger.client.model.ResponseAntecedentesRamaVO;
import io.swagger.client.model.ResponseCamaraComercioMedellinVO;
import io.swagger.client.model.ResponseCambioEstratoBgaVO;
import io.swagger.client.model.ResponseCertificadoRegistroCivilVO;
import io.swagger.client.model.ResponseCertificadoSnrVO;
import io.swagger.client.model.ResponseCmpVO;
import io.swagger.client.model.ResponseColpensionesVO;
import io.swagger.client.model.ResponseConaltelVO;
import io.swagger.client.model.ResponseConsejoProfesionalVO;
import io.swagger.client.model.ResponseContraloriaVO;
import io.swagger.client.model.ResponseCopniaVO;
import io.swagger.client.model.ResponseCpaeVO;
import io.swagger.client.model.ResponseCpbiolVersionDosVO;
import io.swagger.client.model.ResponseCpipVO;
import io.swagger.client.model.ResponseCpiqVO;
import io.swagger.client.model.ResponseCpnaaVO;
import io.swagger.client.model.ResponseCpntVO;
import io.swagger.client.model.ResponseCufeDianVO;
import io.swagger.client.model.ResponseDianRutVO;
import io.swagger.client.model.ResponseDirectorioEmpresasVO;
import io.swagger.client.model.ResponseEinformaVO;
import io.swagger.client.model.ResponseEmpresasGoogleVO;
import io.swagger.client.model.ResponseEstadoCedulaExtranjeriaVO;
import io.swagger.client.model.ResponseEstadoCedulaVO;
import io.swagger.client.model.ResponseEstadoTramiteCedulaVO;
import io.swagger.client.model.ResponseFiduprevisoraVO;
import io.swagger.client.model.ResponseFopepVO;
import io.swagger.client.model.ResponseGarantiasMobiliariasVO;
import io.swagger.client.model.ResponseInpecReclusosVO;
import io.swagger.client.model.ResponseLibretaMilitarVO;
import io.swagger.client.model.ResponseMiCasaYaVO;
import io.swagger.client.model.ResponseMigracionColombiaVO;
import io.swagger.client.model.ResponseMigracionPptVO;
import io.swagger.client.model.ResponseNombreCompletoIntegralVO;
import io.swagger.client.model.ResponseNombreCompletoVO;
import io.swagger.client.model.ResponseOfacVO;
import io.swagger.client.model.ResponseOnuVO;
import io.swagger.client.model.ResponsePagoSnrVO;
import io.swagger.client.model.ResponsePepVO;
import io.swagger.client.model.ResponsePersoneriaBogotaVO;
import io.swagger.client.model.ResponseProcuraduriaVO;
import io.swagger.client.model.ResponseProfesionalSaludVO;
import io.swagger.client.model.ResponseProveedoresFicticiosVO;
import io.swagger.client.model.ResponsePuestoVotacionVO;
import io.swagger.client.model.ResponseRcVigenciaDocumentoVO;
import io.swagger.client.model.ResponseRetencionVehiculosVO;
import io.swagger.client.model.ResponseRethusVO;
import io.swagger.client.model.ResponseRneVO;
import io.swagger.client.model.ResponseRnmcVO;
import io.swagger.client.model.ResponseRntVO;
import io.swagger.client.model.ResponseRuafVO;
import io.swagger.client.model.ResponseRuesCamaraEmpresarialVO;
import io.swagger.client.model.ResponseRuesCamaraUnificadoVO;
import io.swagger.client.model.ResponseRuntPlacaVO;
import io.swagger.client.model.ResponseRuntVO;
import io.swagger.client.model.ResponseSarenVO;
import io.swagger.client.model.ResponseSecopVO;
import io.swagger.client.model.ResponseSeguridadSocialVO;
import io.swagger.client.model.ResponseSenescytVO;
import io.swagger.client.model.ResponseSeniatVO;
import io.swagger.client.model.ResponseServicioNuevoSoiVO;
import io.swagger.client.model.ResponseSimitVO;
import io.swagger.client.model.ResponseSisbenGruposVO;
import io.swagger.client.model.ResponseUrnaVO;
import io.swagger.client.model.ResponseVeterinarioVO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Response
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class Response {
  @SerializedName("rcVigenciaDocumentoVO")
  private ResponseRcVigenciaDocumentoVO rcVigenciaDocumentoVO = null;

  @SerializedName("afiliadosCompensadoVO")
  private ResponseAfiliadosCompensadoVO afiliadosCompensadoVO = null;

  @SerializedName("antecedentesPoliciaVO")
  private ResponseAntecedentesPoliciaVO antecedentesPoliciaVO = null;

  @SerializedName("antecedentesRamaVO")
  private ResponseAntecedentesRamaVO antecedentesRamaVO = null;

  @SerializedName("antecedentesBDUAVO")
  private ResponseAntecedentesBDUAVO antecedentesBDUAVO = null;

  @SerializedName("camaraComercioMedellinVO")
  private ResponseCamaraComercioMedellinVO camaraComercioMedellinVO = null;

  @SerializedName("cambioEstratoBgaVO")
  private ResponseCambioEstratoBgaVO cambioEstratoBgaVO = null;

  @SerializedName("certificadoRegistroCivilVO")
  private ResponseCertificadoRegistroCivilVO certificadoRegistroCivilVO = null;

  @SerializedName("certificadoSnrVO")
  private ResponseCertificadoSnrVO certificadoSnrVO = null;

  @SerializedName("colpensionesVO")
  private ResponseColpensionesVO colpensionesVO = null;

  @SerializedName("conaltelVO")
  private ResponseConaltelVO conaltelVO = null;

  @SerializedName("consejoProfesionalVO")
  private ResponseConsejoProfesionalVO consejoProfesionalVO = null;

  @SerializedName("contraloriaVO")
  private ResponseContraloriaVO contraloriaVO = null;

  @SerializedName("copniaVO")
  private ResponseCopniaVO copniaVO = null;

  @SerializedName("cpaeVO")
  private ResponseCpaeVO cpaeVO = null;

  @SerializedName("cpbiolVersionDosVO")
  private ResponseCpbiolVersionDosVO cpbiolVersionDosVO = null;

  @SerializedName("cpipVO")
  private ResponseCpipVO cpipVO = null;

  @SerializedName("cpiqVO")
  private ResponseCpiqVO cpiqVO = null;

  @SerializedName("cpnaaVO")
  private ResponseCpnaaVO cpnaaVO = null;

  @SerializedName("cpntVO")
  private ResponseCpntVO cpntVO = null;

  @SerializedName("cufeDianVO")
  private ResponseCufeDianVO cufeDianVO = null;

  @SerializedName("dianRutVO")
  private ResponseDianRutVO dianRutVO = null;

  @SerializedName("directorioEmpresasVO")
  private ResponseDirectorioEmpresasVO directorioEmpresasVO = null;

  @SerializedName("einformaVO")
  private ResponseEinformaVO einformaVO = null;

  @SerializedName("empresasGoogleVO")
  private ResponseEmpresasGoogleVO empresasGoogleVO = null;

  @SerializedName("estadoCedulaExtranjeriaVO")
  private ResponseEstadoCedulaExtranjeriaVO estadoCedulaExtranjeriaVO = null;

  @SerializedName("estadoCedulaVO")
  private ResponseEstadoCedulaVO estadoCedulaVO = null;

  @SerializedName("estadoTramiteCedulaVO")
  private ResponseEstadoTramiteCedulaVO estadoTramiteCedulaVO = null;

  @SerializedName("fiduprevisoraVO")
  private ResponseFiduprevisoraVO fiduprevisoraVO = null;

  @SerializedName("fopepVO")
  private ResponseFopepVO fopepVO = null;

  @SerializedName("garantiasMobiliariasVO")
  private ResponseGarantiasMobiliariasVO garantiasMobiliariasVO = null;

  @SerializedName("inpecReclusosVO")
  private ResponseInpecReclusosVO inpecReclusosVO = null;

  @SerializedName("libretaMilitarVO")
  private ResponseLibretaMilitarVO libretaMilitarVO = null;

  @SerializedName("miCasaYaVO")
  private ResponseMiCasaYaVO miCasaYaVO = null;

  @SerializedName("migracionColombiaVO")
  private ResponseMigracionColombiaVO migracionColombiaVO = null;

  @SerializedName("migracionPptVO")
  private ResponseMigracionPptVO migracionPptVO = null;

  @SerializedName("nombreCompletoIntegralVO")
  private ResponseNombreCompletoIntegralVO nombreCompletoIntegralVO = null;

  @SerializedName("nombreCompletoVO")
  private ResponseNombreCompletoVO nombreCompletoVO = null;

  @SerializedName("ofacVO")
  private ResponseOfacVO ofacVO = null;

  @SerializedName("onuVO")
  private ResponseOnuVO onuVO = null;

  @SerializedName("pagoSnrVO")
  private ResponsePagoSnrVO pagoSnrVO = null;

  @SerializedName("pepVO")
  private ResponsePepVO pepVO = null;

  @SerializedName("personeriaBogotaVO")
  private ResponsePersoneriaBogotaVO personeriaBogotaVO = null;

  @SerializedName("procuraduriaVO")
  private ResponseProcuraduriaVO procuraduriaVO = null;

  @SerializedName("proveedoresFicticiosVO")
  private ResponseProveedoresFicticiosVO proveedoresFicticiosVO = null;

  @SerializedName("puestoVotacionVO")
  private ResponsePuestoVotacionVO puestoVotacionVO = null;

  @SerializedName("retencionVehiculosVO")
  private ResponseRetencionVehiculosVO retencionVehiculosVO = null;

  @SerializedName("rethusVO")
  private ResponseRethusVO rethusVO = null;

  @SerializedName("rneVO")
  private ResponseRneVO rneVO = null;

  @SerializedName("rnmcVO")
  private ResponseRnmcVO rnmcVO = null;

  @SerializedName("rntVO")
  private ResponseRntVO rntVO = null;

  @SerializedName("ruafVO")
  private ResponseRuafVO ruafVO = null;

  @SerializedName("ruesCamaraEmpresarialVO")
  private ResponseRuesCamaraEmpresarialVO ruesCamaraEmpresarialVO = null;

  @SerializedName("ruesCamaraUnificadoVO")
  private ResponseRuesCamaraUnificadoVO ruesCamaraUnificadoVO = null;

  @SerializedName("runtPlacaVO")
  private ResponseRuntPlacaVO runtPlacaVO = null;

  @SerializedName("runtVO")
  private ResponseRuntVO runtVO = null;

  @SerializedName("secopVO")
  private ResponseSecopVO secopVO = null;

  @SerializedName("seguridadSocialVO")
  private ResponseSeguridadSocialVO seguridadSocialVO = null;

  @SerializedName("servicioNuevoSoiVO")
  private ResponseServicioNuevoSoiVO servicioNuevoSoiVO = null;

  @SerializedName("simitVO")
  private ResponseSimitVO simitVO = null;

  @SerializedName("sisbenGruposVO")
  private ResponseSisbenGruposVO sisbenGruposVO = null;

  @SerializedName("urnaVO")
  private ResponseUrnaVO urnaVO = null;

  @SerializedName("veterinarioVO")
  private ResponseVeterinarioVO veterinarioVO = null;

  @SerializedName("senescytVO")
  private ResponseSenescytVO senescytVO = null;

  @SerializedName("cmpVO")
  private ResponseCmpVO cmpVO = null;

  @SerializedName("profesionalSaludVO")
  private ResponseProfesionalSaludVO profesionalSaludVO = null;

  @SerializedName("sarenVO")
  private ResponseSarenVO sarenVO = null;

  @SerializedName("seniatVO")
  private ResponseSeniatVO seniatVO = null;

  public Response rcVigenciaDocumentoVO(ResponseRcVigenciaDocumentoVO rcVigenciaDocumentoVO) {
    this.rcVigenciaDocumentoVO = rcVigenciaDocumentoVO;
    return this;
  }

   /**
   * Get rcVigenciaDocumentoVO
   * @return rcVigenciaDocumentoVO
  **/
  @Schema(description = "")
  public ResponseRcVigenciaDocumentoVO getRcVigenciaDocumentoVO() {
    return rcVigenciaDocumentoVO;
  }

  public void setRcVigenciaDocumentoVO(ResponseRcVigenciaDocumentoVO rcVigenciaDocumentoVO) {
    this.rcVigenciaDocumentoVO = rcVigenciaDocumentoVO;
  }

  public Response afiliadosCompensadoVO(ResponseAfiliadosCompensadoVO afiliadosCompensadoVO) {
    this.afiliadosCompensadoVO = afiliadosCompensadoVO;
    return this;
  }

   /**
   * Get afiliadosCompensadoVO
   * @return afiliadosCompensadoVO
  **/
  @Schema(description = "")
  public ResponseAfiliadosCompensadoVO getAfiliadosCompensadoVO() {
    return afiliadosCompensadoVO;
  }

  public void setAfiliadosCompensadoVO(ResponseAfiliadosCompensadoVO afiliadosCompensadoVO) {
    this.afiliadosCompensadoVO = afiliadosCompensadoVO;
  }

  public Response antecedentesPoliciaVO(ResponseAntecedentesPoliciaVO antecedentesPoliciaVO) {
    this.antecedentesPoliciaVO = antecedentesPoliciaVO;
    return this;
  }

   /**
   * Get antecedentesPoliciaVO
   * @return antecedentesPoliciaVO
  **/
  @Schema(description = "")
  public ResponseAntecedentesPoliciaVO getAntecedentesPoliciaVO() {
    return antecedentesPoliciaVO;
  }

  public void setAntecedentesPoliciaVO(ResponseAntecedentesPoliciaVO antecedentesPoliciaVO) {
    this.antecedentesPoliciaVO = antecedentesPoliciaVO;
  }

  public Response antecedentesRamaVO(ResponseAntecedentesRamaVO antecedentesRamaVO) {
    this.antecedentesRamaVO = antecedentesRamaVO;
    return this;
  }

   /**
   * Get antecedentesRamaVO
   * @return antecedentesRamaVO
  **/
  @Schema(description = "")
  public ResponseAntecedentesRamaVO getAntecedentesRamaVO() {
    return antecedentesRamaVO;
  }

  public void setAntecedentesRamaVO(ResponseAntecedentesRamaVO antecedentesRamaVO) {
    this.antecedentesRamaVO = antecedentesRamaVO;
  }

  public Response antecedentesBDUAVO(ResponseAntecedentesBDUAVO antecedentesBDUAVO) {
    this.antecedentesBDUAVO = antecedentesBDUAVO;
    return this;
  }

   /**
   * Get antecedentesBDUAVO
   * @return antecedentesBDUAVO
  **/
  @Schema(description = "")
  public ResponseAntecedentesBDUAVO getAntecedentesBDUAVO() {
    return antecedentesBDUAVO;
  }

  public void setAntecedentesBDUAVO(ResponseAntecedentesBDUAVO antecedentesBDUAVO) {
    this.antecedentesBDUAVO = antecedentesBDUAVO;
  }

  public Response camaraComercioMedellinVO(ResponseCamaraComercioMedellinVO camaraComercioMedellinVO) {
    this.camaraComercioMedellinVO = camaraComercioMedellinVO;
    return this;
  }

   /**
   * Get camaraComercioMedellinVO
   * @return camaraComercioMedellinVO
  **/
  @Schema(description = "")
  public ResponseCamaraComercioMedellinVO getCamaraComercioMedellinVO() {
    return camaraComercioMedellinVO;
  }

  public void setCamaraComercioMedellinVO(ResponseCamaraComercioMedellinVO camaraComercioMedellinVO) {
    this.camaraComercioMedellinVO = camaraComercioMedellinVO;
  }

  public Response cambioEstratoBgaVO(ResponseCambioEstratoBgaVO cambioEstratoBgaVO) {
    this.cambioEstratoBgaVO = cambioEstratoBgaVO;
    return this;
  }

   /**
   * Get cambioEstratoBgaVO
   * @return cambioEstratoBgaVO
  **/
  @Schema(description = "")
  public ResponseCambioEstratoBgaVO getCambioEstratoBgaVO() {
    return cambioEstratoBgaVO;
  }

  public void setCambioEstratoBgaVO(ResponseCambioEstratoBgaVO cambioEstratoBgaVO) {
    this.cambioEstratoBgaVO = cambioEstratoBgaVO;
  }

  public Response certificadoRegistroCivilVO(ResponseCertificadoRegistroCivilVO certificadoRegistroCivilVO) {
    this.certificadoRegistroCivilVO = certificadoRegistroCivilVO;
    return this;
  }

   /**
   * Get certificadoRegistroCivilVO
   * @return certificadoRegistroCivilVO
  **/
  @Schema(description = "")
  public ResponseCertificadoRegistroCivilVO getCertificadoRegistroCivilVO() {
    return certificadoRegistroCivilVO;
  }

  public void setCertificadoRegistroCivilVO(ResponseCertificadoRegistroCivilVO certificadoRegistroCivilVO) {
    this.certificadoRegistroCivilVO = certificadoRegistroCivilVO;
  }

  public Response certificadoSnrVO(ResponseCertificadoSnrVO certificadoSnrVO) {
    this.certificadoSnrVO = certificadoSnrVO;
    return this;
  }

   /**
   * Get certificadoSnrVO
   * @return certificadoSnrVO
  **/
  @Schema(description = "")
  public ResponseCertificadoSnrVO getCertificadoSnrVO() {
    return certificadoSnrVO;
  }

  public void setCertificadoSnrVO(ResponseCertificadoSnrVO certificadoSnrVO) {
    this.certificadoSnrVO = certificadoSnrVO;
  }

  public Response colpensionesVO(ResponseColpensionesVO colpensionesVO) {
    this.colpensionesVO = colpensionesVO;
    return this;
  }

   /**
   * Get colpensionesVO
   * @return colpensionesVO
  **/
  @Schema(description = "")
  public ResponseColpensionesVO getColpensionesVO() {
    return colpensionesVO;
  }

  public void setColpensionesVO(ResponseColpensionesVO colpensionesVO) {
    this.colpensionesVO = colpensionesVO;
  }

  public Response conaltelVO(ResponseConaltelVO conaltelVO) {
    this.conaltelVO = conaltelVO;
    return this;
  }

   /**
   * Get conaltelVO
   * @return conaltelVO
  **/
  @Schema(description = "")
  public ResponseConaltelVO getConaltelVO() {
    return conaltelVO;
  }

  public void setConaltelVO(ResponseConaltelVO conaltelVO) {
    this.conaltelVO = conaltelVO;
  }

  public Response consejoProfesionalVO(ResponseConsejoProfesionalVO consejoProfesionalVO) {
    this.consejoProfesionalVO = consejoProfesionalVO;
    return this;
  }

   /**
   * Get consejoProfesionalVO
   * @return consejoProfesionalVO
  **/
  @Schema(description = "")
  public ResponseConsejoProfesionalVO getConsejoProfesionalVO() {
    return consejoProfesionalVO;
  }

  public void setConsejoProfesionalVO(ResponseConsejoProfesionalVO consejoProfesionalVO) {
    this.consejoProfesionalVO = consejoProfesionalVO;
  }

  public Response contraloriaVO(ResponseContraloriaVO contraloriaVO) {
    this.contraloriaVO = contraloriaVO;
    return this;
  }

   /**
   * Get contraloriaVO
   * @return contraloriaVO
  **/
  @Schema(description = "")
  public ResponseContraloriaVO getContraloriaVO() {
    return contraloriaVO;
  }

  public void setContraloriaVO(ResponseContraloriaVO contraloriaVO) {
    this.contraloriaVO = contraloriaVO;
  }

  public Response copniaVO(ResponseCopniaVO copniaVO) {
    this.copniaVO = copniaVO;
    return this;
  }

   /**
   * Get copniaVO
   * @return copniaVO
  **/
  @Schema(description = "")
  public ResponseCopniaVO getCopniaVO() {
    return copniaVO;
  }

  public void setCopniaVO(ResponseCopniaVO copniaVO) {
    this.copniaVO = copniaVO;
  }

  public Response cpaeVO(ResponseCpaeVO cpaeVO) {
    this.cpaeVO = cpaeVO;
    return this;
  }

   /**
   * Get cpaeVO
   * @return cpaeVO
  **/
  @Schema(description = "")
  public ResponseCpaeVO getCpaeVO() {
    return cpaeVO;
  }

  public void setCpaeVO(ResponseCpaeVO cpaeVO) {
    this.cpaeVO = cpaeVO;
  }

  public Response cpbiolVersionDosVO(ResponseCpbiolVersionDosVO cpbiolVersionDosVO) {
    this.cpbiolVersionDosVO = cpbiolVersionDosVO;
    return this;
  }

   /**
   * Get cpbiolVersionDosVO
   * @return cpbiolVersionDosVO
  **/
  @Schema(description = "")
  public ResponseCpbiolVersionDosVO getCpbiolVersionDosVO() {
    return cpbiolVersionDosVO;
  }

  public void setCpbiolVersionDosVO(ResponseCpbiolVersionDosVO cpbiolVersionDosVO) {
    this.cpbiolVersionDosVO = cpbiolVersionDosVO;
  }

  public Response cpipVO(ResponseCpipVO cpipVO) {
    this.cpipVO = cpipVO;
    return this;
  }

   /**
   * Get cpipVO
   * @return cpipVO
  **/
  @Schema(description = "")
  public ResponseCpipVO getCpipVO() {
    return cpipVO;
  }

  public void setCpipVO(ResponseCpipVO cpipVO) {
    this.cpipVO = cpipVO;
  }

  public Response cpiqVO(ResponseCpiqVO cpiqVO) {
    this.cpiqVO = cpiqVO;
    return this;
  }

   /**
   * Get cpiqVO
   * @return cpiqVO
  **/
  @Schema(description = "")
  public ResponseCpiqVO getCpiqVO() {
    return cpiqVO;
  }

  public void setCpiqVO(ResponseCpiqVO cpiqVO) {
    this.cpiqVO = cpiqVO;
  }

  public Response cpnaaVO(ResponseCpnaaVO cpnaaVO) {
    this.cpnaaVO = cpnaaVO;
    return this;
  }

   /**
   * Get cpnaaVO
   * @return cpnaaVO
  **/
  @Schema(description = "")
  public ResponseCpnaaVO getCpnaaVO() {
    return cpnaaVO;
  }

  public void setCpnaaVO(ResponseCpnaaVO cpnaaVO) {
    this.cpnaaVO = cpnaaVO;
  }

  public Response cpntVO(ResponseCpntVO cpntVO) {
    this.cpntVO = cpntVO;
    return this;
  }

   /**
   * Get cpntVO
   * @return cpntVO
  **/
  @Schema(description = "")
  public ResponseCpntVO getCpntVO() {
    return cpntVO;
  }

  public void setCpntVO(ResponseCpntVO cpntVO) {
    this.cpntVO = cpntVO;
  }

  public Response cufeDianVO(ResponseCufeDianVO cufeDianVO) {
    this.cufeDianVO = cufeDianVO;
    return this;
  }

   /**
   * Get cufeDianVO
   * @return cufeDianVO
  **/
  @Schema(description = "")
  public ResponseCufeDianVO getCufeDianVO() {
    return cufeDianVO;
  }

  public void setCufeDianVO(ResponseCufeDianVO cufeDianVO) {
    this.cufeDianVO = cufeDianVO;
  }

  public Response dianRutVO(ResponseDianRutVO dianRutVO) {
    this.dianRutVO = dianRutVO;
    return this;
  }

   /**
   * Get dianRutVO
   * @return dianRutVO
  **/
  @Schema(description = "")
  public ResponseDianRutVO getDianRutVO() {
    return dianRutVO;
  }

  public void setDianRutVO(ResponseDianRutVO dianRutVO) {
    this.dianRutVO = dianRutVO;
  }

  public Response directorioEmpresasVO(ResponseDirectorioEmpresasVO directorioEmpresasVO) {
    this.directorioEmpresasVO = directorioEmpresasVO;
    return this;
  }

   /**
   * Get directorioEmpresasVO
   * @return directorioEmpresasVO
  **/
  @Schema(description = "")
  public ResponseDirectorioEmpresasVO getDirectorioEmpresasVO() {
    return directorioEmpresasVO;
  }

  public void setDirectorioEmpresasVO(ResponseDirectorioEmpresasVO directorioEmpresasVO) {
    this.directorioEmpresasVO = directorioEmpresasVO;
  }

  public Response einformaVO(ResponseEinformaVO einformaVO) {
    this.einformaVO = einformaVO;
    return this;
  }

   /**
   * Get einformaVO
   * @return einformaVO
  **/
  @Schema(description = "")
  public ResponseEinformaVO getEinformaVO() {
    return einformaVO;
  }

  public void setEinformaVO(ResponseEinformaVO einformaVO) {
    this.einformaVO = einformaVO;
  }

  public Response empresasGoogleVO(ResponseEmpresasGoogleVO empresasGoogleVO) {
    this.empresasGoogleVO = empresasGoogleVO;
    return this;
  }

   /**
   * Get empresasGoogleVO
   * @return empresasGoogleVO
  **/
  @Schema(description = "")
  public ResponseEmpresasGoogleVO getEmpresasGoogleVO() {
    return empresasGoogleVO;
  }

  public void setEmpresasGoogleVO(ResponseEmpresasGoogleVO empresasGoogleVO) {
    this.empresasGoogleVO = empresasGoogleVO;
  }

  public Response estadoCedulaExtranjeriaVO(ResponseEstadoCedulaExtranjeriaVO estadoCedulaExtranjeriaVO) {
    this.estadoCedulaExtranjeriaVO = estadoCedulaExtranjeriaVO;
    return this;
  }

   /**
   * Get estadoCedulaExtranjeriaVO
   * @return estadoCedulaExtranjeriaVO
  **/
  @Schema(description = "")
  public ResponseEstadoCedulaExtranjeriaVO getEstadoCedulaExtranjeriaVO() {
    return estadoCedulaExtranjeriaVO;
  }

  public void setEstadoCedulaExtranjeriaVO(ResponseEstadoCedulaExtranjeriaVO estadoCedulaExtranjeriaVO) {
    this.estadoCedulaExtranjeriaVO = estadoCedulaExtranjeriaVO;
  }

  public Response estadoCedulaVO(ResponseEstadoCedulaVO estadoCedulaVO) {
    this.estadoCedulaVO = estadoCedulaVO;
    return this;
  }

   /**
   * Get estadoCedulaVO
   * @return estadoCedulaVO
  **/
  @Schema(description = "")
  public ResponseEstadoCedulaVO getEstadoCedulaVO() {
    return estadoCedulaVO;
  }

  public void setEstadoCedulaVO(ResponseEstadoCedulaVO estadoCedulaVO) {
    this.estadoCedulaVO = estadoCedulaVO;
  }

  public Response estadoTramiteCedulaVO(ResponseEstadoTramiteCedulaVO estadoTramiteCedulaVO) {
    this.estadoTramiteCedulaVO = estadoTramiteCedulaVO;
    return this;
  }

   /**
   * Get estadoTramiteCedulaVO
   * @return estadoTramiteCedulaVO
  **/
  @Schema(description = "")
  public ResponseEstadoTramiteCedulaVO getEstadoTramiteCedulaVO() {
    return estadoTramiteCedulaVO;
  }

  public void setEstadoTramiteCedulaVO(ResponseEstadoTramiteCedulaVO estadoTramiteCedulaVO) {
    this.estadoTramiteCedulaVO = estadoTramiteCedulaVO;
  }

  public Response fiduprevisoraVO(ResponseFiduprevisoraVO fiduprevisoraVO) {
    this.fiduprevisoraVO = fiduprevisoraVO;
    return this;
  }

   /**
   * Get fiduprevisoraVO
   * @return fiduprevisoraVO
  **/
  @Schema(description = "")
  public ResponseFiduprevisoraVO getFiduprevisoraVO() {
    return fiduprevisoraVO;
  }

  public void setFiduprevisoraVO(ResponseFiduprevisoraVO fiduprevisoraVO) {
    this.fiduprevisoraVO = fiduprevisoraVO;
  }

  public Response fopepVO(ResponseFopepVO fopepVO) {
    this.fopepVO = fopepVO;
    return this;
  }

   /**
   * Get fopepVO
   * @return fopepVO
  **/
  @Schema(description = "")
  public ResponseFopepVO getFopepVO() {
    return fopepVO;
  }

  public void setFopepVO(ResponseFopepVO fopepVO) {
    this.fopepVO = fopepVO;
  }

  public Response garantiasMobiliariasVO(ResponseGarantiasMobiliariasVO garantiasMobiliariasVO) {
    this.garantiasMobiliariasVO = garantiasMobiliariasVO;
    return this;
  }

   /**
   * Get garantiasMobiliariasVO
   * @return garantiasMobiliariasVO
  **/
  @Schema(description = "")
  public ResponseGarantiasMobiliariasVO getGarantiasMobiliariasVO() {
    return garantiasMobiliariasVO;
  }

  public void setGarantiasMobiliariasVO(ResponseGarantiasMobiliariasVO garantiasMobiliariasVO) {
    this.garantiasMobiliariasVO = garantiasMobiliariasVO;
  }

  public Response inpecReclusosVO(ResponseInpecReclusosVO inpecReclusosVO) {
    this.inpecReclusosVO = inpecReclusosVO;
    return this;
  }

   /**
   * Get inpecReclusosVO
   * @return inpecReclusosVO
  **/
  @Schema(description = "")
  public ResponseInpecReclusosVO getInpecReclusosVO() {
    return inpecReclusosVO;
  }

  public void setInpecReclusosVO(ResponseInpecReclusosVO inpecReclusosVO) {
    this.inpecReclusosVO = inpecReclusosVO;
  }

  public Response libretaMilitarVO(ResponseLibretaMilitarVO libretaMilitarVO) {
    this.libretaMilitarVO = libretaMilitarVO;
    return this;
  }

   /**
   * Get libretaMilitarVO
   * @return libretaMilitarVO
  **/
  @Schema(description = "")
  public ResponseLibretaMilitarVO getLibretaMilitarVO() {
    return libretaMilitarVO;
  }

  public void setLibretaMilitarVO(ResponseLibretaMilitarVO libretaMilitarVO) {
    this.libretaMilitarVO = libretaMilitarVO;
  }

  public Response miCasaYaVO(ResponseMiCasaYaVO miCasaYaVO) {
    this.miCasaYaVO = miCasaYaVO;
    return this;
  }

   /**
   * Get miCasaYaVO
   * @return miCasaYaVO
  **/
  @Schema(description = "")
  public ResponseMiCasaYaVO getMiCasaYaVO() {
    return miCasaYaVO;
  }

  public void setMiCasaYaVO(ResponseMiCasaYaVO miCasaYaVO) {
    this.miCasaYaVO = miCasaYaVO;
  }

  public Response migracionColombiaVO(ResponseMigracionColombiaVO migracionColombiaVO) {
    this.migracionColombiaVO = migracionColombiaVO;
    return this;
  }

   /**
   * Get migracionColombiaVO
   * @return migracionColombiaVO
  **/
  @Schema(description = "")
  public ResponseMigracionColombiaVO getMigracionColombiaVO() {
    return migracionColombiaVO;
  }

  public void setMigracionColombiaVO(ResponseMigracionColombiaVO migracionColombiaVO) {
    this.migracionColombiaVO = migracionColombiaVO;
  }

  public Response migracionPptVO(ResponseMigracionPptVO migracionPptVO) {
    this.migracionPptVO = migracionPptVO;
    return this;
  }

   /**
   * Get migracionPptVO
   * @return migracionPptVO
  **/
  @Schema(description = "")
  public ResponseMigracionPptVO getMigracionPptVO() {
    return migracionPptVO;
  }

  public void setMigracionPptVO(ResponseMigracionPptVO migracionPptVO) {
    this.migracionPptVO = migracionPptVO;
  }

  public Response nombreCompletoIntegralVO(ResponseNombreCompletoIntegralVO nombreCompletoIntegralVO) {
    this.nombreCompletoIntegralVO = nombreCompletoIntegralVO;
    return this;
  }

   /**
   * Get nombreCompletoIntegralVO
   * @return nombreCompletoIntegralVO
  **/
  @Schema(description = "")
  public ResponseNombreCompletoIntegralVO getNombreCompletoIntegralVO() {
    return nombreCompletoIntegralVO;
  }

  public void setNombreCompletoIntegralVO(ResponseNombreCompletoIntegralVO nombreCompletoIntegralVO) {
    this.nombreCompletoIntegralVO = nombreCompletoIntegralVO;
  }

  public Response nombreCompletoVO(ResponseNombreCompletoVO nombreCompletoVO) {
    this.nombreCompletoVO = nombreCompletoVO;
    return this;
  }

   /**
   * Get nombreCompletoVO
   * @return nombreCompletoVO
  **/
  @Schema(description = "")
  public ResponseNombreCompletoVO getNombreCompletoVO() {
    return nombreCompletoVO;
  }

  public void setNombreCompletoVO(ResponseNombreCompletoVO nombreCompletoVO) {
    this.nombreCompletoVO = nombreCompletoVO;
  }

  public Response ofacVO(ResponseOfacVO ofacVO) {
    this.ofacVO = ofacVO;
    return this;
  }

   /**
   * Get ofacVO
   * @return ofacVO
  **/
  @Schema(description = "")
  public ResponseOfacVO getOfacVO() {
    return ofacVO;
  }

  public void setOfacVO(ResponseOfacVO ofacVO) {
    this.ofacVO = ofacVO;
  }

  public Response onuVO(ResponseOnuVO onuVO) {
    this.onuVO = onuVO;
    return this;
  }

   /**
   * Get onuVO
   * @return onuVO
  **/
  @Schema(description = "")
  public ResponseOnuVO getOnuVO() {
    return onuVO;
  }

  public void setOnuVO(ResponseOnuVO onuVO) {
    this.onuVO = onuVO;
  }

  public Response pagoSnrVO(ResponsePagoSnrVO pagoSnrVO) {
    this.pagoSnrVO = pagoSnrVO;
    return this;
  }

   /**
   * Get pagoSnrVO
   * @return pagoSnrVO
  **/
  @Schema(description = "")
  public ResponsePagoSnrVO getPagoSnrVO() {
    return pagoSnrVO;
  }

  public void setPagoSnrVO(ResponsePagoSnrVO pagoSnrVO) {
    this.pagoSnrVO = pagoSnrVO;
  }

  public Response pepVO(ResponsePepVO pepVO) {
    this.pepVO = pepVO;
    return this;
  }

   /**
   * Get pepVO
   * @return pepVO
  **/
  @Schema(description = "")
  public ResponsePepVO getPepVO() {
    return pepVO;
  }

  public void setPepVO(ResponsePepVO pepVO) {
    this.pepVO = pepVO;
  }

  public Response personeriaBogotaVO(ResponsePersoneriaBogotaVO personeriaBogotaVO) {
    this.personeriaBogotaVO = personeriaBogotaVO;
    return this;
  }

   /**
   * Get personeriaBogotaVO
   * @return personeriaBogotaVO
  **/
  @Schema(description = "")
  public ResponsePersoneriaBogotaVO getPersoneriaBogotaVO() {
    return personeriaBogotaVO;
  }

  public void setPersoneriaBogotaVO(ResponsePersoneriaBogotaVO personeriaBogotaVO) {
    this.personeriaBogotaVO = personeriaBogotaVO;
  }

  public Response procuraduriaVO(ResponseProcuraduriaVO procuraduriaVO) {
    this.procuraduriaVO = procuraduriaVO;
    return this;
  }

   /**
   * Get procuraduriaVO
   * @return procuraduriaVO
  **/
  @Schema(description = "")
  public ResponseProcuraduriaVO getProcuraduriaVO() {
    return procuraduriaVO;
  }

  public void setProcuraduriaVO(ResponseProcuraduriaVO procuraduriaVO) {
    this.procuraduriaVO = procuraduriaVO;
  }

  public Response proveedoresFicticiosVO(ResponseProveedoresFicticiosVO proveedoresFicticiosVO) {
    this.proveedoresFicticiosVO = proveedoresFicticiosVO;
    return this;
  }

   /**
   * Get proveedoresFicticiosVO
   * @return proveedoresFicticiosVO
  **/
  @Schema(description = "")
  public ResponseProveedoresFicticiosVO getProveedoresFicticiosVO() {
    return proveedoresFicticiosVO;
  }

  public void setProveedoresFicticiosVO(ResponseProveedoresFicticiosVO proveedoresFicticiosVO) {
    this.proveedoresFicticiosVO = proveedoresFicticiosVO;
  }

  public Response puestoVotacionVO(ResponsePuestoVotacionVO puestoVotacionVO) {
    this.puestoVotacionVO = puestoVotacionVO;
    return this;
  }

   /**
   * Get puestoVotacionVO
   * @return puestoVotacionVO
  **/
  @Schema(description = "")
  public ResponsePuestoVotacionVO getPuestoVotacionVO() {
    return puestoVotacionVO;
  }

  public void setPuestoVotacionVO(ResponsePuestoVotacionVO puestoVotacionVO) {
    this.puestoVotacionVO = puestoVotacionVO;
  }

  public Response retencionVehiculosVO(ResponseRetencionVehiculosVO retencionVehiculosVO) {
    this.retencionVehiculosVO = retencionVehiculosVO;
    return this;
  }

   /**
   * Get retencionVehiculosVO
   * @return retencionVehiculosVO
  **/
  @Schema(description = "")
  public ResponseRetencionVehiculosVO getRetencionVehiculosVO() {
    return retencionVehiculosVO;
  }

  public void setRetencionVehiculosVO(ResponseRetencionVehiculosVO retencionVehiculosVO) {
    this.retencionVehiculosVO = retencionVehiculosVO;
  }

  public Response rethusVO(ResponseRethusVO rethusVO) {
    this.rethusVO = rethusVO;
    return this;
  }

   /**
   * Get rethusVO
   * @return rethusVO
  **/
  @Schema(description = "")
  public ResponseRethusVO getRethusVO() {
    return rethusVO;
  }

  public void setRethusVO(ResponseRethusVO rethusVO) {
    this.rethusVO = rethusVO;
  }

  public Response rneVO(ResponseRneVO rneVO) {
    this.rneVO = rneVO;
    return this;
  }

   /**
   * Get rneVO
   * @return rneVO
  **/
  @Schema(description = "")
  public ResponseRneVO getRneVO() {
    return rneVO;
  }

  public void setRneVO(ResponseRneVO rneVO) {
    this.rneVO = rneVO;
  }

  public Response rnmcVO(ResponseRnmcVO rnmcVO) {
    this.rnmcVO = rnmcVO;
    return this;
  }

   /**
   * Get rnmcVO
   * @return rnmcVO
  **/
  @Schema(description = "")
  public ResponseRnmcVO getRnmcVO() {
    return rnmcVO;
  }

  public void setRnmcVO(ResponseRnmcVO rnmcVO) {
    this.rnmcVO = rnmcVO;
  }

  public Response rntVO(ResponseRntVO rntVO) {
    this.rntVO = rntVO;
    return this;
  }

   /**
   * Get rntVO
   * @return rntVO
  **/
  @Schema(description = "")
  public ResponseRntVO getRntVO() {
    return rntVO;
  }

  public void setRntVO(ResponseRntVO rntVO) {
    this.rntVO = rntVO;
  }

  public Response ruafVO(ResponseRuafVO ruafVO) {
    this.ruafVO = ruafVO;
    return this;
  }

   /**
   * Get ruafVO
   * @return ruafVO
  **/
  @Schema(description = "")
  public ResponseRuafVO getRuafVO() {
    return ruafVO;
  }

  public void setRuafVO(ResponseRuafVO ruafVO) {
    this.ruafVO = ruafVO;
  }

  public Response ruesCamaraEmpresarialVO(ResponseRuesCamaraEmpresarialVO ruesCamaraEmpresarialVO) {
    this.ruesCamaraEmpresarialVO = ruesCamaraEmpresarialVO;
    return this;
  }

   /**
   * Get ruesCamaraEmpresarialVO
   * @return ruesCamaraEmpresarialVO
  **/
  @Schema(description = "")
  public ResponseRuesCamaraEmpresarialVO getRuesCamaraEmpresarialVO() {
    return ruesCamaraEmpresarialVO;
  }

  public void setRuesCamaraEmpresarialVO(ResponseRuesCamaraEmpresarialVO ruesCamaraEmpresarialVO) {
    this.ruesCamaraEmpresarialVO = ruesCamaraEmpresarialVO;
  }

  public Response ruesCamaraUnificadoVO(ResponseRuesCamaraUnificadoVO ruesCamaraUnificadoVO) {
    this.ruesCamaraUnificadoVO = ruesCamaraUnificadoVO;
    return this;
  }

   /**
   * Get ruesCamaraUnificadoVO
   * @return ruesCamaraUnificadoVO
  **/
  @Schema(description = "")
  public ResponseRuesCamaraUnificadoVO getRuesCamaraUnificadoVO() {
    return ruesCamaraUnificadoVO;
  }

  public void setRuesCamaraUnificadoVO(ResponseRuesCamaraUnificadoVO ruesCamaraUnificadoVO) {
    this.ruesCamaraUnificadoVO = ruesCamaraUnificadoVO;
  }

  public Response runtPlacaVO(ResponseRuntPlacaVO runtPlacaVO) {
    this.runtPlacaVO = runtPlacaVO;
    return this;
  }

   /**
   * Get runtPlacaVO
   * @return runtPlacaVO
  **/
  @Schema(description = "")
  public ResponseRuntPlacaVO getRuntPlacaVO() {
    return runtPlacaVO;
  }

  public void setRuntPlacaVO(ResponseRuntPlacaVO runtPlacaVO) {
    this.runtPlacaVO = runtPlacaVO;
  }

  public Response runtVO(ResponseRuntVO runtVO) {
    this.runtVO = runtVO;
    return this;
  }

   /**
   * Get runtVO
   * @return runtVO
  **/
  @Schema(description = "")
  public ResponseRuntVO getRuntVO() {
    return runtVO;
  }

  public void setRuntVO(ResponseRuntVO runtVO) {
    this.runtVO = runtVO;
  }

  public Response secopVO(ResponseSecopVO secopVO) {
    this.secopVO = secopVO;
    return this;
  }

   /**
   * Get secopVO
   * @return secopVO
  **/
  @Schema(description = "")
  public ResponseSecopVO getSecopVO() {
    return secopVO;
  }

  public void setSecopVO(ResponseSecopVO secopVO) {
    this.secopVO = secopVO;
  }

  public Response seguridadSocialVO(ResponseSeguridadSocialVO seguridadSocialVO) {
    this.seguridadSocialVO = seguridadSocialVO;
    return this;
  }

   /**
   * Get seguridadSocialVO
   * @return seguridadSocialVO
  **/
  @Schema(description = "")
  public ResponseSeguridadSocialVO getSeguridadSocialVO() {
    return seguridadSocialVO;
  }

  public void setSeguridadSocialVO(ResponseSeguridadSocialVO seguridadSocialVO) {
    this.seguridadSocialVO = seguridadSocialVO;
  }

  public Response servicioNuevoSoiVO(ResponseServicioNuevoSoiVO servicioNuevoSoiVO) {
    this.servicioNuevoSoiVO = servicioNuevoSoiVO;
    return this;
  }

   /**
   * Get servicioNuevoSoiVO
   * @return servicioNuevoSoiVO
  **/
  @Schema(description = "")
  public ResponseServicioNuevoSoiVO getServicioNuevoSoiVO() {
    return servicioNuevoSoiVO;
  }

  public void setServicioNuevoSoiVO(ResponseServicioNuevoSoiVO servicioNuevoSoiVO) {
    this.servicioNuevoSoiVO = servicioNuevoSoiVO;
  }

  public Response simitVO(ResponseSimitVO simitVO) {
    this.simitVO = simitVO;
    return this;
  }

   /**
   * Get simitVO
   * @return simitVO
  **/
  @Schema(description = "")
  public ResponseSimitVO getSimitVO() {
    return simitVO;
  }

  public void setSimitVO(ResponseSimitVO simitVO) {
    this.simitVO = simitVO;
  }

  public Response sisbenGruposVO(ResponseSisbenGruposVO sisbenGruposVO) {
    this.sisbenGruposVO = sisbenGruposVO;
    return this;
  }

   /**
   * Get sisbenGruposVO
   * @return sisbenGruposVO
  **/
  @Schema(description = "")
  public ResponseSisbenGruposVO getSisbenGruposVO() {
    return sisbenGruposVO;
  }

  public void setSisbenGruposVO(ResponseSisbenGruposVO sisbenGruposVO) {
    this.sisbenGruposVO = sisbenGruposVO;
  }

  public Response urnaVO(ResponseUrnaVO urnaVO) {
    this.urnaVO = urnaVO;
    return this;
  }

   /**
   * Get urnaVO
   * @return urnaVO
  **/
  @Schema(description = "")
  public ResponseUrnaVO getUrnaVO() {
    return urnaVO;
  }

  public void setUrnaVO(ResponseUrnaVO urnaVO) {
    this.urnaVO = urnaVO;
  }

  public Response veterinarioVO(ResponseVeterinarioVO veterinarioVO) {
    this.veterinarioVO = veterinarioVO;
    return this;
  }

   /**
   * Get veterinarioVO
   * @return veterinarioVO
  **/
  @Schema(description = "")
  public ResponseVeterinarioVO getVeterinarioVO() {
    return veterinarioVO;
  }

  public void setVeterinarioVO(ResponseVeterinarioVO veterinarioVO) {
    this.veterinarioVO = veterinarioVO;
  }

  public Response senescytVO(ResponseSenescytVO senescytVO) {
    this.senescytVO = senescytVO;
    return this;
  }

   /**
   * Get senescytVO
   * @return senescytVO
  **/
  @Schema(description = "")
  public ResponseSenescytVO getSenescytVO() {
    return senescytVO;
  }

  public void setSenescytVO(ResponseSenescytVO senescytVO) {
    this.senescytVO = senescytVO;
  }

  public Response cmpVO(ResponseCmpVO cmpVO) {
    this.cmpVO = cmpVO;
    return this;
  }

   /**
   * Get cmpVO
   * @return cmpVO
  **/
  @Schema(description = "")
  public ResponseCmpVO getCmpVO() {
    return cmpVO;
  }

  public void setCmpVO(ResponseCmpVO cmpVO) {
    this.cmpVO = cmpVO;
  }

  public Response profesionalSaludVO(ResponseProfesionalSaludVO profesionalSaludVO) {
    this.profesionalSaludVO = profesionalSaludVO;
    return this;
  }

   /**
   * Get profesionalSaludVO
   * @return profesionalSaludVO
  **/
  @Schema(description = "")
  public ResponseProfesionalSaludVO getProfesionalSaludVO() {
    return profesionalSaludVO;
  }

  public void setProfesionalSaludVO(ResponseProfesionalSaludVO profesionalSaludVO) {
    this.profesionalSaludVO = profesionalSaludVO;
  }

  public Response sarenVO(ResponseSarenVO sarenVO) {
    this.sarenVO = sarenVO;
    return this;
  }

   /**
   * Get sarenVO
   * @return sarenVO
  **/
  @Schema(description = "")
  public ResponseSarenVO getSarenVO() {
    return sarenVO;
  }

  public void setSarenVO(ResponseSarenVO sarenVO) {
    this.sarenVO = sarenVO;
  }

  public Response seniatVO(ResponseSeniatVO seniatVO) {
    this.seniatVO = seniatVO;
    return this;
  }

   /**
   * Get seniatVO
   * @return seniatVO
  **/
  @Schema(description = "")
  public ResponseSeniatVO getSeniatVO() {
    return seniatVO;
  }

  public void setSeniatVO(ResponseSeniatVO seniatVO) {
    this.seniatVO = seniatVO;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Response response = (Response) o;
    return Objects.equals(this.rcVigenciaDocumentoVO, response.rcVigenciaDocumentoVO) &&
        Objects.equals(this.afiliadosCompensadoVO, response.afiliadosCompensadoVO) &&
        Objects.equals(this.antecedentesPoliciaVO, response.antecedentesPoliciaVO) &&
        Objects.equals(this.antecedentesRamaVO, response.antecedentesRamaVO) &&
        Objects.equals(this.antecedentesBDUAVO, response.antecedentesBDUAVO) &&
        Objects.equals(this.camaraComercioMedellinVO, response.camaraComercioMedellinVO) &&
        Objects.equals(this.cambioEstratoBgaVO, response.cambioEstratoBgaVO) &&
        Objects.equals(this.certificadoRegistroCivilVO, response.certificadoRegistroCivilVO) &&
        Objects.equals(this.certificadoSnrVO, response.certificadoSnrVO) &&
        Objects.equals(this.colpensionesVO, response.colpensionesVO) &&
        Objects.equals(this.conaltelVO, response.conaltelVO) &&
        Objects.equals(this.consejoProfesionalVO, response.consejoProfesionalVO) &&
        Objects.equals(this.contraloriaVO, response.contraloriaVO) &&
        Objects.equals(this.copniaVO, response.copniaVO) &&
        Objects.equals(this.cpaeVO, response.cpaeVO) &&
        Objects.equals(this.cpbiolVersionDosVO, response.cpbiolVersionDosVO) &&
        Objects.equals(this.cpipVO, response.cpipVO) &&
        Objects.equals(this.cpiqVO, response.cpiqVO) &&
        Objects.equals(this.cpnaaVO, response.cpnaaVO) &&
        Objects.equals(this.cpntVO, response.cpntVO) &&
        Objects.equals(this.cufeDianVO, response.cufeDianVO) &&
        Objects.equals(this.dianRutVO, response.dianRutVO) &&
        Objects.equals(this.directorioEmpresasVO, response.directorioEmpresasVO) &&
        Objects.equals(this.einformaVO, response.einformaVO) &&
        Objects.equals(this.empresasGoogleVO, response.empresasGoogleVO) &&
        Objects.equals(this.estadoCedulaExtranjeriaVO, response.estadoCedulaExtranjeriaVO) &&
        Objects.equals(this.estadoCedulaVO, response.estadoCedulaVO) &&
        Objects.equals(this.estadoTramiteCedulaVO, response.estadoTramiteCedulaVO) &&
        Objects.equals(this.fiduprevisoraVO, response.fiduprevisoraVO) &&
        Objects.equals(this.fopepVO, response.fopepVO) &&
        Objects.equals(this.garantiasMobiliariasVO, response.garantiasMobiliariasVO) &&
        Objects.equals(this.inpecReclusosVO, response.inpecReclusosVO) &&
        Objects.equals(this.libretaMilitarVO, response.libretaMilitarVO) &&
        Objects.equals(this.miCasaYaVO, response.miCasaYaVO) &&
        Objects.equals(this.migracionColombiaVO, response.migracionColombiaVO) &&
        Objects.equals(this.migracionPptVO, response.migracionPptVO) &&
        Objects.equals(this.nombreCompletoIntegralVO, response.nombreCompletoIntegralVO) &&
        Objects.equals(this.nombreCompletoVO, response.nombreCompletoVO) &&
        Objects.equals(this.ofacVO, response.ofacVO) &&
        Objects.equals(this.onuVO, response.onuVO) &&
        Objects.equals(this.pagoSnrVO, response.pagoSnrVO) &&
        Objects.equals(this.pepVO, response.pepVO) &&
        Objects.equals(this.personeriaBogotaVO, response.personeriaBogotaVO) &&
        Objects.equals(this.procuraduriaVO, response.procuraduriaVO) &&
        Objects.equals(this.proveedoresFicticiosVO, response.proveedoresFicticiosVO) &&
        Objects.equals(this.puestoVotacionVO, response.puestoVotacionVO) &&
        Objects.equals(this.retencionVehiculosVO, response.retencionVehiculosVO) &&
        Objects.equals(this.rethusVO, response.rethusVO) &&
        Objects.equals(this.rneVO, response.rneVO) &&
        Objects.equals(this.rnmcVO, response.rnmcVO) &&
        Objects.equals(this.rntVO, response.rntVO) &&
        Objects.equals(this.ruafVO, response.ruafVO) &&
        Objects.equals(this.ruesCamaraEmpresarialVO, response.ruesCamaraEmpresarialVO) &&
        Objects.equals(this.ruesCamaraUnificadoVO, response.ruesCamaraUnificadoVO) &&
        Objects.equals(this.runtPlacaVO, response.runtPlacaVO) &&
        Objects.equals(this.runtVO, response.runtVO) &&
        Objects.equals(this.secopVO, response.secopVO) &&
        Objects.equals(this.seguridadSocialVO, response.seguridadSocialVO) &&
        Objects.equals(this.servicioNuevoSoiVO, response.servicioNuevoSoiVO) &&
        Objects.equals(this.simitVO, response.simitVO) &&
        Objects.equals(this.sisbenGruposVO, response.sisbenGruposVO) &&
        Objects.equals(this.urnaVO, response.urnaVO) &&
        Objects.equals(this.veterinarioVO, response.veterinarioVO) &&
        Objects.equals(this.senescytVO, response.senescytVO) &&
        Objects.equals(this.cmpVO, response.cmpVO) &&
        Objects.equals(this.profesionalSaludVO, response.profesionalSaludVO) &&
        Objects.equals(this.sarenVO, response.sarenVO) &&
        Objects.equals(this.seniatVO, response.seniatVO);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rcVigenciaDocumentoVO, afiliadosCompensadoVO, antecedentesPoliciaVO, antecedentesRamaVO, antecedentesBDUAVO, camaraComercioMedellinVO, cambioEstratoBgaVO, certificadoRegistroCivilVO, certificadoSnrVO, colpensionesVO, conaltelVO, consejoProfesionalVO, contraloriaVO, copniaVO, cpaeVO, cpbiolVersionDosVO, cpipVO, cpiqVO, cpnaaVO, cpntVO, cufeDianVO, dianRutVO, directorioEmpresasVO, einformaVO, empresasGoogleVO, estadoCedulaExtranjeriaVO, estadoCedulaVO, estadoTramiteCedulaVO, fiduprevisoraVO, fopepVO, garantiasMobiliariasVO, inpecReclusosVO, libretaMilitarVO, miCasaYaVO, migracionColombiaVO, migracionPptVO, nombreCompletoIntegralVO, nombreCompletoVO, ofacVO, onuVO, pagoSnrVO, pepVO, personeriaBogotaVO, procuraduriaVO, proveedoresFicticiosVO, puestoVotacionVO, retencionVehiculosVO, rethusVO, rneVO, rnmcVO, rntVO, ruafVO, ruesCamaraEmpresarialVO, ruesCamaraUnificadoVO, runtPlacaVO, runtVO, secopVO, seguridadSocialVO, servicioNuevoSoiVO, simitVO, sisbenGruposVO, urnaVO, veterinarioVO, senescytVO, cmpVO, profesionalSaludVO, sarenVO, seniatVO);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Response {\n");
    
    sb.append("    rcVigenciaDocumentoVO: ").append(toIndentedString(rcVigenciaDocumentoVO)).append("\n");
    sb.append("    afiliadosCompensadoVO: ").append(toIndentedString(afiliadosCompensadoVO)).append("\n");
    sb.append("    antecedentesPoliciaVO: ").append(toIndentedString(antecedentesPoliciaVO)).append("\n");
    sb.append("    antecedentesRamaVO: ").append(toIndentedString(antecedentesRamaVO)).append("\n");
    sb.append("    antecedentesBDUAVO: ").append(toIndentedString(antecedentesBDUAVO)).append("\n");
    sb.append("    camaraComercioMedellinVO: ").append(toIndentedString(camaraComercioMedellinVO)).append("\n");
    sb.append("    cambioEstratoBgaVO: ").append(toIndentedString(cambioEstratoBgaVO)).append("\n");
    sb.append("    certificadoRegistroCivilVO: ").append(toIndentedString(certificadoRegistroCivilVO)).append("\n");
    sb.append("    certificadoSnrVO: ").append(toIndentedString(certificadoSnrVO)).append("\n");
    sb.append("    colpensionesVO: ").append(toIndentedString(colpensionesVO)).append("\n");
    sb.append("    conaltelVO: ").append(toIndentedString(conaltelVO)).append("\n");
    sb.append("    consejoProfesionalVO: ").append(toIndentedString(consejoProfesionalVO)).append("\n");
    sb.append("    contraloriaVO: ").append(toIndentedString(contraloriaVO)).append("\n");
    sb.append("    copniaVO: ").append(toIndentedString(copniaVO)).append("\n");
    sb.append("    cpaeVO: ").append(toIndentedString(cpaeVO)).append("\n");
    sb.append("    cpbiolVersionDosVO: ").append(toIndentedString(cpbiolVersionDosVO)).append("\n");
    sb.append("    cpipVO: ").append(toIndentedString(cpipVO)).append("\n");
    sb.append("    cpiqVO: ").append(toIndentedString(cpiqVO)).append("\n");
    sb.append("    cpnaaVO: ").append(toIndentedString(cpnaaVO)).append("\n");
    sb.append("    cpntVO: ").append(toIndentedString(cpntVO)).append("\n");
    sb.append("    cufeDianVO: ").append(toIndentedString(cufeDianVO)).append("\n");
    sb.append("    dianRutVO: ").append(toIndentedString(dianRutVO)).append("\n");
    sb.append("    directorioEmpresasVO: ").append(toIndentedString(directorioEmpresasVO)).append("\n");
    sb.append("    einformaVO: ").append(toIndentedString(einformaVO)).append("\n");
    sb.append("    empresasGoogleVO: ").append(toIndentedString(empresasGoogleVO)).append("\n");
    sb.append("    estadoCedulaExtranjeriaVO: ").append(toIndentedString(estadoCedulaExtranjeriaVO)).append("\n");
    sb.append("    estadoCedulaVO: ").append(toIndentedString(estadoCedulaVO)).append("\n");
    sb.append("    estadoTramiteCedulaVO: ").append(toIndentedString(estadoTramiteCedulaVO)).append("\n");
    sb.append("    fiduprevisoraVO: ").append(toIndentedString(fiduprevisoraVO)).append("\n");
    sb.append("    fopepVO: ").append(toIndentedString(fopepVO)).append("\n");
    sb.append("    garantiasMobiliariasVO: ").append(toIndentedString(garantiasMobiliariasVO)).append("\n");
    sb.append("    inpecReclusosVO: ").append(toIndentedString(inpecReclusosVO)).append("\n");
    sb.append("    libretaMilitarVO: ").append(toIndentedString(libretaMilitarVO)).append("\n");
    sb.append("    miCasaYaVO: ").append(toIndentedString(miCasaYaVO)).append("\n");
    sb.append("    migracionColombiaVO: ").append(toIndentedString(migracionColombiaVO)).append("\n");
    sb.append("    migracionPptVO: ").append(toIndentedString(migracionPptVO)).append("\n");
    sb.append("    nombreCompletoIntegralVO: ").append(toIndentedString(nombreCompletoIntegralVO)).append("\n");
    sb.append("    nombreCompletoVO: ").append(toIndentedString(nombreCompletoVO)).append("\n");
    sb.append("    ofacVO: ").append(toIndentedString(ofacVO)).append("\n");
    sb.append("    onuVO: ").append(toIndentedString(onuVO)).append("\n");
    sb.append("    pagoSnrVO: ").append(toIndentedString(pagoSnrVO)).append("\n");
    sb.append("    pepVO: ").append(toIndentedString(pepVO)).append("\n");
    sb.append("    personeriaBogotaVO: ").append(toIndentedString(personeriaBogotaVO)).append("\n");
    sb.append("    procuraduriaVO: ").append(toIndentedString(procuraduriaVO)).append("\n");
    sb.append("    proveedoresFicticiosVO: ").append(toIndentedString(proveedoresFicticiosVO)).append("\n");
    sb.append("    puestoVotacionVO: ").append(toIndentedString(puestoVotacionVO)).append("\n");
    sb.append("    retencionVehiculosVO: ").append(toIndentedString(retencionVehiculosVO)).append("\n");
    sb.append("    rethusVO: ").append(toIndentedString(rethusVO)).append("\n");
    sb.append("    rneVO: ").append(toIndentedString(rneVO)).append("\n");
    sb.append("    rnmcVO: ").append(toIndentedString(rnmcVO)).append("\n");
    sb.append("    rntVO: ").append(toIndentedString(rntVO)).append("\n");
    sb.append("    ruafVO: ").append(toIndentedString(ruafVO)).append("\n");
    sb.append("    ruesCamaraEmpresarialVO: ").append(toIndentedString(ruesCamaraEmpresarialVO)).append("\n");
    sb.append("    ruesCamaraUnificadoVO: ").append(toIndentedString(ruesCamaraUnificadoVO)).append("\n");
    sb.append("    runtPlacaVO: ").append(toIndentedString(runtPlacaVO)).append("\n");
    sb.append("    runtVO: ").append(toIndentedString(runtVO)).append("\n");
    sb.append("    secopVO: ").append(toIndentedString(secopVO)).append("\n");
    sb.append("    seguridadSocialVO: ").append(toIndentedString(seguridadSocialVO)).append("\n");
    sb.append("    servicioNuevoSoiVO: ").append(toIndentedString(servicioNuevoSoiVO)).append("\n");
    sb.append("    simitVO: ").append(toIndentedString(simitVO)).append("\n");
    sb.append("    sisbenGruposVO: ").append(toIndentedString(sisbenGruposVO)).append("\n");
    sb.append("    urnaVO: ").append(toIndentedString(urnaVO)).append("\n");
    sb.append("    veterinarioVO: ").append(toIndentedString(veterinarioVO)).append("\n");
    sb.append("    senescytVO: ").append(toIndentedString(senescytVO)).append("\n");
    sb.append("    cmpVO: ").append(toIndentedString(cmpVO)).append("\n");
    sb.append("    profesionalSaludVO: ").append(toIndentedString(profesionalSaludVO)).append("\n");
    sb.append("    sarenVO: ").append(toIndentedString(sarenVO)).append("\n");
    sb.append("    seniatVO: ").append(toIndentedString(seniatVO)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
