/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseCufeDianVOListEventosFactura;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Colombia -  87944111 - Factura electrónica Dian
 */
@Schema(description = "Colombia -  87944111 - Factura electrónica Dian")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseCufeDianVO {
  @SerializedName("cufe")
  private String cufe = null;

  @SerializedName("listEventosFactura")
  private List<ResponseCufeDianVOListEventosFactura> listEventosFactura = new ArrayList<ResponseCufeDianVOListEventosFactura>();

  @SerializedName("estado")
  private String estado = null;

  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  /**
   * Indica si la fuente falló en la consulta.
   */
  @JsonAdapter(FuenteFalloEnum.Adapter.class)
  public enum FuenteFalloEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    FuenteFalloEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FuenteFalloEnum fromValue(String input) {
      for (FuenteFalloEnum b : FuenteFalloEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FuenteFalloEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FuenteFalloEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public FuenteFalloEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return FuenteFalloEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("fuenteFallo")
  private FuenteFalloEnum fuenteFallo = null;

  public ResponseCufeDianVO cufe(String cufe) {
    this.cufe = cufe;
    return this;
  }

   /**
   * Código Único de Factura Electrónica (CUFE).
   * @return cufe
  **/
  @Schema(example = "001a4bd2d79e72ba07e839900513f51a6aaacaf0167e3f00e3a69e292fdb4cd1000ea6c2a88fbc28e27e7201b3005b35", required = true, description = "Código Único de Factura Electrónica (CUFE).")
  public String getCufe() {
    return cufe;
  }

  public void setCufe(String cufe) {
    this.cufe = cufe;
  }

  public ResponseCufeDianVO listEventosFactura(List<ResponseCufeDianVOListEventosFactura> listEventosFactura) {
    this.listEventosFactura = listEventosFactura;
    return this;
  }

  public ResponseCufeDianVO addListEventosFacturaItem(ResponseCufeDianVOListEventosFactura listEventosFacturaItem) {
    this.listEventosFactura.add(listEventosFacturaItem);
    return this;
  }

   /**
   * Listado de eventos asociados a la factura electrónica.
   * @return listEventosFactura
  **/
  @Schema(required = true, description = "Listado de eventos asociados a la factura electrónica.")
  public List<ResponseCufeDianVOListEventosFactura> getListEventosFactura() {
    return listEventosFactura;
  }

  public void setListEventosFactura(List<ResponseCufeDianVOListEventosFactura> listEventosFactura) {
    this.listEventosFactura = listEventosFactura;
  }

  public ResponseCufeDianVO estado(String estado) {
    this.estado = estado;
    return this;
  }

   /**
   * Estado general de la consulta del CUFE.
   * @return estado
  **/
  @Schema(required = true, description = "Estado general de la consulta del CUFE.")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public ResponseCufeDianVO fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Get fechaConsulta
   * @return fechaConsulta
  **/
  @Schema(required = true, description = "")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public ResponseCufeDianVO fuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
    return this;
  }

   /**
   * Indica si la fuente falló en la consulta.
   * @return fuenteFallo
  **/
  @Schema(example = "NO", required = true, description = "Indica si la fuente falló en la consulta.")
  public FuenteFalloEnum getFuenteFallo() {
    return fuenteFallo;
  }

  public void setFuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseCufeDianVO responseCufeDianVO = (ResponseCufeDianVO) o;
    return Objects.equals(this.cufe, responseCufeDianVO.cufe) &&
        Objects.equals(this.listEventosFactura, responseCufeDianVO.listEventosFactura) &&
        Objects.equals(this.estado, responseCufeDianVO.estado) &&
        Objects.equals(this.fechaConsulta, responseCufeDianVO.fechaConsulta) &&
        Objects.equals(this.fuenteFallo, responseCufeDianVO.fuenteFallo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cufe, listEventosFactura, estado, fechaConsulta, fuenteFallo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseCufeDianVO {\n");
    
    sb.append("    cufe: ").append(toIndentedString(cufe)).append("\n");
    sb.append("    listEventosFactura: ").append(toIndentedString(listEventosFactura)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    fuenteFallo: ").append(toIndentedString(fuenteFallo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
