/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PersonaVO;
import io.swagger.client.model.ResponseRnmcVOListMedidasCorrectivases;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Colombia -  85453412 - Consulta del Registro Nacional de Medidas Correctivas RNMC. Incluye los campos de localidad, relato y descargos.
 */
@Schema(description = "Colombia -  85453412 - Consulta del Registro Nacional de Medidas Correctivas RNMC. Incluye los campos de localidad, relato y descargos.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRnmcVO {
  @SerializedName("personaVO")
  private PersonaVO personaVO = null;

  @SerializedName("estado")
  private String estado = null;

  @SerializedName("expediente")
  private String expediente = null;

  @SerializedName("formato")
  private String formato = null;

  @SerializedName("fecha")
  private String fecha = null;

  @SerializedName("departamento")
  private String departamento = null;

  @SerializedName("municipio")
  private String municipio = null;

  @SerializedName("articulo")
  private String articulo = null;

  @SerializedName("numeral")
  private String numeral = null;

  @SerializedName("literal")
  private String literal = null;

  /**
   * Indica si el registro está en apelación.
   */
  @JsonAdapter(ApelacionEnum.Adapter.class)
  public enum ApelacionEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    ApelacionEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ApelacionEnum fromValue(String input) {
      for (ApelacionEnum b : ApelacionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ApelacionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ApelacionEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public ApelacionEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return ApelacionEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("apelacion")
  private ApelacionEnum apelacion = null;

  @SerializedName("localidad")
  private String localidad = null;

  @SerializedName("relato")
  private String relato = null;

  @SerializedName("descargos")
  private String descargos = null;

  @SerializedName("listMedidasCorrectivases")
  private List<ResponseRnmcVOListMedidasCorrectivases> listMedidasCorrectivases = new ArrayList<ResponseRnmcVOListMedidasCorrectivases>();

  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  /**
   * Indica si la fuente falló en la consulta.
   */
  @JsonAdapter(FuenteFalloEnum.Adapter.class)
  public enum FuenteFalloEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    FuenteFalloEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FuenteFalloEnum fromValue(String input) {
      for (FuenteFalloEnum b : FuenteFalloEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FuenteFalloEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FuenteFalloEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public FuenteFalloEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return FuenteFalloEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("fuenteFallo")
  private FuenteFalloEnum fuenteFallo = null;

  public ResponseRnmcVO personaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
    return this;
  }

   /**
   * Get personaVO
   * @return personaVO
  **/
  @Schema(required = true, description = "")
  public PersonaVO getPersonaVO() {
    return personaVO;
  }

  public void setPersonaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
  }

  public ResponseRnmcVO estado(String estado) {
    this.estado = estado;
    return this;
  }

   /**
   * Estado general de la consulta de registros.
   * @return estado
  **/
  @Schema(example = "PRESENTA LOS SIGUIENTES REGISTROS:", required = true, description = "Estado general de la consulta de registros.")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public ResponseRnmcVO expediente(String expediente) {
    this.expediente = expediente;
    return this;
  }

   /**
   * Número de expediente del registro.
   * @return expediente
  **/
  @Schema(example = "68-276-6-2020-12418", required = true, description = "Número de expediente del registro.")
  public String getExpediente() {
    return expediente;
  }

  public void setExpediente(String expediente) {
    this.expediente = expediente;
  }

  public ResponseRnmcVO formato(String formato) {
    this.formato = formato;
    return this;
  }

   /**
   * Formato del registro.
   * @return formato
  **/
  @Schema(example = "002", required = true, description = "Formato del registro.")
  public String getFormato() {
    return formato;
  }

  public void setFormato(String formato) {
    this.formato = formato;
  }

  public ResponseRnmcVO fecha(String fecha) {
    this.fecha = fecha;
    return this;
  }

   /**
   * Get fecha
   * @return fecha
  **/
  @Schema(required = true, description = "")
  public String getFecha() {
    return fecha;
  }

  public void setFecha(String fecha) {
    this.fecha = fecha;
  }

  public ResponseRnmcVO departamento(String departamento) {
    this.departamento = departamento;
    return this;
  }

   /**
   * Departamento donde se registró la medida correctiva.
   * @return departamento
  **/
  @Schema(example = "SANTANDER", required = true, description = "Departamento donde se registró la medida correctiva.")
  public String getDepartamento() {
    return departamento;
  }

  public void setDepartamento(String departamento) {
    this.departamento = departamento;
  }

  public ResponseRnmcVO municipio(String municipio) {
    this.municipio = municipio;
    return this;
  }

   /**
   * Municipio donde se registró la medida correctiva.
   * @return municipio
  **/
  @Schema(example = "FLORIDABLANCA", required = true, description = "Municipio donde se registró la medida correctiva.")
  public String getMunicipio() {
    return municipio;
  }

  public void setMunicipio(String municipio) {
    this.municipio = municipio;
  }

  public ResponseRnmcVO articulo(String articulo) {
    this.articulo = articulo;
    return this;
  }

   /**
   * Artículo legal que fundamenta la medida.
   * @return articulo
  **/
  @Schema(example = "Art. 35 Comportamientos que afectan las relaciones entre las personas y las autoridades", required = true, description = "Artículo legal que fundamenta la medida.")
  public String getArticulo() {
    return articulo;
  }

  public void setArticulo(String articulo) {
    this.articulo = articulo;
  }

  public ResponseRnmcVO numeral(String numeral) {
    this.numeral = numeral;
    return this;
  }

   /**
   * Numeral del artículo legal.
   * @return numeral
  **/
  @Schema(example = "Num. 2 Incumplir, desacatar, desconocer e impedir la función o la orden de policía", required = true, description = "Numeral del artículo legal.")
  public String getNumeral() {
    return numeral;
  }

  public void setNumeral(String numeral) {
    this.numeral = numeral;
  }

  public ResponseRnmcVO literal(String literal) {
    this.literal = literal;
    return this;
  }

   /**
   * Literal del artículo/numeral (si aplica).
   * @return literal
  **/
  @Schema(example = "No aplica", required = true, description = "Literal del artículo/numeral (si aplica).")
  public String getLiteral() {
    return literal;
  }

  public void setLiteral(String literal) {
    this.literal = literal;
  }

  public ResponseRnmcVO apelacion(ApelacionEnum apelacion) {
    this.apelacion = apelacion;
    return this;
  }

   /**
   * Indica si el registro está en apelación.
   * @return apelacion
  **/
  @Schema(example = "SI", required = true, description = "Indica si el registro está en apelación.")
  public ApelacionEnum getApelacion() {
    return apelacion;
  }

  public void setApelacion(ApelacionEnum apelacion) {
    this.apelacion = apelacion;
  }

  public ResponseRnmcVO localidad(String localidad) {
    this.localidad = localidad;
    return this;
  }

   /**
   * Localidad o sector donde ocurrió el comportamiento.
   * @return localidad
  **/
  @Schema(example = "C-2 CAÑAVERAL", required = true, description = "Localidad o sector donde ocurrió el comportamiento.")
  public String getLocalidad() {
    return localidad;
  }

  public void setLocalidad(String localidad) {
    this.localidad = localidad;
  }

  public ResponseRnmcVO relato(String relato) {
    this.relato = relato;
    return this;
  }

   /**
   * Relato descriptivo de los hechos que llevaron a la medida correctiva.
   * @return relato
  **/
  @Schema(example = "El ciudadano en mencion desacata la orden de policia emitida por el alcalde municipal de Floridablanca en el decreto 0223 del 31 de mayo de 2020 en su articulo 3 de pico y cédula en concordancia con el decreto municipal de Floridablanca 0238 del 30 de junio de 2020 en su articulo 1 referente a la autorizacion para transitar donde el dia de hoy corresponde para los ciudadanos que la cédula de ciudadania termine en par y la del ciudadano termina en impar 7 y al momento no se encuentra realizando la actividad ni presenta ningún tipo de permiso.", required = true, description = "Relato descriptivo de los hechos que llevaron a la medida correctiva.")
  public String getRelato() {
    return relato;
  }

  public void setRelato(String relato) {
    this.relato = relato;
  }

  public ResponseRnmcVO descargos(String descargos) {
    this.descargos = descargos;
    return this;
  }

   /**
   * Descargos o alegatos presentados por el ciudadano.
   * @return descargos
  **/
  @Schema(example = "el ciudadano manifiesta \" tengo el permiso para salir debido a mi razón social la cual me indica que puedo salir en las excepciones del decreto y debido a que es un negocio virtual puedo estar en cualquier lugar ejerciendo la labor.", required = true, description = "Descargos o alegatos presentados por el ciudadano.")
  public String getDescargos() {
    return descargos;
  }

  public void setDescargos(String descargos) {
    this.descargos = descargos;
  }

  public ResponseRnmcVO listMedidasCorrectivases(List<ResponseRnmcVOListMedidasCorrectivases> listMedidasCorrectivases) {
    this.listMedidasCorrectivases = listMedidasCorrectivases;
    return this;
  }

  public ResponseRnmcVO addListMedidasCorrectivasesItem(ResponseRnmcVOListMedidasCorrectivases listMedidasCorrectivasesItem) {
    this.listMedidasCorrectivases.add(listMedidasCorrectivasesItem);
    return this;
  }

   /**
   * Listado de medidas correctivas aplicadas.
   * @return listMedidasCorrectivases
  **/
  @Schema(required = true, description = "Listado de medidas correctivas aplicadas.")
  public List<ResponseRnmcVOListMedidasCorrectivases> getListMedidasCorrectivases() {
    return listMedidasCorrectivases;
  }

  public void setListMedidasCorrectivases(List<ResponseRnmcVOListMedidasCorrectivases> listMedidasCorrectivases) {
    this.listMedidasCorrectivases = listMedidasCorrectivases;
  }

  public ResponseRnmcVO fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Get fechaConsulta
   * @return fechaConsulta
  **/
  @Schema(required = true, description = "")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public ResponseRnmcVO fuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
    return this;
  }

   /**
   * Indica si la fuente falló en la consulta.
   * @return fuenteFallo
  **/
  @Schema(example = "NO", required = true, description = "Indica si la fuente falló en la consulta.")
  public FuenteFalloEnum getFuenteFallo() {
    return fuenteFallo;
  }

  public void setFuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRnmcVO responseRnmcVO = (ResponseRnmcVO) o;
    return Objects.equals(this.personaVO, responseRnmcVO.personaVO) &&
        Objects.equals(this.estado, responseRnmcVO.estado) &&
        Objects.equals(this.expediente, responseRnmcVO.expediente) &&
        Objects.equals(this.formato, responseRnmcVO.formato) &&
        Objects.equals(this.fecha, responseRnmcVO.fecha) &&
        Objects.equals(this.departamento, responseRnmcVO.departamento) &&
        Objects.equals(this.municipio, responseRnmcVO.municipio) &&
        Objects.equals(this.articulo, responseRnmcVO.articulo) &&
        Objects.equals(this.numeral, responseRnmcVO.numeral) &&
        Objects.equals(this.literal, responseRnmcVO.literal) &&
        Objects.equals(this.apelacion, responseRnmcVO.apelacion) &&
        Objects.equals(this.localidad, responseRnmcVO.localidad) &&
        Objects.equals(this.relato, responseRnmcVO.relato) &&
        Objects.equals(this.descargos, responseRnmcVO.descargos) &&
        Objects.equals(this.listMedidasCorrectivases, responseRnmcVO.listMedidasCorrectivases) &&
        Objects.equals(this.fechaConsulta, responseRnmcVO.fechaConsulta) &&
        Objects.equals(this.fuenteFallo, responseRnmcVO.fuenteFallo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personaVO, estado, expediente, formato, fecha, departamento, municipio, articulo, numeral, literal, apelacion, localidad, relato, descargos, listMedidasCorrectivases, fechaConsulta, fuenteFallo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRnmcVO {\n");
    
    sb.append("    personaVO: ").append(toIndentedString(personaVO)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    expediente: ").append(toIndentedString(expediente)).append("\n");
    sb.append("    formato: ").append(toIndentedString(formato)).append("\n");
    sb.append("    fecha: ").append(toIndentedString(fecha)).append("\n");
    sb.append("    departamento: ").append(toIndentedString(departamento)).append("\n");
    sb.append("    municipio: ").append(toIndentedString(municipio)).append("\n");
    sb.append("    articulo: ").append(toIndentedString(articulo)).append("\n");
    sb.append("    numeral: ").append(toIndentedString(numeral)).append("\n");
    sb.append("    literal: ").append(toIndentedString(literal)).append("\n");
    sb.append("    apelacion: ").append(toIndentedString(apelacion)).append("\n");
    sb.append("    localidad: ").append(toIndentedString(localidad)).append("\n");
    sb.append("    relato: ").append(toIndentedString(relato)).append("\n");
    sb.append("    descargos: ").append(toIndentedString(descargos)).append("\n");
    sb.append("    listMedidasCorrectivases: ").append(toIndentedString(listMedidasCorrectivases)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    fuenteFallo: ").append(toIndentedString(fuenteFallo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
