/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollection
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollection {
  @SerializedName("tblPensionesGrpPensiones")
  private List<ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones> tblPensionesGrpPensiones = null;

  public ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollection tblPensionesGrpPensiones(List<ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones> tblPensionesGrpPensiones) {
    this.tblPensionesGrpPensiones = tblPensionesGrpPensiones;
    return this;
  }

  public ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollection addTblPensionesGrpPensionesItem(ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones tblPensionesGrpPensionesItem) {
    if (this.tblPensionesGrpPensiones == null) {
      this.tblPensionesGrpPensiones = new ArrayList<ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones>();
    }
    this.tblPensionesGrpPensiones.add(tblPensionesGrpPensionesItem);
    return this;
  }

   /**
   * Detalles de afiliación a Pensiones.
   * @return tblPensionesGrpPensiones
  **/
  @Schema(description = "Detalles de afiliación a Pensiones.")
  public List<ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones> getTblPensionesGrpPensiones() {
    return tblPensionesGrpPensiones;
  }

  public void setTblPensionesGrpPensiones(List<ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollectionTblPensionesGrpPensiones> tblPensionesGrpPensiones) {
    this.tblPensionesGrpPensiones = tblPensionesGrpPensiones;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollection responseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollection = (ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollection) o;
    return Objects.equals(this.tblPensionesGrpPensiones, responseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollection.tblPensionesGrpPensiones);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tblPensionesGrpPensiones);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuafVOReportVOLstPensionadosTblPensionesTblPensionesGrpPensionesCollection {\n");
    
    sb.append("    tblPensionesGrpPensiones: ").append(toIndentedString(tblPensionesGrpPensiones)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
