/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PersonaVO;
import io.swagger.client.model.ResponseServicioNuevoSoiVOAportesSeguridadSocial;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Colombia -  45749652 - Pago de Seguridad Social SOI
 */
@Schema(description = "Colombia -  45749652 - Pago de Seguridad Social SOI")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseServicioNuevoSoiVO {
  @SerializedName("personaVO")
  private PersonaVO personaVO = null;

  @SerializedName("aportesSeguridadSocial")
  private List<ResponseServicioNuevoSoiVOAportesSeguridadSocial> aportesSeguridadSocial = new ArrayList<ResponseServicioNuevoSoiVOAportesSeguridadSocial>();

  @SerializedName("aportesParafiscales")
  private List<Object> aportesParafiscales = new ArrayList<Object>();

  @SerializedName("mensajeEstado")
  private String mensajeEstado = null;

  @SerializedName("nombreAportante")
  private String nombreAportante = null;

  @SerializedName("numeroPlanilla")
  private String numeroPlanilla = null;

  @SerializedName("tipoPlanilla")
  private String tipoPlanilla = null;

  @SerializedName("periodoCotizadoOtros")
  private String periodoCotizadoOtros = null;

  @SerializedName("periodoCotizadoSalud")
  private String periodoCotizadoSalud = null;

  @SerializedName("fechaPago")
  private String fechaPago = null;

  @SerializedName("numeroAutorizacion")
  private String numeroAutorizacion = null;

  /**
   * Indica si el aportante está exonerado de algún tipo de aporte.
   */
  @JsonAdapter(ExoneradoEnum.Adapter.class)
  public enum ExoneradoEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    ExoneradoEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ExoneradoEnum fromValue(String input) {
      for (ExoneradoEnum b : ExoneradoEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ExoneradoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ExoneradoEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public ExoneradoEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return ExoneradoEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("exonerado")
  private ExoneradoEnum exonerado = null;

  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  /**
   * Indica si la fuente falló en la consulta.
   */
  @JsonAdapter(FuenteFalloEnum.Adapter.class)
  public enum FuenteFalloEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    FuenteFalloEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FuenteFalloEnum fromValue(String input) {
      for (FuenteFalloEnum b : FuenteFalloEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FuenteFalloEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FuenteFalloEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public FuenteFalloEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return FuenteFalloEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("fuenteFallo")
  private FuenteFalloEnum fuenteFallo = null;

  public ResponseServicioNuevoSoiVO personaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
    return this;
  }

   /**
   * Get personaVO
   * @return personaVO
  **/
  @Schema(required = true, description = "")
  public PersonaVO getPersonaVO() {
    return personaVO;
  }

  public void setPersonaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
  }

  public ResponseServicioNuevoSoiVO aportesSeguridadSocial(List<ResponseServicioNuevoSoiVOAportesSeguridadSocial> aportesSeguridadSocial) {
    this.aportesSeguridadSocial = aportesSeguridadSocial;
    return this;
  }

  public ResponseServicioNuevoSoiVO addAportesSeguridadSocialItem(ResponseServicioNuevoSoiVOAportesSeguridadSocial aportesSeguridadSocialItem) {
    this.aportesSeguridadSocial.add(aportesSeguridadSocialItem);
    return this;
  }

   /**
   * Listado de aportes a seguridad social (salud, pensión, ARL).
   * @return aportesSeguridadSocial
  **/
  @Schema(required = true, description = "Listado de aportes a seguridad social (salud, pensión, ARL).")
  public List<ResponseServicioNuevoSoiVOAportesSeguridadSocial> getAportesSeguridadSocial() {
    return aportesSeguridadSocial;
  }

  public void setAportesSeguridadSocial(List<ResponseServicioNuevoSoiVOAportesSeguridadSocial> aportesSeguridadSocial) {
    this.aportesSeguridadSocial = aportesSeguridadSocial;
  }

  public ResponseServicioNuevoSoiVO aportesParafiscales(List<Object> aportesParafiscales) {
    this.aportesParafiscales = aportesParafiscales;
    return this;
  }

  public ResponseServicioNuevoSoiVO addAportesParafiscalesItem(Object aportesParafiscalesItem) {
    this.aportesParafiscales.add(aportesParafiscalesItem);
    return this;
  }

   /**
   * Listado de aportes parafiscales
   * @return aportesParafiscales
  **/
  @Schema(example = "[]", required = true, description = "Listado de aportes parafiscales")
  public List<Object> getAportesParafiscales() {
    return aportesParafiscales;
  }

  public void setAportesParafiscales(List<Object> aportesParafiscales) {
    this.aportesParafiscales = aportesParafiscales;
  }

  public ResponseServicioNuevoSoiVO mensajeEstado(String mensajeEstado) {
    this.mensajeEstado = mensajeEstado;
    return this;
  }

   /**
   * Mensaje de estado de la consulta (puede estar vacío).
   * @return mensajeEstado
  **/
  @Schema(required = true, description = "Mensaje de estado de la consulta (puede estar vacío).")
  public String getMensajeEstado() {
    return mensajeEstado;
  }

  public void setMensajeEstado(String mensajeEstado) {
    this.mensajeEstado = mensajeEstado;
  }

  public ResponseServicioNuevoSoiVO nombreAportante(String nombreAportante) {
    this.nombreAportante = nombreAportante;
    return this;
  }

   /**
   * Nombre del aportante.
   * @return nombreAportante
  **/
  @Schema(example = "AMPARO", required = true, description = "Nombre del aportante.")
  public String getNombreAportante() {
    return nombreAportante;
  }

  public void setNombreAportante(String nombreAportante) {
    this.nombreAportante = nombreAportante;
  }

  public ResponseServicioNuevoSoiVO numeroPlanilla(String numeroPlanilla) {
    this.numeroPlanilla = numeroPlanilla;
    return this;
  }

   /**
   * Número de la planilla SOI.
   * @return numeroPlanilla
  **/
  @Schema(example = "4370447851", required = true, description = "Número de la planilla SOI.")
  public String getNumeroPlanilla() {
    return numeroPlanilla;
  }

  public void setNumeroPlanilla(String numeroPlanilla) {
    this.numeroPlanilla = numeroPlanilla;
  }

  public ResponseServicioNuevoSoiVO tipoPlanilla(String tipoPlanilla) {
    this.tipoPlanilla = tipoPlanilla;
    return this;
  }

   /**
   * Tipo de planilla SOI
   * @return tipoPlanilla
  **/
  @Schema(example = "I-INDEPENDIENTES", required = true, description = "Tipo de planilla SOI")
  public String getTipoPlanilla() {
    return tipoPlanilla;
  }

  public void setTipoPlanilla(String tipoPlanilla) {
    this.tipoPlanilla = tipoPlanilla;
  }

  public ResponseServicioNuevoSoiVO periodoCotizadoOtros(String periodoCotizadoOtros) {
    this.periodoCotizadoOtros = periodoCotizadoOtros;
    return this;
  }

   /**
   * Periodo cotizado para otros aportes.
   * @return periodoCotizadoOtros
  **/
  @Schema(example = "ENERO/2021", required = true, description = "Periodo cotizado para otros aportes.")
  public String getPeriodoCotizadoOtros() {
    return periodoCotizadoOtros;
  }

  public void setPeriodoCotizadoOtros(String periodoCotizadoOtros) {
    this.periodoCotizadoOtros = periodoCotizadoOtros;
  }

  public ResponseServicioNuevoSoiVO periodoCotizadoSalud(String periodoCotizadoSalud) {
    this.periodoCotizadoSalud = periodoCotizadoSalud;
    return this;
  }

   /**
   * Periodo cotizado para salud.
   * @return periodoCotizadoSalud
  **/
  @Schema(example = "ENERO/2021", required = true, description = "Periodo cotizado para salud.")
  public String getPeriodoCotizadoSalud() {
    return periodoCotizadoSalud;
  }

  public void setPeriodoCotizadoSalud(String periodoCotizadoSalud) {
    this.periodoCotizadoSalud = periodoCotizadoSalud;
  }

  public ResponseServicioNuevoSoiVO fechaPago(String fechaPago) {
    this.fechaPago = fechaPago;
    return this;
  }

   /**
   * Get fechaPago
   * @return fechaPago
  **/
  @Schema(required = true, description = "")
  public String getFechaPago() {
    return fechaPago;
  }

  public void setFechaPago(String fechaPago) {
    this.fechaPago = fechaPago;
  }

  public ResponseServicioNuevoSoiVO numeroAutorizacion(String numeroAutorizacion) {
    this.numeroAutorizacion = numeroAutorizacion;
    return this;
  }

   /**
   * Número de autorización.
   * @return numeroAutorizacion
  **/
  @Schema(example = "9993766969", required = true, description = "Número de autorización.")
  public String getNumeroAutorizacion() {
    return numeroAutorizacion;
  }

  public void setNumeroAutorizacion(String numeroAutorizacion) {
    this.numeroAutorizacion = numeroAutorizacion;
  }

  public ResponseServicioNuevoSoiVO exonerado(ExoneradoEnum exonerado) {
    this.exonerado = exonerado;
    return this;
  }

   /**
   * Indica si el aportante está exonerado de algún tipo de aporte.
   * @return exonerado
  **/
  @Schema(example = "NO", required = true, description = "Indica si el aportante está exonerado de algún tipo de aporte.")
  public ExoneradoEnum getExonerado() {
    return exonerado;
  }

  public void setExonerado(ExoneradoEnum exonerado) {
    this.exonerado = exonerado;
  }

  public ResponseServicioNuevoSoiVO fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Get fechaConsulta
   * @return fechaConsulta
  **/
  @Schema(required = true, description = "")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public ResponseServicioNuevoSoiVO fuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
    return this;
  }

   /**
   * Indica si la fuente falló en la consulta.
   * @return fuenteFallo
  **/
  @Schema(example = "NO", required = true, description = "Indica si la fuente falló en la consulta.")
  public FuenteFalloEnum getFuenteFallo() {
    return fuenteFallo;
  }

  public void setFuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseServicioNuevoSoiVO responseServicioNuevoSoiVO = (ResponseServicioNuevoSoiVO) o;
    return Objects.equals(this.personaVO, responseServicioNuevoSoiVO.personaVO) &&
        Objects.equals(this.aportesSeguridadSocial, responseServicioNuevoSoiVO.aportesSeguridadSocial) &&
        Objects.equals(this.aportesParafiscales, responseServicioNuevoSoiVO.aportesParafiscales) &&
        Objects.equals(this.mensajeEstado, responseServicioNuevoSoiVO.mensajeEstado) &&
        Objects.equals(this.nombreAportante, responseServicioNuevoSoiVO.nombreAportante) &&
        Objects.equals(this.numeroPlanilla, responseServicioNuevoSoiVO.numeroPlanilla) &&
        Objects.equals(this.tipoPlanilla, responseServicioNuevoSoiVO.tipoPlanilla) &&
        Objects.equals(this.periodoCotizadoOtros, responseServicioNuevoSoiVO.periodoCotizadoOtros) &&
        Objects.equals(this.periodoCotizadoSalud, responseServicioNuevoSoiVO.periodoCotizadoSalud) &&
        Objects.equals(this.fechaPago, responseServicioNuevoSoiVO.fechaPago) &&
        Objects.equals(this.numeroAutorizacion, responseServicioNuevoSoiVO.numeroAutorizacion) &&
        Objects.equals(this.exonerado, responseServicioNuevoSoiVO.exonerado) &&
        Objects.equals(this.fechaConsulta, responseServicioNuevoSoiVO.fechaConsulta) &&
        Objects.equals(this.fuenteFallo, responseServicioNuevoSoiVO.fuenteFallo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personaVO, aportesSeguridadSocial, aportesParafiscales, mensajeEstado, nombreAportante, numeroPlanilla, tipoPlanilla, periodoCotizadoOtros, periodoCotizadoSalud, fechaPago, numeroAutorizacion, exonerado, fechaConsulta, fuenteFallo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseServicioNuevoSoiVO {\n");
    
    sb.append("    personaVO: ").append(toIndentedString(personaVO)).append("\n");
    sb.append("    aportesSeguridadSocial: ").append(toIndentedString(aportesSeguridadSocial)).append("\n");
    sb.append("    aportesParafiscales: ").append(toIndentedString(aportesParafiscales)).append("\n");
    sb.append("    mensajeEstado: ").append(toIndentedString(mensajeEstado)).append("\n");
    sb.append("    nombreAportante: ").append(toIndentedString(nombreAportante)).append("\n");
    sb.append("    numeroPlanilla: ").append(toIndentedString(numeroPlanilla)).append("\n");
    sb.append("    tipoPlanilla: ").append(toIndentedString(tipoPlanilla)).append("\n");
    sb.append("    periodoCotizadoOtros: ").append(toIndentedString(periodoCotizadoOtros)).append("\n");
    sb.append("    periodoCotizadoSalud: ").append(toIndentedString(periodoCotizadoSalud)).append("\n");
    sb.append("    fechaPago: ").append(toIndentedString(fechaPago)).append("\n");
    sb.append("    numeroAutorizacion: ").append(toIndentedString(numeroAutorizacion)).append("\n");
    sb.append("    exonerado: ").append(toIndentedString(exonerado)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    fuenteFallo: ").append(toIndentedString(fuenteFallo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
