/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseCmpVORegistrosList
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseCmpVORegistrosList {
  @SerializedName("nombreRegistro")
  private String nombreRegistro = null;

  @SerializedName("tipo")
  private String tipo = null;

  @SerializedName("codigo")
  private String codigo = null;

  @SerializedName("fecha")
  private String fecha = null;

  public ResponseCmpVORegistrosList nombreRegistro(String nombreRegistro) {
    this.nombreRegistro = nombreRegistro;
    return this;
  }

   /**
   * Nombre del registro o especialidad.
   * @return nombreRegistro
  **/
  @Schema(example = "DIPLOMATURA EN AUDITORIA MEDICA", required = true, description = "Nombre del registro o especialidad.")
  public String getNombreRegistro() {
    return nombreRegistro;
  }

  public void setNombreRegistro(String nombreRegistro) {
    this.nombreRegistro = nombreRegistro;
  }

  public ResponseCmpVORegistrosList tipo(String tipo) {
    this.tipo = tipo;
    return this;
  }

   /**
   * Tipo de registro
   * @return tipo
  **/
  @Schema(example = "RNA", required = true, description = "Tipo de registro")
  public String getTipo() {
    return tipo;
  }

  public void setTipo(String tipo) {
    this.tipo = tipo;
  }

  public ResponseCmpVORegistrosList codigo(String codigo) {
    this.codigo = codigo;
    return this;
  }

   /**
   * Código del registro.
   * @return codigo
  **/
  @Schema(example = "A05252", required = true, description = "Código del registro.")
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  public ResponseCmpVORegistrosList fecha(String fecha) {
    this.fecha = fecha;
    return this;
  }

   /**
   * Get fecha
   * @return fecha
  **/
  @Schema(required = true, description = "")
  public String getFecha() {
    return fecha;
  }

  public void setFecha(String fecha) {
    this.fecha = fecha;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseCmpVORegistrosList responseCmpVORegistrosList = (ResponseCmpVORegistrosList) o;
    return Objects.equals(this.nombreRegistro, responseCmpVORegistrosList.nombreRegistro) &&
        Objects.equals(this.tipo, responseCmpVORegistrosList.tipo) &&
        Objects.equals(this.codigo, responseCmpVORegistrosList.codigo) &&
        Objects.equals(this.fecha, responseCmpVORegistrosList.fecha);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nombreRegistro, tipo, codigo, fecha);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseCmpVORegistrosList {\n");
    
    sb.append("    nombreRegistro: ").append(toIndentedString(nombreRegistro)).append("\n");
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    fecha: ").append(toIndentedString(fecha)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
