/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollectionTblAsistenciaSocialGrpPersona;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollection
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollection {
  @SerializedName("tblAsistenciaSocialGrpPersona")
  private List<ResponseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollectionTblAsistenciaSocialGrpPersona> tblAsistenciaSocialGrpPersona = null;

  public ResponseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollection tblAsistenciaSocialGrpPersona(List<ResponseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollectionTblAsistenciaSocialGrpPersona> tblAsistenciaSocialGrpPersona) {
    this.tblAsistenciaSocialGrpPersona = tblAsistenciaSocialGrpPersona;
    return this;
  }

  public ResponseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollection addTblAsistenciaSocialGrpPersonaItem(ResponseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollectionTblAsistenciaSocialGrpPersona tblAsistenciaSocialGrpPersonaItem) {
    if (this.tblAsistenciaSocialGrpPersona == null) {
      this.tblAsistenciaSocialGrpPersona = new ArrayList<ResponseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollectionTblAsistenciaSocialGrpPersona>();
    }
    this.tblAsistenciaSocialGrpPersona.add(tblAsistenciaSocialGrpPersonaItem);
    return this;
  }

   /**
   * Get tblAsistenciaSocialGrpPersona
   * @return tblAsistenciaSocialGrpPersona
  **/
  @Schema(description = "")
  public List<ResponseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollectionTblAsistenciaSocialGrpPersona> getTblAsistenciaSocialGrpPersona() {
    return tblAsistenciaSocialGrpPersona;
  }

  public void setTblAsistenciaSocialGrpPersona(List<ResponseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollectionTblAsistenciaSocialGrpPersona> tblAsistenciaSocialGrpPersona) {
    this.tblAsistenciaSocialGrpPersona = tblAsistenciaSocialGrpPersona;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollection responseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollection = (ResponseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollection) o;
    return Objects.equals(this.tblAsistenciaSocialGrpPersona, responseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollection.tblAsistenciaSocialGrpPersona);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tblAsistenciaSocialGrpPersona);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuafVOReportVOLstPensionadosTblAsistenciaSocialTblAsistenciaSocialGrpPersonaCollection {\n");
    
    sb.append("    tblAsistenciaSocialGrpPersona: ").append(toIndentedString(tblAsistenciaSocialGrpPersona)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
