/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PersonaVO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Colombia -  98653214 - Consulta de antecedentes disciplinarios ante la personería de Bogotá.
 */
@Schema(description = "Colombia -  98653214 - Consulta de antecedentes disciplinarios ante la personería de Bogotá.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponsePersoneriaBogotaVO {
  @SerializedName("personaVO")
  private PersonaVO personaVO = null;

  @SerializedName("antecedentes")
  private String antecedentes = null;

  @SerializedName("lugarExpedicion")
  private String lugarExpedicion = null;

  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  /**
   * Indica si la fuente falló en la consulta.
   */
  @JsonAdapter(FuenteFalloEnum.Adapter.class)
  public enum FuenteFalloEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    FuenteFalloEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FuenteFalloEnum fromValue(String input) {
      for (FuenteFalloEnum b : FuenteFalloEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FuenteFalloEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FuenteFalloEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public FuenteFalloEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return FuenteFalloEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("fuenteFallo")
  private FuenteFalloEnum fuenteFallo = null;

  public ResponsePersoneriaBogotaVO personaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
    return this;
  }

   /**
   * Get personaVO
   * @return personaVO
  **/
  @Schema(required = true, description = "")
  public PersonaVO getPersonaVO() {
    return personaVO;
  }

  public void setPersonaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
  }

  public ResponsePersoneriaBogotaVO antecedentes(String antecedentes) {
    this.antecedentes = antecedentes;
    return this;
  }

   /**
   * Información sobre sanciones o inhabilidades registradas.
   * @return antecedentes
  **/
  @Schema(example = "NO REGISTRA SANCIONES NI INHABILIDADES VIGENTES", required = true, description = "Información sobre sanciones o inhabilidades registradas.")
  public String getAntecedentes() {
    return antecedentes;
  }

  public void setAntecedentes(String antecedentes) {
    this.antecedentes = antecedentes;
  }

  public ResponsePersoneriaBogotaVO lugarExpedicion(String lugarExpedicion) {
    this.lugarExpedicion = lugarExpedicion;
    return this;
  }

   /**
   * Lugar de expedición del documento o donde se realizó la consulta del antecedente.
   * @return lugarExpedicion
  **/
  @Schema(example = "VALLEDUPAR", required = true, description = "Lugar de expedición del documento o donde se realizó la consulta del antecedente.")
  public String getLugarExpedicion() {
    return lugarExpedicion;
  }

  public void setLugarExpedicion(String lugarExpedicion) {
    this.lugarExpedicion = lugarExpedicion;
  }

  public ResponsePersoneriaBogotaVO fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Get fechaConsulta
   * @return fechaConsulta
  **/
  @Schema(required = true, description = "")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public ResponsePersoneriaBogotaVO fuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
    return this;
  }

   /**
   * Indica si la fuente falló en la consulta.
   * @return fuenteFallo
  **/
  @Schema(example = "NO", description = "Indica si la fuente falló en la consulta.")
  public FuenteFalloEnum getFuenteFallo() {
    return fuenteFallo;
  }

  public void setFuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsePersoneriaBogotaVO responsePersoneriaBogotaVO = (ResponsePersoneriaBogotaVO) o;
    return Objects.equals(this.personaVO, responsePersoneriaBogotaVO.personaVO) &&
        Objects.equals(this.antecedentes, responsePersoneriaBogotaVO.antecedentes) &&
        Objects.equals(this.lugarExpedicion, responsePersoneriaBogotaVO.lugarExpedicion) &&
        Objects.equals(this.fechaConsulta, responsePersoneriaBogotaVO.fechaConsulta) &&
        Objects.equals(this.fuenteFallo, responsePersoneriaBogotaVO.fuenteFallo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personaVO, antecedentes, lugarExpedicion, fechaConsulta, fuenteFallo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsePersoneriaBogotaVO {\n");
    
    sb.append("    personaVO: ").append(toIndentedString(personaVO)).append("\n");
    sb.append("    antecedentes: ").append(toIndentedString(antecedentes)).append("\n");
    sb.append("    lugarExpedicion: ").append(toIndentedString(lugarExpedicion)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    fuenteFallo: ").append(toIndentedString(fuenteFallo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
