/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.LocalDate;
/**
 * Información del certificado de desintegración física del vehículo.
 */
@Schema(description = "Información del certificado de desintegración física del vehículo.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuntPlacaVOCertificadoDesintegracionFisica {
  @SerializedName("nroCertificacion")
  private String nroCertificacion = null;

  @SerializedName("estadoCertificado")
  private String estadoCertificado = null;

  @SerializedName("fechaExpedicion")
  private LocalDate fechaExpedicion = null;

  @SerializedName("entidadDesintegradora")
  private String entidadDesintegradora = null;

  public ResponseRuntPlacaVOCertificadoDesintegracionFisica nroCertificacion(String nroCertificacion) {
    this.nroCertificacion = nroCertificacion;
    return this;
  }

   /**
   * Número de certificación de desintegración.
   * @return nroCertificacion
  **/
  @Schema(required = true, description = "Número de certificación de desintegración.")
  public String getNroCertificacion() {
    return nroCertificacion;
  }

  public void setNroCertificacion(String nroCertificacion) {
    this.nroCertificacion = nroCertificacion;
  }

  public ResponseRuntPlacaVOCertificadoDesintegracionFisica estadoCertificado(String estadoCertificado) {
    this.estadoCertificado = estadoCertificado;
    return this;
  }

   /**
   * Estado del certificado de desintegración.
   * @return estadoCertificado
  **/
  @Schema(required = true, description = "Estado del certificado de desintegración.")
  public String getEstadoCertificado() {
    return estadoCertificado;
  }

  public void setEstadoCertificado(String estadoCertificado) {
    this.estadoCertificado = estadoCertificado;
  }

  public ResponseRuntPlacaVOCertificadoDesintegracionFisica fechaExpedicion(LocalDate fechaExpedicion) {
    this.fechaExpedicion = fechaExpedicion;
    return this;
  }

   /**
   * Fecha de expedición del certificado de desintegración.
   * @return fechaExpedicion
  **/
  @Schema(required = true, description = "Fecha de expedición del certificado de desintegración.")
  public LocalDate getFechaExpedicion() {
    return fechaExpedicion;
  }

  public void setFechaExpedicion(LocalDate fechaExpedicion) {
    this.fechaExpedicion = fechaExpedicion;
  }

  public ResponseRuntPlacaVOCertificadoDesintegracionFisica entidadDesintegradora(String entidadDesintegradora) {
    this.entidadDesintegradora = entidadDesintegradora;
    return this;
  }

   /**
   * Entidad que realizó la desintegración.
   * @return entidadDesintegradora
  **/
  @Schema(required = true, description = "Entidad que realizó la desintegración.")
  public String getEntidadDesintegradora() {
    return entidadDesintegradora;
  }

  public void setEntidadDesintegradora(String entidadDesintegradora) {
    this.entidadDesintegradora = entidadDesintegradora;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuntPlacaVOCertificadoDesintegracionFisica responseRuntPlacaVOCertificadoDesintegracionFisica = (ResponseRuntPlacaVOCertificadoDesintegracionFisica) o;
    return Objects.equals(this.nroCertificacion, responseRuntPlacaVOCertificadoDesintegracionFisica.nroCertificacion) &&
        Objects.equals(this.estadoCertificado, responseRuntPlacaVOCertificadoDesintegracionFisica.estadoCertificado) &&
        Objects.equals(this.fechaExpedicion, responseRuntPlacaVOCertificadoDesintegracionFisica.fechaExpedicion) &&
        Objects.equals(this.entidadDesintegradora, responseRuntPlacaVOCertificadoDesintegracionFisica.entidadDesintegradora);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nroCertificacion, estadoCertificado, fechaExpedicion, entidadDesintegradora);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuntPlacaVOCertificadoDesintegracionFisica {\n");
    
    sb.append("    nroCertificacion: ").append(toIndentedString(nroCertificacion)).append("\n");
    sb.append("    estadoCertificado: ").append(toIndentedString(estadoCertificado)).append("\n");
    sb.append("    fechaExpedicion: ").append(toIndentedString(fechaExpedicion)).append("\n");
    sb.append("    entidadDesintegradora: ").append(toIndentedString(entidadDesintegradora)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
