/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseOfacVOAliases
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseOfacVOAliases {
  @SerializedName("type")
  private String type = null;

  @SerializedName("category")
  private String category = null;

  @SerializedName("name")
  private String name = null;

  public ResponseOfacVOAliases type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Tipo de alias
   * @return type
  **/
  @Schema(example = "a.k.a.", required = true, description = "Tipo de alias")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ResponseOfacVOAliases category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Categoría del alias
   * @return category
  **/
  @Schema(example = "strong", required = true, description = "Categoría del alias")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public ResponseOfacVOAliases name(String name) {
    this.name = name;
    return this;
  }

   /**
   * El alias.
   * @return name
  **/
  @Schema(example = "PITCHAYOS, Vinai", required = true, description = "El alias.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseOfacVOAliases responseOfacVOAliases = (ResponseOfacVOAliases) o;
    return Objects.equals(this.type, responseOfacVOAliases.type) &&
        Objects.equals(this.category, responseOfacVOAliases.category) &&
        Objects.equals(this.name, responseOfacVOAliases.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, category, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseOfacVOAliases {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
