/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PersonaVO;
import io.swagger.client.model.ResponseRuafVOReportVO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Colombia -  46784765 - Consultas al Sistema Integral de Información de la Protección Social. Registro Único de Afiliados (SISPRO).
 */
@Schema(description = "Colombia -  46784765 - Consultas al Sistema Integral de Información de la Protección Social. Registro Único de Afiliados (SISPRO).")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuafVO {
  @SerializedName("personaVO")
  private PersonaVO personaVO = null;

  @SerializedName("reportVO")
  private ResponseRuafVOReportVO reportVO = null;

  @SerializedName("mensajeEstado")
  private String mensajeEstado = null;

  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  /**
   * Indica si la fuente falló en la consulta.
   */
  @JsonAdapter(FuenteFalloEnum.Adapter.class)
  public enum FuenteFalloEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    FuenteFalloEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FuenteFalloEnum fromValue(String input) {
      for (FuenteFalloEnum b : FuenteFalloEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FuenteFalloEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FuenteFalloEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public FuenteFalloEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return FuenteFalloEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("fuenteFallo")
  private FuenteFalloEnum fuenteFallo = null;

  public ResponseRuafVO personaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
    return this;
  }

   /**
   * Get personaVO
   * @return personaVO
  **/
  @Schema(required = true, description = "")
  public PersonaVO getPersonaVO() {
    return personaVO;
  }

  public void setPersonaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
  }

  public ResponseRuafVO reportVO(ResponseRuafVOReportVO reportVO) {
    this.reportVO = reportVO;
    return this;
  }

   /**
   * Get reportVO
   * @return reportVO
  **/
  @Schema(required = true, description = "")
  public ResponseRuafVOReportVO getReportVO() {
    return reportVO;
  }

  public void setReportVO(ResponseRuafVOReportVO reportVO) {
    this.reportVO = reportVO;
  }

  public ResponseRuafVO mensajeEstado(String mensajeEstado) {
    this.mensajeEstado = mensajeEstado;
    return this;
  }

   /**
   * Mensaje de estado de la consulta (puede estar vacío).
   * @return mensajeEstado
  **/
  @Schema(required = true, description = "Mensaje de estado de la consulta (puede estar vacío).")
  public String getMensajeEstado() {
    return mensajeEstado;
  }

  public void setMensajeEstado(String mensajeEstado) {
    this.mensajeEstado = mensajeEstado;
  }

  public ResponseRuafVO fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Get fechaConsulta
   * @return fechaConsulta
  **/
  @Schema(required = true, description = "")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public ResponseRuafVO fuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
    return this;
  }

   /**
   * Indica si la fuente falló en la consulta.
   * @return fuenteFallo
  **/
  @Schema(example = "NO", required = true, description = "Indica si la fuente falló en la consulta.")
  public FuenteFalloEnum getFuenteFallo() {
    return fuenteFallo;
  }

  public void setFuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuafVO responseRuafVO = (ResponseRuafVO) o;
    return Objects.equals(this.personaVO, responseRuafVO.personaVO) &&
        Objects.equals(this.reportVO, responseRuafVO.reportVO) &&
        Objects.equals(this.mensajeEstado, responseRuafVO.mensajeEstado) &&
        Objects.equals(this.fechaConsulta, responseRuafVO.fechaConsulta) &&
        Objects.equals(this.fuenteFallo, responseRuafVO.fuenteFallo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personaVO, reportVO, mensajeEstado, fechaConsulta, fuenteFallo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuafVO {\n");
    
    sb.append("    personaVO: ").append(toIndentedString(personaVO)).append("\n");
    sb.append("    reportVO: ").append(toIndentedString(reportVO)).append("\n");
    sb.append("    mensajeEstado: ").append(toIndentedString(mensajeEstado)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    fuenteFallo: ").append(toIndentedString(fuenteFallo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
