/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PersonaVO;
import io.swagger.client.model.ResponseSecopVOContratos;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Colombia -  14032024 - Portal Anticorrupción de Colombia
 */
@Schema(description = "Colombia -  14032024 - Portal Anticorrupción de Colombia")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseSecopVO {
  @SerializedName("personaVO")
  private PersonaVO personaVO = null;

  @SerializedName("numSanciones")
  private String numSanciones = null;

  @SerializedName("numMultas")
  private String numMultas = null;

  @SerializedName("numResponsabilidades")
  private String numResponsabilidades = null;

  @SerializedName("contratos")
  private List<ResponseSecopVOContratos> contratos = new ArrayList<ResponseSecopVOContratos>();

  @SerializedName("estado")
  private String estado = null;

  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  /**
   * Indica si la fuente falló en la consulta.
   */
  @JsonAdapter(FuenteFalloEnum.Adapter.class)
  public enum FuenteFalloEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    FuenteFalloEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FuenteFalloEnum fromValue(String input) {
      for (FuenteFalloEnum b : FuenteFalloEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FuenteFalloEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FuenteFalloEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public FuenteFalloEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return FuenteFalloEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("fuenteFallo")
  private FuenteFalloEnum fuenteFallo = null;

  public ResponseSecopVO personaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
    return this;
  }

   /**
   * Get personaVO
   * @return personaVO
  **/
  @Schema(required = true, description = "")
  public PersonaVO getPersonaVO() {
    return personaVO;
  }

  public void setPersonaVO(PersonaVO personaVO) {
    this.personaVO = personaVO;
  }

  public ResponseSecopVO numSanciones(String numSanciones) {
    this.numSanciones = numSanciones;
    return this;
  }

   /**
   * Número de sanciones registradas.
   * @return numSanciones
  **/
  @Schema(example = "0", required = true, description = "Número de sanciones registradas.")
  public String getNumSanciones() {
    return numSanciones;
  }

  public void setNumSanciones(String numSanciones) {
    this.numSanciones = numSanciones;
  }

  public ResponseSecopVO numMultas(String numMultas) {
    this.numMultas = numMultas;
    return this;
  }

   /**
   * Número de multas registradas.
   * @return numMultas
  **/
  @Schema(example = "0", required = true, description = "Número de multas registradas.")
  public String getNumMultas() {
    return numMultas;
  }

  public void setNumMultas(String numMultas) {
    this.numMultas = numMultas;
  }

  public ResponseSecopVO numResponsabilidades(String numResponsabilidades) {
    this.numResponsabilidades = numResponsabilidades;
    return this;
  }

   /**
   * Número de responsabilidades registradas.
   * @return numResponsabilidades
  **/
  @Schema(example = "0", required = true, description = "Número de responsabilidades registradas.")
  public String getNumResponsabilidades() {
    return numResponsabilidades;
  }

  public void setNumResponsabilidades(String numResponsabilidades) {
    this.numResponsabilidades = numResponsabilidades;
  }

  public ResponseSecopVO contratos(List<ResponseSecopVOContratos> contratos) {
    this.contratos = contratos;
    return this;
  }

  public ResponseSecopVO addContratosItem(ResponseSecopVOContratos contratosItem) {
    this.contratos.add(contratosItem);
    return this;
  }

   /**
   * Listado de contratos en los que la persona o entidad ha participado.
   * @return contratos
  **/
  @Schema(required = true, description = "Listado de contratos en los que la persona o entidad ha participado.")
  public List<ResponseSecopVOContratos> getContratos() {
    return contratos;
  }

  public void setContratos(List<ResponseSecopVOContratos> contratos) {
    this.contratos = contratos;
  }

  public ResponseSecopVO estado(String estado) {
    this.estado = estado;
    return this;
  }

   /**
   * Estado general de la consulta (puede estar vacío).
   * @return estado
  **/
  @Schema(required = true, description = "Estado general de la consulta (puede estar vacío).")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public ResponseSecopVO fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Get fechaConsulta
   * @return fechaConsulta
  **/
  @Schema(required = true, description = "")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public ResponseSecopVO fuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
    return this;
  }

   /**
   * Indica si la fuente falló en la consulta.
   * @return fuenteFallo
  **/
  @Schema(example = "NO", required = true, description = "Indica si la fuente falló en la consulta.")
  public FuenteFalloEnum getFuenteFallo() {
    return fuenteFallo;
  }

  public void setFuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseSecopVO responseSecopVO = (ResponseSecopVO) o;
    return Objects.equals(this.personaVO, responseSecopVO.personaVO) &&
        Objects.equals(this.numSanciones, responseSecopVO.numSanciones) &&
        Objects.equals(this.numMultas, responseSecopVO.numMultas) &&
        Objects.equals(this.numResponsabilidades, responseSecopVO.numResponsabilidades) &&
        Objects.equals(this.contratos, responseSecopVO.contratos) &&
        Objects.equals(this.estado, responseSecopVO.estado) &&
        Objects.equals(this.fechaConsulta, responseSecopVO.fechaConsulta) &&
        Objects.equals(this.fuenteFallo, responseSecopVO.fuenteFallo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personaVO, numSanciones, numMultas, numResponsabilidades, contratos, estado, fechaConsulta, fuenteFallo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseSecopVO {\n");
    
    sb.append("    personaVO: ").append(toIndentedString(personaVO)).append("\n");
    sb.append("    numSanciones: ").append(toIndentedString(numSanciones)).append("\n");
    sb.append("    numMultas: ").append(toIndentedString(numMultas)).append("\n");
    sb.append("    numResponsabilidades: ").append(toIndentedString(numResponsabilidades)).append("\n");
    sb.append("    contratos: ").append(toIndentedString(contratos)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    fuenteFallo: ").append(toIndentedString(fuenteFallo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
