/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseRuesCamaraUnificadoVORepresentantesLegalesList
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuesCamaraUnificadoVORepresentantesLegalesList {
  @SerializedName("numeroDocumento")
  private String numeroDocumento = null;

  @SerializedName("nombre")
  private String nombre = null;

  @SerializedName("cargo")
  private String cargo = null;

  public ResponseRuesCamaraUnificadoVORepresentantesLegalesList numeroDocumento(String numeroDocumento) {
    this.numeroDocumento = numeroDocumento;
    return this;
  }

   /**
   * Número de documento del representante legal.
   * @return numeroDocumento
  **/
  @Schema(example = "43085720", required = true, description = "Número de documento del representante legal.")
  public String getNumeroDocumento() {
    return numeroDocumento;
  }

  public void setNumeroDocumento(String numeroDocumento) {
    this.numeroDocumento = numeroDocumento;
  }

  public ResponseRuesCamaraUnificadoVORepresentantesLegalesList nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

   /**
   * Nombre completo del representante legal.
   * @return nombre
  **/
  @Schema(example = "URREA GARCES LILIA MARGARITA", required = true, description = "Nombre completo del representante legal.")
  public String getNombre() {
    return nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public ResponseRuesCamaraUnificadoVORepresentantesLegalesList cargo(String cargo) {
    this.cargo = cargo;
    return this;
  }

   /**
   * Cargo del representante legal.
   * @return cargo
  **/
  @Schema(example = "REPRESENTACION LEGAL (PRINCIPALES) ****", required = true, description = "Cargo del representante legal.")
  public String getCargo() {
    return cargo;
  }

  public void setCargo(String cargo) {
    this.cargo = cargo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuesCamaraUnificadoVORepresentantesLegalesList responseRuesCamaraUnificadoVORepresentantesLegalesList = (ResponseRuesCamaraUnificadoVORepresentantesLegalesList) o;
    return Objects.equals(this.numeroDocumento, responseRuesCamaraUnificadoVORepresentantesLegalesList.numeroDocumento) &&
        Objects.equals(this.nombre, responseRuesCamaraUnificadoVORepresentantesLegalesList.nombre) &&
        Objects.equals(this.cargo, responseRuesCamaraUnificadoVORepresentantesLegalesList.cargo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroDocumento, nombre, cargo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuesCamaraUnificadoVORepresentantesLegalesList {\n");
    
    sb.append("    numeroDocumento: ").append(toIndentedString(numeroDocumento)).append("\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    cargo: ").append(toIndentedString(cargo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
