/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Colombia -  25004558 - Consulta de puesto de votación.
 */
@Schema(description = "Colombia -  25004558 - Consulta de puesto de votación.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponsePuestoVotacionVO {
  @SerializedName("estado")
  private String estado = null;

  @SerializedName("departamento")
  private String departamento = null;

  @SerializedName("municipio")
  private String municipio = null;

  @SerializedName("puestoVotacion")
  private String puestoVotacion = null;

  @SerializedName("direccionPuesto")
  private String direccionPuesto = null;

  @SerializedName("fechaInscripcion")
  private String fechaInscripcion = null;

  @SerializedName("resolucion")
  private String resolucion = null;

  @SerializedName("fechaNovedad")
  private String fechaNovedad = null;

  @SerializedName("mesa")
  private String mesa = null;

  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  /**
   * Indica si la fuente falló en la consulta.
   */
  @JsonAdapter(FuenteFalloEnum.Adapter.class)
  public enum FuenteFalloEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    FuenteFalloEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FuenteFalloEnum fromValue(String input) {
      for (FuenteFalloEnum b : FuenteFalloEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FuenteFalloEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FuenteFalloEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public FuenteFalloEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return FuenteFalloEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("fuenteFallo")
  private FuenteFalloEnum fuenteFallo = null;

  public ResponsePuestoVotacionVO estado(String estado) {
    this.estado = estado;
    return this;
  }

   /**
   * Estado general del puesto de votación o de la inscripción.
   * @return estado
  **/
  @Schema(required = true, description = "Estado general del puesto de votación o de la inscripción.")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public ResponsePuestoVotacionVO departamento(String departamento) {
    this.departamento = departamento;
    return this;
  }

   /**
   * Departamento donde se ubica el puesto de votación.
   * @return departamento
  **/
  @Schema(example = "RISARALDA", required = true, description = "Departamento donde se ubica el puesto de votación.")
  public String getDepartamento() {
    return departamento;
  }

  public void setDepartamento(String departamento) {
    this.departamento = departamento;
  }

  public ResponsePuestoVotacionVO municipio(String municipio) {
    this.municipio = municipio;
    return this;
  }

   /**
   * Municipio donde se ubica el puesto de votación.
   * @return municipio
  **/
  @Schema(example = "DOSQUEBRADAS", required = true, description = "Municipio donde se ubica el puesto de votación.")
  public String getMunicipio() {
    return municipio;
  }

  public void setMunicipio(String municipio) {
    this.municipio = municipio;
  }

  public ResponsePuestoVotacionVO puestoVotacion(String puestoVotacion) {
    this.puestoVotacion = puestoVotacion;
    return this;
  }

   /**
   * Nombre del puesto de votación.
   * @return puestoVotacion
  **/
  @Schema(example = "COLISEO ESTADIO DOSQUEBRADAS", required = true, description = "Nombre del puesto de votación.")
  public String getPuestoVotacion() {
    return puestoVotacion;
  }

  public void setPuestoVotacion(String puestoVotacion) {
    this.puestoVotacion = puestoVotacion;
  }

  public ResponsePuestoVotacionVO direccionPuesto(String direccionPuesto) {
    this.direccionPuesto = direccionPuesto;
    return this;
  }

   /**
   * Dirección del puesto de votación.
   * @return direccionPuesto
  **/
  @Schema(example = "KM 1 VIA ROMELIA EL POLLO", required = true, description = "Dirección del puesto de votación.")
  public String getDireccionPuesto() {
    return direccionPuesto;
  }

  public void setDireccionPuesto(String direccionPuesto) {
    this.direccionPuesto = direccionPuesto;
  }

  public ResponsePuestoVotacionVO fechaInscripcion(String fechaInscripcion) {
    this.fechaInscripcion = fechaInscripcion;
    return this;
  }

   /**
   * Get fechaInscripcion
   * @return fechaInscripcion
  **/
  @Schema(required = true, description = "")
  public String getFechaInscripcion() {
    return fechaInscripcion;
  }

  public void setFechaInscripcion(String fechaInscripcion) {
    this.fechaInscripcion = fechaInscripcion;
  }

  public ResponsePuestoVotacionVO resolucion(String resolucion) {
    this.resolucion = resolucion;
    return this;
  }

   /**
   * Número de resolución asociada (si aplica).
   * @return resolucion
  **/
  @Schema(required = true, description = "Número de resolución asociada (si aplica).")
  public String getResolucion() {
    return resolucion;
  }

  public void setResolucion(String resolucion) {
    this.resolucion = resolucion;
  }

  public ResponsePuestoVotacionVO fechaNovedad(String fechaNovedad) {
    this.fechaNovedad = fechaNovedad;
    return this;
  }

   /**
   * Get fechaNovedad
   * @return fechaNovedad
  **/
  @Schema(required = true, description = "")
  public String getFechaNovedad() {
    return fechaNovedad;
  }

  public void setFechaNovedad(String fechaNovedad) {
    this.fechaNovedad = fechaNovedad;
  }

  public ResponsePuestoVotacionVO mesa(String mesa) {
    this.mesa = mesa;
    return this;
  }

   /**
   * Número de mesa de votación.
   * @return mesa
  **/
  @Schema(example = "7", required = true, description = "Número de mesa de votación.")
  public String getMesa() {
    return mesa;
  }

  public void setMesa(String mesa) {
    this.mesa = mesa;
  }

  public ResponsePuestoVotacionVO fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Get fechaConsulta
   * @return fechaConsulta
  **/
  @Schema(required = true, description = "")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public ResponsePuestoVotacionVO fuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
    return this;
  }

   /**
   * Indica si la fuente falló en la consulta.
   * @return fuenteFallo
  **/
  @Schema(example = "NO", required = true, description = "Indica si la fuente falló en la consulta.")
  public FuenteFalloEnum getFuenteFallo() {
    return fuenteFallo;
  }

  public void setFuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsePuestoVotacionVO responsePuestoVotacionVO = (ResponsePuestoVotacionVO) o;
    return Objects.equals(this.estado, responsePuestoVotacionVO.estado) &&
        Objects.equals(this.departamento, responsePuestoVotacionVO.departamento) &&
        Objects.equals(this.municipio, responsePuestoVotacionVO.municipio) &&
        Objects.equals(this.puestoVotacion, responsePuestoVotacionVO.puestoVotacion) &&
        Objects.equals(this.direccionPuesto, responsePuestoVotacionVO.direccionPuesto) &&
        Objects.equals(this.fechaInscripcion, responsePuestoVotacionVO.fechaInscripcion) &&
        Objects.equals(this.resolucion, responsePuestoVotacionVO.resolucion) &&
        Objects.equals(this.fechaNovedad, responsePuestoVotacionVO.fechaNovedad) &&
        Objects.equals(this.mesa, responsePuestoVotacionVO.mesa) &&
        Objects.equals(this.fechaConsulta, responsePuestoVotacionVO.fechaConsulta) &&
        Objects.equals(this.fuenteFallo, responsePuestoVotacionVO.fuenteFallo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(estado, departamento, municipio, puestoVotacion, direccionPuesto, fechaInscripcion, resolucion, fechaNovedad, mesa, fechaConsulta, fuenteFallo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsePuestoVotacionVO {\n");
    
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    departamento: ").append(toIndentedString(departamento)).append("\n");
    sb.append("    municipio: ").append(toIndentedString(municipio)).append("\n");
    sb.append("    puestoVotacion: ").append(toIndentedString(puestoVotacion)).append("\n");
    sb.append("    direccionPuesto: ").append(toIndentedString(direccionPuesto)).append("\n");
    sb.append("    fechaInscripcion: ").append(toIndentedString(fechaInscripcion)).append("\n");
    sb.append("    resolucion: ").append(toIndentedString(resolucion)).append("\n");
    sb.append("    fechaNovedad: ").append(toIndentedString(fechaNovedad)).append("\n");
    sb.append("    mesa: ").append(toIndentedString(mesa)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    fuenteFallo: ").append(toIndentedString(fuenteFallo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
