/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseProcuraduriaVOListInhabilidades
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseProcuraduriaVOListInhabilidades {
  @SerializedName("nroSiri")
  private String nroSiri = null;

  @SerializedName("modulo")
  private String modulo = null;

  @SerializedName("inhabilidadLegal")
  private String inhabilidadLegal = null;

  @SerializedName("fechaInicio")
  private String fechaInicio = null;

  @SerializedName("fechaFin")
  private String fechaFin = null;

  public ResponseProcuraduriaVOListInhabilidades nroSiri(String nroSiri) {
    this.nroSiri = nroSiri;
    return this;
  }

   /**
   * Número de registro SIRI para la inhabilidad.
   * @return nroSiri
  **/
  @Schema(example = "201096378", required = true, description = "Número de registro SIRI para la inhabilidad.")
  public String getNroSiri() {
    return nroSiri;
  }

  public void setNroSiri(String nroSiri) {
    this.nroSiri = nroSiri;
  }

  public ResponseProcuraduriaVOListInhabilidades modulo(String modulo) {
    this.modulo = modulo;
    return this;
  }

   /**
   * Módulo o tipo de inhabilidad
   * @return modulo
  **/
  @Schema(example = "PENAL", required = true, description = "Módulo o tipo de inhabilidad")
  public String getModulo() {
    return modulo;
  }

  public void setModulo(String modulo) {
    this.modulo = modulo;
  }

  public ResponseProcuraduriaVOListInhabilidades inhabilidadLegal(String inhabilidadLegal) {
    this.inhabilidadLegal = inhabilidadLegal;
    return this;
  }

   /**
   * Descripción legal de la inhabilidad.
   * @return inhabilidadLegal
  **/
  @Schema(example = "INHABILIDAD PARA CONTRATAR CON EL ESTADO LEY 80 ART 8 LIT. D", required = true, description = "Descripción legal de la inhabilidad.")
  public String getInhabilidadLegal() {
    return inhabilidadLegal;
  }

  public void setInhabilidadLegal(String inhabilidadLegal) {
    this.inhabilidadLegal = inhabilidadLegal;
  }

  public ResponseProcuraduriaVOListInhabilidades fechaInicio(String fechaInicio) {
    this.fechaInicio = fechaInicio;
    return this;
  }

   /**
   * Get fechaInicio
   * @return fechaInicio
  **/
  @Schema(required = true, description = "")
  public String getFechaInicio() {
    return fechaInicio;
  }

  public void setFechaInicio(String fechaInicio) {
    this.fechaInicio = fechaInicio;
  }

  public ResponseProcuraduriaVOListInhabilidades fechaFin(String fechaFin) {
    this.fechaFin = fechaFin;
    return this;
  }

   /**
   * Get fechaFin
   * @return fechaFin
  **/
  @Schema(required = true, description = "")
  public String getFechaFin() {
    return fechaFin;
  }

  public void setFechaFin(String fechaFin) {
    this.fechaFin = fechaFin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseProcuraduriaVOListInhabilidades responseProcuraduriaVOListInhabilidades = (ResponseProcuraduriaVOListInhabilidades) o;
    return Objects.equals(this.nroSiri, responseProcuraduriaVOListInhabilidades.nroSiri) &&
        Objects.equals(this.modulo, responseProcuraduriaVOListInhabilidades.modulo) &&
        Objects.equals(this.inhabilidadLegal, responseProcuraduriaVOListInhabilidades.inhabilidadLegal) &&
        Objects.equals(this.fechaInicio, responseProcuraduriaVOListInhabilidades.fechaInicio) &&
        Objects.equals(this.fechaFin, responseProcuraduriaVOListInhabilidades.fechaFin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nroSiri, modulo, inhabilidadLegal, fechaInicio, fechaFin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseProcuraduriaVOListInhabilidades {\n");
    
    sb.append("    nroSiri: ").append(toIndentedString(nroSiri)).append("\n");
    sb.append("    modulo: ").append(toIndentedString(modulo)).append("\n");
    sb.append("    inhabilidadLegal: ").append(toIndentedString(inhabilidadLegal)).append("\n");
    sb.append("    fechaInicio: ").append(toIndentedString(fechaInicio)).append("\n");
    sb.append("    fechaFin: ").append(toIndentedString(fechaFin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
