/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseGarantiasMobiliariasVOAcreedores;
import io.swagger.client.model.ResponseGarantiasMobiliariasVOBienes;
import io.swagger.client.model.ResponseGarantiasMobiliariasVODeudores;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Colombia -  36256894 - Consulta del Registro de garantías mobiliarias.
 */
@Schema(description = "Colombia -  36256894 - Consulta del Registro de garantías mobiliarias.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseGarantiasMobiliariasVO {
  @SerializedName("deudores")
  private List<ResponseGarantiasMobiliariasVODeudores> deudores = new ArrayList<ResponseGarantiasMobiliariasVODeudores>();

  @SerializedName("acreedores")
  private List<ResponseGarantiasMobiliariasVOAcreedores> acreedores = new ArrayList<ResponseGarantiasMobiliariasVOAcreedores>();

  @SerializedName("bienes")
  private List<ResponseGarantiasMobiliariasVOBienes> bienes = new ArrayList<ResponseGarantiasMobiliariasVOBienes>();

  @SerializedName("folioElectronico")
  private String folioElectronico = null;

  @SerializedName("fechaInscripcion")
  private String fechaInscripcion = null;

  @SerializedName("fechaInscripcionInicial")
  private String fechaInscripcionInicial = null;

  @SerializedName("prioridadAdquisicion")
  private String prioridadAdquisicion = null;

  @SerializedName("tipoGarantia")
  private String tipoGarantia = null;

  @SerializedName("fechaFinalizacion")
  private String fechaFinalizacion = null;

  @SerializedName("datoReferencia")
  private String datoReferencia = null;

  @SerializedName("montoMaximo")
  private String montoMaximo = null;

  @SerializedName("tipoMoneda")
  private String tipoMoneda = null;

  @SerializedName("fechaInscripcionRegistroEspecial")
  private String fechaInscripcionRegistroEspecial = null;

  @SerializedName("garantiaInscritaRegistroEspecial")
  private String garantiaInscritaRegistroEspecial = null;

  @SerializedName("fechaConsulta")
  private String fechaConsulta = null;

  /**
   * Indica si la fuente falló en la consulta.
   */
  @JsonAdapter(FuenteFalloEnum.Adapter.class)
  public enum FuenteFalloEnum {
    @SerializedName("SI")
    SI("SI"),
    @SerializedName("NO")
    NO("NO");

    private String value;

    FuenteFalloEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FuenteFalloEnum fromValue(String input) {
      for (FuenteFalloEnum b : FuenteFalloEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FuenteFalloEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FuenteFalloEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public FuenteFalloEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return FuenteFalloEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("fuenteFallo")
  private FuenteFalloEnum fuenteFallo = null;

  public ResponseGarantiasMobiliariasVO deudores(List<ResponseGarantiasMobiliariasVODeudores> deudores) {
    this.deudores = deudores;
    return this;
  }

  public ResponseGarantiasMobiliariasVO addDeudoresItem(ResponseGarantiasMobiliariasVODeudores deudoresItem) {
    this.deudores.add(deudoresItem);
    return this;
  }

   /**
   * Listado de deudores asociados a la garantía.
   * @return deudores
  **/
  @Schema(required = true, description = "Listado de deudores asociados a la garantía.")
  public List<ResponseGarantiasMobiliariasVODeudores> getDeudores() {
    return deudores;
  }

  public void setDeudores(List<ResponseGarantiasMobiliariasVODeudores> deudores) {
    this.deudores = deudores;
  }

  public ResponseGarantiasMobiliariasVO acreedores(List<ResponseGarantiasMobiliariasVOAcreedores> acreedores) {
    this.acreedores = acreedores;
    return this;
  }

  public ResponseGarantiasMobiliariasVO addAcreedoresItem(ResponseGarantiasMobiliariasVOAcreedores acreedoresItem) {
    this.acreedores.add(acreedoresItem);
    return this;
  }

   /**
   * Listado de acreedores asociados a la garantía.
   * @return acreedores
  **/
  @Schema(required = true, description = "Listado de acreedores asociados a la garantía.")
  public List<ResponseGarantiasMobiliariasVOAcreedores> getAcreedores() {
    return acreedores;
  }

  public void setAcreedores(List<ResponseGarantiasMobiliariasVOAcreedores> acreedores) {
    this.acreedores = acreedores;
  }

  public ResponseGarantiasMobiliariasVO bienes(List<ResponseGarantiasMobiliariasVOBienes> bienes) {
    this.bienes = bienes;
    return this;
  }

  public ResponseGarantiasMobiliariasVO addBienesItem(ResponseGarantiasMobiliariasVOBienes bienesItem) {
    this.bienes.add(bienesItem);
    return this;
  }

   /**
   * Listado de bienes asociados a la garantía.
   * @return bienes
  **/
  @Schema(required = true, description = "Listado de bienes asociados a la garantía.")
  public List<ResponseGarantiasMobiliariasVOBienes> getBienes() {
    return bienes;
  }

  public void setBienes(List<ResponseGarantiasMobiliariasVOBienes> bienes) {
    this.bienes = bienes;
  }

  public ResponseGarantiasMobiliariasVO folioElectronico(String folioElectronico) {
    this.folioElectronico = folioElectronico;
    return this;
  }

   /**
   * Folio electrónico de la garantía.
   * @return folioElectronico
  **/
  @Schema(example = "20200706000025300", required = true, description = "Folio electrónico de la garantía.")
  public String getFolioElectronico() {
    return folioElectronico;
  }

  public void setFolioElectronico(String folioElectronico) {
    this.folioElectronico = folioElectronico;
  }

  public ResponseGarantiasMobiliariasVO fechaInscripcion(String fechaInscripcion) {
    this.fechaInscripcion = fechaInscripcion;
    return this;
  }

   /**
   * Get fechaInscripcion
   * @return fechaInscripcion
  **/
  @Schema(required = true, description = "")
  public String getFechaInscripcion() {
    return fechaInscripcion;
  }

  public void setFechaInscripcion(String fechaInscripcion) {
    this.fechaInscripcion = fechaInscripcion;
  }

  public ResponseGarantiasMobiliariasVO fechaInscripcionInicial(String fechaInscripcionInicial) {
    this.fechaInscripcionInicial = fechaInscripcionInicial;
    return this;
  }

   /**
   * Get fechaInscripcionInicial
   * @return fechaInscripcionInicial
  **/
  @Schema(required = true, description = "")
  public String getFechaInscripcionInicial() {
    return fechaInscripcionInicial;
  }

  public void setFechaInscripcionInicial(String fechaInscripcionInicial) {
    this.fechaInscripcionInicial = fechaInscripcionInicial;
  }

  public ResponseGarantiasMobiliariasVO prioridadAdquisicion(String prioridadAdquisicion) {
    this.prioridadAdquisicion = prioridadAdquisicion;
    return this;
  }

   /**
   * Indicador de prioridad de adquisición de la garantía.
   * @return prioridadAdquisicion
  **/
  @Schema(example = "No", required = true, description = "Indicador de prioridad de adquisición de la garantía.")
  public String getPrioridadAdquisicion() {
    return prioridadAdquisicion;
  }

  public void setPrioridadAdquisicion(String prioridadAdquisicion) {
    this.prioridadAdquisicion = prioridadAdquisicion;
  }

  public ResponseGarantiasMobiliariasVO tipoGarantia(String tipoGarantia) {
    this.tipoGarantia = tipoGarantia;
    return this;
  }

   /**
   * Tipo de garantía.
   * @return tipoGarantia
  **/
  @Schema(example = "Garantía Mobiliaria", required = true, description = "Tipo de garantía.")
  public String getTipoGarantia() {
    return tipoGarantia;
  }

  public void setTipoGarantia(String tipoGarantia) {
    this.tipoGarantia = tipoGarantia;
  }

  public ResponseGarantiasMobiliariasVO fechaFinalizacion(String fechaFinalizacion) {
    this.fechaFinalizacion = fechaFinalizacion;
    return this;
  }

   /**
   * Get fechaFinalizacion
   * @return fechaFinalizacion
  **/
  @Schema(required = true, description = "")
  public String getFechaFinalizacion() {
    return fechaFinalizacion;
  }

  public void setFechaFinalizacion(String fechaFinalizacion) {
    this.fechaFinalizacion = fechaFinalizacion;
  }

  public ResponseGarantiasMobiliariasVO datoReferencia(String datoReferencia) {
    this.datoReferencia = datoReferencia;
    return this;
  }

   /**
   * Dato de referencia de la garantía.
   * @return datoReferencia
  **/
  @Schema(example = "1261813", required = true, description = "Dato de referencia de la garantía.")
  public String getDatoReferencia() {
    return datoReferencia;
  }

  public void setDatoReferencia(String datoReferencia) {
    this.datoReferencia = datoReferencia;
  }

  public ResponseGarantiasMobiliariasVO montoMaximo(String montoMaximo) {
    this.montoMaximo = montoMaximo;
    return this;
  }

   /**
   * Monto máximo cubierto por la garantía.
   * @return montoMaximo
  **/
  @Schema(example = "$ 49.490.000", required = true, description = "Monto máximo cubierto por la garantía.")
  public String getMontoMaximo() {
    return montoMaximo;
  }

  public void setMontoMaximo(String montoMaximo) {
    this.montoMaximo = montoMaximo;
  }

  public ResponseGarantiasMobiliariasVO tipoMoneda(String tipoMoneda) {
    this.tipoMoneda = tipoMoneda;
    return this;
  }

   /**
   * Tipo de moneda del monto máximo.
   * @return tipoMoneda
  **/
  @Schema(example = "Peso colombiano", required = true, description = "Tipo de moneda del monto máximo.")
  public String getTipoMoneda() {
    return tipoMoneda;
  }

  public void setTipoMoneda(String tipoMoneda) {
    this.tipoMoneda = tipoMoneda;
  }

  public ResponseGarantiasMobiliariasVO fechaInscripcionRegistroEspecial(String fechaInscripcionRegistroEspecial) {
    this.fechaInscripcionRegistroEspecial = fechaInscripcionRegistroEspecial;
    return this;
  }

   /**
   * Get fechaInscripcionRegistroEspecial
   * @return fechaInscripcionRegistroEspecial
  **/
  @Schema(required = true, description = "")
  public String getFechaInscripcionRegistroEspecial() {
    return fechaInscripcionRegistroEspecial;
  }

  public void setFechaInscripcionRegistroEspecial(String fechaInscripcionRegistroEspecial) {
    this.fechaInscripcionRegistroEspecial = fechaInscripcionRegistroEspecial;
  }

  public ResponseGarantiasMobiliariasVO garantiaInscritaRegistroEspecial(String garantiaInscritaRegistroEspecial) {
    this.garantiaInscritaRegistroEspecial = garantiaInscritaRegistroEspecial;
    return this;
  }

   /**
   * Get garantiaInscritaRegistroEspecial
   * @return garantiaInscritaRegistroEspecial
  **/
  @Schema(required = true, description = "")
  public String getGarantiaInscritaRegistroEspecial() {
    return garantiaInscritaRegistroEspecial;
  }

  public void setGarantiaInscritaRegistroEspecial(String garantiaInscritaRegistroEspecial) {
    this.garantiaInscritaRegistroEspecial = garantiaInscritaRegistroEspecial;
  }

  public ResponseGarantiasMobiliariasVO fechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
    return this;
  }

   /**
   * Get fechaConsulta
   * @return fechaConsulta
  **/
  @Schema(required = true, description = "")
  public String getFechaConsulta() {
    return fechaConsulta;
  }

  public void setFechaConsulta(String fechaConsulta) {
    this.fechaConsulta = fechaConsulta;
  }

  public ResponseGarantiasMobiliariasVO fuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
    return this;
  }

   /**
   * Indica si la fuente falló en la consulta.
   * @return fuenteFallo
  **/
  @Schema(example = "NO", required = true, description = "Indica si la fuente falló en la consulta.")
  public FuenteFalloEnum getFuenteFallo() {
    return fuenteFallo;
  }

  public void setFuenteFallo(FuenteFalloEnum fuenteFallo) {
    this.fuenteFallo = fuenteFallo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseGarantiasMobiliariasVO responseGarantiasMobiliariasVO = (ResponseGarantiasMobiliariasVO) o;
    return Objects.equals(this.deudores, responseGarantiasMobiliariasVO.deudores) &&
        Objects.equals(this.acreedores, responseGarantiasMobiliariasVO.acreedores) &&
        Objects.equals(this.bienes, responseGarantiasMobiliariasVO.bienes) &&
        Objects.equals(this.folioElectronico, responseGarantiasMobiliariasVO.folioElectronico) &&
        Objects.equals(this.fechaInscripcion, responseGarantiasMobiliariasVO.fechaInscripcion) &&
        Objects.equals(this.fechaInscripcionInicial, responseGarantiasMobiliariasVO.fechaInscripcionInicial) &&
        Objects.equals(this.prioridadAdquisicion, responseGarantiasMobiliariasVO.prioridadAdquisicion) &&
        Objects.equals(this.tipoGarantia, responseGarantiasMobiliariasVO.tipoGarantia) &&
        Objects.equals(this.fechaFinalizacion, responseGarantiasMobiliariasVO.fechaFinalizacion) &&
        Objects.equals(this.datoReferencia, responseGarantiasMobiliariasVO.datoReferencia) &&
        Objects.equals(this.montoMaximo, responseGarantiasMobiliariasVO.montoMaximo) &&
        Objects.equals(this.tipoMoneda, responseGarantiasMobiliariasVO.tipoMoneda) &&
        Objects.equals(this.fechaInscripcionRegistroEspecial, responseGarantiasMobiliariasVO.fechaInscripcionRegistroEspecial) &&
        Objects.equals(this.garantiaInscritaRegistroEspecial, responseGarantiasMobiliariasVO.garantiaInscritaRegistroEspecial) &&
        Objects.equals(this.fechaConsulta, responseGarantiasMobiliariasVO.fechaConsulta) &&
        Objects.equals(this.fuenteFallo, responseGarantiasMobiliariasVO.fuenteFallo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deudores, acreedores, bienes, folioElectronico, fechaInscripcion, fechaInscripcionInicial, prioridadAdquisicion, tipoGarantia, fechaFinalizacion, datoReferencia, montoMaximo, tipoMoneda, fechaInscripcionRegistroEspecial, garantiaInscritaRegistroEspecial, fechaConsulta, fuenteFallo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseGarantiasMobiliariasVO {\n");
    
    sb.append("    deudores: ").append(toIndentedString(deudores)).append("\n");
    sb.append("    acreedores: ").append(toIndentedString(acreedores)).append("\n");
    sb.append("    bienes: ").append(toIndentedString(bienes)).append("\n");
    sb.append("    folioElectronico: ").append(toIndentedString(folioElectronico)).append("\n");
    sb.append("    fechaInscripcion: ").append(toIndentedString(fechaInscripcion)).append("\n");
    sb.append("    fechaInscripcionInicial: ").append(toIndentedString(fechaInscripcionInicial)).append("\n");
    sb.append("    prioridadAdquisicion: ").append(toIndentedString(prioridadAdquisicion)).append("\n");
    sb.append("    tipoGarantia: ").append(toIndentedString(tipoGarantia)).append("\n");
    sb.append("    fechaFinalizacion: ").append(toIndentedString(fechaFinalizacion)).append("\n");
    sb.append("    datoReferencia: ").append(toIndentedString(datoReferencia)).append("\n");
    sb.append("    montoMaximo: ").append(toIndentedString(montoMaximo)).append("\n");
    sb.append("    tipoMoneda: ").append(toIndentedString(tipoMoneda)).append("\n");
    sb.append("    fechaInscripcionRegistroEspecial: ").append(toIndentedString(fechaInscripcionRegistroEspecial)).append("\n");
    sb.append("    garantiaInscritaRegistroEspecial: ").append(toIndentedString(garantiaInscritaRegistroEspecial)).append("\n");
    sb.append("    fechaConsulta: ").append(toIndentedString(fechaConsulta)).append("\n");
    sb.append("    fuenteFallo: ").append(toIndentedString(fuenteFallo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
