/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ResponseRuntVODetalleLicencias;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ResponseRuntVOLicenciasConduccion
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuntVOLicenciasConduccion {
  @SerializedName("numeroLicencia")
  private String numeroLicencia = null;

  @SerializedName("otExpide")
  private String otExpide = null;

  @SerializedName("fechaExpedicion")
  private String fechaExpedicion = null;

  @SerializedName("estadoLicencia")
  private String estadoLicencia = null;

  @SerializedName("restricciones")
  private String restricciones = null;

  @SerializedName("detalleLicencias")
  private List<ResponseRuntVODetalleLicencias> detalleLicencias = null;

  public ResponseRuntVOLicenciasConduccion numeroLicencia(String numeroLicencia) {
    this.numeroLicencia = numeroLicencia;
    return this;
  }

   /**
   * Número de la licencia de conducción.
   * @return numeroLicencia
  **/
  @Schema(example = "ND1098XX", description = "Número de la licencia de conducción.")
  public String getNumeroLicencia() {
    return numeroLicencia;
  }

  public void setNumeroLicencia(String numeroLicencia) {
    this.numeroLicencia = numeroLicencia;
  }

  public ResponseRuntVOLicenciasConduccion otExpide(String otExpide) {
    this.otExpide = otExpide;
    return this;
  }

   /**
   * Organismo de Tránsito que expide la licencia.
   * @return otExpide
  **/
  @Schema(example = "INST TTO ATLANTICO/SABANAGRANDE", description = "Organismo de Tránsito que expide la licencia.")
  public String getOtExpide() {
    return otExpide;
  }

  public void setOtExpide(String otExpide) {
    this.otExpide = otExpide;
  }

  public ResponseRuntVOLicenciasConduccion fechaExpedicion(String fechaExpedicion) {
    this.fechaExpedicion = fechaExpedicion;
    return this;
  }

   /**
   * Get fechaExpedicion
   * @return fechaExpedicion
  **/
  @Schema(description = "")
  public String getFechaExpedicion() {
    return fechaExpedicion;
  }

  public void setFechaExpedicion(String fechaExpedicion) {
    this.fechaExpedicion = fechaExpedicion;
  }

  public ResponseRuntVOLicenciasConduccion estadoLicencia(String estadoLicencia) {
    this.estadoLicencia = estadoLicencia;
    return this;
  }

   /**
   * Estado actual de la licencia de conducción.
   * @return estadoLicencia
  **/
  @Schema(example = "ACTIVA", description = "Estado actual de la licencia de conducción.")
  public String getEstadoLicencia() {
    return estadoLicencia;
  }

  public void setEstadoLicencia(String estadoLicencia) {
    this.estadoLicencia = estadoLicencia;
  }

  public ResponseRuntVOLicenciasConduccion restricciones(String restricciones) {
    this.restricciones = restricciones;
    return this;
  }

   /**
   * Restricciones asociadas a la licencia.
   * @return restricciones
  **/
  @Schema(description = "Restricciones asociadas a la licencia.")
  public String getRestricciones() {
    return restricciones;
  }

  public void setRestricciones(String restricciones) {
    this.restricciones = restricciones;
  }

  public ResponseRuntVOLicenciasConduccion detalleLicencias(List<ResponseRuntVODetalleLicencias> detalleLicencias) {
    this.detalleLicencias = detalleLicencias;
    return this;
  }

  public ResponseRuntVOLicenciasConduccion addDetalleLicenciasItem(ResponseRuntVODetalleLicencias detalleLicenciasItem) {
    if (this.detalleLicencias == null) {
      this.detalleLicencias = new ArrayList<ResponseRuntVODetalleLicencias>();
    }
    this.detalleLicencias.add(detalleLicenciasItem);
    return this;
  }

   /**
   * Detalles de categorías y vencimientos de la licencia.
   * @return detalleLicencias
  **/
  @Schema(description = "Detalles de categorías y vencimientos de la licencia.")
  public List<ResponseRuntVODetalleLicencias> getDetalleLicencias() {
    return detalleLicencias;
  }

  public void setDetalleLicencias(List<ResponseRuntVODetalleLicencias> detalleLicencias) {
    this.detalleLicencias = detalleLicencias;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuntVOLicenciasConduccion responseRuntVOLicenciasConduccion = (ResponseRuntVOLicenciasConduccion) o;
    return Objects.equals(this.numeroLicencia, responseRuntVOLicenciasConduccion.numeroLicencia) &&
        Objects.equals(this.otExpide, responseRuntVOLicenciasConduccion.otExpide) &&
        Objects.equals(this.fechaExpedicion, responseRuntVOLicenciasConduccion.fechaExpedicion) &&
        Objects.equals(this.estadoLicencia, responseRuntVOLicenciasConduccion.estadoLicencia) &&
        Objects.equals(this.restricciones, responseRuntVOLicenciasConduccion.restricciones) &&
        Objects.equals(this.detalleLicencias, responseRuntVOLicenciasConduccion.detalleLicencias);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroLicencia, otExpide, fechaExpedicion, estadoLicencia, restricciones, detalleLicencias);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuntVOLicenciasConduccion {\n");
    
    sb.append("    numeroLicencia: ").append(toIndentedString(numeroLicencia)).append("\n");
    sb.append("    otExpide: ").append(toIndentedString(otExpide)).append("\n");
    sb.append("    fechaExpedicion: ").append(toIndentedString(fechaExpedicion)).append("\n");
    sb.append("    estadoLicencia: ").append(toIndentedString(estadoLicencia)).append("\n");
    sb.append("    restricciones: ").append(toIndentedString(restricciones)).append("\n");
    sb.append("    detalleLicencias: ").append(toIndentedString(detalleLicencias)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
