/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Detalles del directorio de la empresa.
 */
@Schema(description = "Detalles del directorio de la empresa.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseDirectorioEmpresasVOInformacionDirectorio {
  @SerializedName("nombreEmpresa")
  private String nombreEmpresa = null;

  @SerializedName("nit")
  private String nit = null;

  @SerializedName("direccion")
  private String direccion = null;

  @SerializedName("ciudad")
  private String ciudad = null;

  @SerializedName("departamento")
  private String departamento = null;

  @SerializedName("telefono")
  private String telefono = null;

  @SerializedName("actividad")
  private String actividad = null;

  @SerializedName("ultimaFacturacionRegistrada")
  private String ultimaFacturacionRegistrada = null;

  public ResponseDirectorioEmpresasVOInformacionDirectorio nombreEmpresa(String nombreEmpresa) {
    this.nombreEmpresa = nombreEmpresa;
    return this;
  }

   /**
   * Nombre o razón social de la empresa.
   * @return nombreEmpresa
  **/
  @Schema(example = "Ferreteria Berce E U", required = true, description = "Nombre o razón social de la empresa.")
  public String getNombreEmpresa() {
    return nombreEmpresa;
  }

  public void setNombreEmpresa(String nombreEmpresa) {
    this.nombreEmpresa = nombreEmpresa;
  }

  public ResponseDirectorioEmpresasVOInformacionDirectorio nit(String nit) {
    this.nit = nit;
    return this;
  }

   /**
   * Número de Identificación Tributaria (NIT) de la empresa.
   * @return nit
  **/
  @Schema(example = "8060096369", required = true, description = "Número de Identificación Tributaria (NIT) de la empresa.")
  public String getNit() {
    return nit;
  }

  public void setNit(String nit) {
    this.nit = nit;
  }

  public ResponseDirectorioEmpresasVOInformacionDirectorio direccion(String direccion) {
    this.direccion = direccion;
    return this;
  }

   /**
   * Dirección de la empresa.
   * @return direccion
  **/
  @Schema(example = "AVENIDA PEDRO DE HEREDIA 49 99", required = true, description = "Dirección de la empresa.")
  public String getDireccion() {
    return direccion;
  }

  public void setDireccion(String direccion) {
    this.direccion = direccion;
  }

  public ResponseDirectorioEmpresasVOInformacionDirectorio ciudad(String ciudad) {
    this.ciudad = ciudad;
    return this;
  }

   /**
   * Ciudad de la empresa.
   * @return ciudad
  **/
  @Schema(example = "CARTAGENA", required = true, description = "Ciudad de la empresa.")
  public String getCiudad() {
    return ciudad;
  }

  public void setCiudad(String ciudad) {
    this.ciudad = ciudad;
  }

  public ResponseDirectorioEmpresasVOInformacionDirectorio departamento(String departamento) {
    this.departamento = departamento;
    return this;
  }

   /**
   * Departamento de la empresa.
   * @return departamento
  **/
  @Schema(example = "BOLIVAR", required = true, description = "Departamento de la empresa.")
  public String getDepartamento() {
    return departamento;
  }

  public void setDepartamento(String departamento) {
    this.departamento = departamento;
  }

  public ResponseDirectorioEmpresasVOInformacionDirectorio telefono(String telefono) {
    this.telefono = telefono;
    return this;
  }

   /**
   * Número de teléfono de la empresa.
   * @return telefono
  **/
  @Schema(example = "(5)6697361", required = true, description = "Número de teléfono de la empresa.")
  public String getTelefono() {
    return telefono;
  }

  public void setTelefono(String telefono) {
    this.telefono = telefono;
  }

  public ResponseDirectorioEmpresasVOInformacionDirectorio actividad(String actividad) {
    this.actividad = actividad;
    return this;
  }

   /**
   * Descripción de la actividad comercial principal.
   * @return actividad
  **/
  @Schema(example = "Comercio al por menor de articulos de ferreteria pinturas y productos de vidrio en establecimientos especializados", required = true, description = "Descripción de la actividad comercial principal.")
  public String getActividad() {
    return actividad;
  }

  public void setActividad(String actividad) {
    this.actividad = actividad;
  }

  public ResponseDirectorioEmpresasVOInformacionDirectorio ultimaFacturacionRegistrada(String ultimaFacturacionRegistrada) {
    this.ultimaFacturacionRegistrada = ultimaFacturacionRegistrada;
    return this;
  }

   /**
   * Fecha o período de la última facturación registrada. Puede estar vacío.
   * @return ultimaFacturacionRegistrada
  **/
  @Schema(required = true, description = "Fecha o período de la última facturación registrada. Puede estar vacío.")
  public String getUltimaFacturacionRegistrada() {
    return ultimaFacturacionRegistrada;
  }

  public void setUltimaFacturacionRegistrada(String ultimaFacturacionRegistrada) {
    this.ultimaFacturacionRegistrada = ultimaFacturacionRegistrada;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseDirectorioEmpresasVOInformacionDirectorio responseDirectorioEmpresasVOInformacionDirectorio = (ResponseDirectorioEmpresasVOInformacionDirectorio) o;
    return Objects.equals(this.nombreEmpresa, responseDirectorioEmpresasVOInformacionDirectorio.nombreEmpresa) &&
        Objects.equals(this.nit, responseDirectorioEmpresasVOInformacionDirectorio.nit) &&
        Objects.equals(this.direccion, responseDirectorioEmpresasVOInformacionDirectorio.direccion) &&
        Objects.equals(this.ciudad, responseDirectorioEmpresasVOInformacionDirectorio.ciudad) &&
        Objects.equals(this.departamento, responseDirectorioEmpresasVOInformacionDirectorio.departamento) &&
        Objects.equals(this.telefono, responseDirectorioEmpresasVOInformacionDirectorio.telefono) &&
        Objects.equals(this.actividad, responseDirectorioEmpresasVOInformacionDirectorio.actividad) &&
        Objects.equals(this.ultimaFacturacionRegistrada, responseDirectorioEmpresasVOInformacionDirectorio.ultimaFacturacionRegistrada);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nombreEmpresa, nit, direccion, ciudad, departamento, telefono, actividad, ultimaFacturacionRegistrada);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseDirectorioEmpresasVOInformacionDirectorio {\n");
    
    sb.append("    nombreEmpresa: ").append(toIndentedString(nombreEmpresa)).append("\n");
    sb.append("    nit: ").append(toIndentedString(nit)).append("\n");
    sb.append("    direccion: ").append(toIndentedString(direccion)).append("\n");
    sb.append("    ciudad: ").append(toIndentedString(ciudad)).append("\n");
    sb.append("    departamento: ").append(toIndentedString(departamento)).append("\n");
    sb.append("    telefono: ").append(toIndentedString(telefono)).append("\n");
    sb.append("    actividad: ").append(toIndentedString(actividad)).append("\n");
    sb.append("    ultimaFacturacionRegistrada: ").append(toIndentedString(ultimaFacturacionRegistrada)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
