/*
 * API Konivin
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseRuntVOCertificadosAptitudConduccion
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-01T20:01:52.954733595Z[GMT]")

public class ResponseRuntVOCertificadosAptitudConduccion {
  @SerializedName("numeroCertificado")
  private String numeroCertificado = null;

  @SerializedName("nombreCea")
  private String nombreCea = null;

  @SerializedName("fechaExpedicion")
  private String fechaExpedicion = null;

  @SerializedName("categoria")
  private String categoria = null;

  @SerializedName("tipoCertificado")
  private String tipoCertificado = null;

  @SerializedName("estado")
  private String estado = null;

  @SerializedName("nroSolicitud")
  private String nroSolicitud = null;

  @SerializedName("fechaSolicitud")
  private String fechaSolicitud = null;

  @SerializedName("nroFupa")
  private String nroFupa = null;

  @SerializedName("tramiteSolicitado")
  private String tramiteSolicitado = null;

  public ResponseRuntVOCertificadosAptitudConduccion numeroCertificado(String numeroCertificado) {
    this.numeroCertificado = numeroCertificado;
    return this;
  }

   /**
   * Número del certificado de aptitud en conducción.
   * @return numeroCertificado
  **/
  @Schema(example = "12763051", required = true, description = "Número del certificado de aptitud en conducción.")
  public String getNumeroCertificado() {
    return numeroCertificado;
  }

  public void setNumeroCertificado(String numeroCertificado) {
    this.numeroCertificado = numeroCertificado;
  }

  public ResponseRuntVOCertificadosAptitudConduccion nombreCea(String nombreCea) {
    this.nombreCea = nombreCea;
    return this;
  }

   /**
   * Nombre del Centro de Enseñanza Automovilística (CEA).
   * @return nombreCea
  **/
  @Schema(example = "CENTRO DE ENSEÃ¿ANZA AUTOMOVILISTICA VERDADEROS PILOTOS", required = true, description = "Nombre del Centro de Enseñanza Automovilística (CEA).")
  public String getNombreCea() {
    return nombreCea;
  }

  public void setNombreCea(String nombreCea) {
    this.nombreCea = nombreCea;
  }

  public ResponseRuntVOCertificadosAptitudConduccion fechaExpedicion(String fechaExpedicion) {
    this.fechaExpedicion = fechaExpedicion;
    return this;
  }

   /**
   * Get fechaExpedicion
   * @return fechaExpedicion
  **/
  @Schema(required = true, description = "")
  public String getFechaExpedicion() {
    return fechaExpedicion;
  }

  public void setFechaExpedicion(String fechaExpedicion) {
    this.fechaExpedicion = fechaExpedicion;
  }

  public ResponseRuntVOCertificadosAptitudConduccion categoria(String categoria) {
    this.categoria = categoria;
    return this;
  }

   /**
   * Categoría de conducción asociada al certificado.
   * @return categoria
  **/
  @Schema(example = "C1", required = true, description = "Categoría de conducción asociada al certificado.")
  public String getCategoria() {
    return categoria;
  }

  public void setCategoria(String categoria) {
    this.categoria = categoria;
  }

  public ResponseRuntVOCertificadosAptitudConduccion tipoCertificado(String tipoCertificado) {
    this.tipoCertificado = tipoCertificado;
    return this;
  }

   /**
   * Tipo de certificado.
   * @return tipoCertificado
  **/
  @Schema(example = "CERTIFICADO CONDUCTOR", required = true, description = "Tipo de certificado.")
  public String getTipoCertificado() {
    return tipoCertificado;
  }

  public void setTipoCertificado(String tipoCertificado) {
    this.tipoCertificado = tipoCertificado;
  }

  public ResponseRuntVOCertificadosAptitudConduccion estado(String estado) {
    this.estado = estado;
    return this;
  }

   /**
   * Estado del certificado
   * @return estado
  **/
  @Schema(example = "UTILIZADO", required = true, description = "Estado del certificado")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public ResponseRuntVOCertificadosAptitudConduccion nroSolicitud(String nroSolicitud) {
    this.nroSolicitud = nroSolicitud;
    return this;
  }

   /**
   * Número de solicitud asociada.
   * @return nroSolicitud
  **/
  @Schema(example = "68116669", required = true, description = "Número de solicitud asociada.")
  public String getNroSolicitud() {
    return nroSolicitud;
  }

  public void setNroSolicitud(String nroSolicitud) {
    this.nroSolicitud = nroSolicitud;
  }

  public ResponseRuntVOCertificadosAptitudConduccion fechaSolicitud(String fechaSolicitud) {
    this.fechaSolicitud = fechaSolicitud;
    return this;
  }

   /**
   * Get fechaSolicitud
   * @return fechaSolicitud
  **/
  @Schema(required = true, description = "")
  public String getFechaSolicitud() {
    return fechaSolicitud;
  }

  public void setFechaSolicitud(String fechaSolicitud) {
    this.fechaSolicitud = fechaSolicitud;
  }

  public ResponseRuntVOCertificadosAptitudConduccion nroFupa(String nroFupa) {
    this.nroFupa = nroFupa;
    return this;
  }

   /**
   * Número FUPA (Formulario Único de Personas Aptas).
   * @return nroFupa
  **/
  @Schema(example = "600000000029260713", required = true, description = "Número FUPA (Formulario Único de Personas Aptas).")
  public String getNroFupa() {
    return nroFupa;
  }

  public void setNroFupa(String nroFupa) {
    this.nroFupa = nroFupa;
  }

  public ResponseRuntVOCertificadosAptitudConduccion tramiteSolicitado(String tramiteSolicitado) {
    this.tramiteSolicitado = tramiteSolicitado;
    return this;
  }

   /**
   * Trámite solicitado.
   * @return tramiteSolicitado
  **/
  @Schema(example = "Tramite expedicion licencia conduccion", required = true, description = "Trámite solicitado.")
  public String getTramiteSolicitado() {
    return tramiteSolicitado;
  }

  public void setTramiteSolicitado(String tramiteSolicitado) {
    this.tramiteSolicitado = tramiteSolicitado;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRuntVOCertificadosAptitudConduccion responseRuntVOCertificadosAptitudConduccion = (ResponseRuntVOCertificadosAptitudConduccion) o;
    return Objects.equals(this.numeroCertificado, responseRuntVOCertificadosAptitudConduccion.numeroCertificado) &&
        Objects.equals(this.nombreCea, responseRuntVOCertificadosAptitudConduccion.nombreCea) &&
        Objects.equals(this.fechaExpedicion, responseRuntVOCertificadosAptitudConduccion.fechaExpedicion) &&
        Objects.equals(this.categoria, responseRuntVOCertificadosAptitudConduccion.categoria) &&
        Objects.equals(this.tipoCertificado, responseRuntVOCertificadosAptitudConduccion.tipoCertificado) &&
        Objects.equals(this.estado, responseRuntVOCertificadosAptitudConduccion.estado) &&
        Objects.equals(this.nroSolicitud, responseRuntVOCertificadosAptitudConduccion.nroSolicitud) &&
        Objects.equals(this.fechaSolicitud, responseRuntVOCertificadosAptitudConduccion.fechaSolicitud) &&
        Objects.equals(this.nroFupa, responseRuntVOCertificadosAptitudConduccion.nroFupa) &&
        Objects.equals(this.tramiteSolicitado, responseRuntVOCertificadosAptitudConduccion.tramiteSolicitado);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroCertificado, nombreCea, fechaExpedicion, categoria, tipoCertificado, estado, nroSolicitud, fechaSolicitud, nroFupa, tramiteSolicitado);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRuntVOCertificadosAptitudConduccion {\n");
    
    sb.append("    numeroCertificado: ").append(toIndentedString(numeroCertificado)).append("\n");
    sb.append("    nombreCea: ").append(toIndentedString(nombreCea)).append("\n");
    sb.append("    fechaExpedicion: ").append(toIndentedString(fechaExpedicion)).append("\n");
    sb.append("    categoria: ").append(toIndentedString(categoria)).append("\n");
    sb.append("    tipoCertificado: ").append(toIndentedString(tipoCertificado)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    nroSolicitud: ").append(toIndentedString(nroSolicitud)).append("\n");
    sb.append("    fechaSolicitud: ").append(toIndentedString(fechaSolicitud)).append("\n");
    sb.append("    nroFupa: ").append(toIndentedString(nroFupa)).append("\n");
    sb.append("    tramiteSolicitado: ").append(toIndentedString(tramiteSolicitado)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
